### ISSUE TITLE
metrics-graphite-3.1.2.jar on Cassandra 2.2

### ISSUE THREAD

**Issue by orshemesh** [dropwizard/metrics#1000]
Hi,

I saw that Cassandra using your JAR to report metrics to the Graphite,
Cassandra 2.2 use metrics-core-3.1.0.jar,metrics-logback-3.1.0.jar and I add metrics-graphite-3.1.2.jar to Cassandra and now it sends to the Graphite only Cassandra metrics org.apache.cassandra.metrics.* but doesn't expose metrics from java.lang.*.

What I'm missing so your JAR will report metrics on java.lang.*? 

Thanks

**Comment by ryantenney** [comment]
What metrics are available from java.lang?

**Comment by ryanrupp** [comment]
I think you're looking for the metrics-jvm jar - http://metrics.dropwizard.io/3.1.0/manual/jvm/ - it looks like current versions of Cassandra already may be registering this module (look for metrics under jvm.*) - references to registering these in Cassandra source at least [here](https://github.com/apache/cassandra/blob/f56c0c6685a490c9237f5f8ff0baa84f3441b545/src/java/org/apache/cassandra/service/CassandraDaemon.java#L363) - but looks like this was a recent change [commit here](https://github.com/apache/cassandra/commit/3cda6829ccbbfaac08092773b55c9ee315dd5bbd)

So, not sure how you'd add that in Cassandra 2.2 but that's the metrics module I think you're looking for.

**Comment by ryanrupp** [comment]
Looks like maybe those JVM metrics got lost when Cassandra upgraded from Metrics 2.x to 3.x - the related Jira [here](https://issues.apache.org/jira/browse/CASSANDRA-12312)

**Comment by orshemesh** [comment]
Thanks,
You're right , I'm using Cassandra 2.2.7 and only in Cassandra 2.2.8 these metrics will be available.
