### ISSUE TITLE
miss a function name()

### ISSUE THREAD

**Issue by silentString** [dropwizard/metrics#1002]
In the class of GangliaReporter, the function prefix() used a function name(), but name() did not define in the class GangliaReporter, neither in it's superclass

**Comment by ryanrupp** [comment]
It should be coming from the static import, see (here)[https://github.com/dropwizard/metrics/blob/3.2-development/metrics-ganglia/src/main/java/com/codahale/metrics/ganglia/GangliaReporter.java#L18]
