### ISSUE TITLE
NaN mean timer value and standard deviation

### ISSUE THREAD

**Issue by gkopff** [dropwizard/metrics#1005]
I am using `3.1.0` and have started seeing `NaN` values for the mean and standard deviation of timers.  (Until recently, I was using `3.0.1` and I never had a NaN value.)

```
"theTimer" : {
      "count" : 4332,
      "max" : 0.288696783,
      "mean" : "NaN",
      "min" : 6.00388E-4,
      "p50" : 0.003298735,
      "p75" : 0.003298735,
      "p95" : 0.003298735,
      "p98" : 0.003298735,
      "p99" : 0.003298735,
      "p999" : 0.003298735,
      "stddev" : "NaN",
      "m15_rate" : 0.08561987306180467,
      "m1_rate" : 0.03960663833117155,
      "m5_rate" : 0.10383331627579845,
      "mean_rate" : 0.02467728882193572,
      "duration_units" : "seconds",
      "rate_units" : "calls/second"
    },
```

I don't think this is expected, is it?

Looking back through the change-log, it appears that `v1.0.2` (Mar 08 2010) eliminated NaN values from timers:

> Timer now uses Welford’s algorithm for calculating running variance, which means no more hilariously wrong standard deviations (e.g., NaN).

Is this a bug?

**Comment by arteam** [comment]
Should be fixed by #1033
