### ISSUE TITLE
`MetricsRegistry.remove` is not the inverse of `MetricsRegistry.register`

### ISSUE THREAD

**Issue by timmc** [dropwizard/metrics#1007]
If I register a metric and then remove it, I expect that I should then be able to register it again. (Think of unit tests where you are testing setup and teardown of an app.) However, this does not work without writing additional recursive code on top of this library.

Specifically, `MetricRegistry.register` can [accept a MetricSet](https://github.com/dropwizard/metrics/blob/ed96867/metrics-core/src/main/java/com/codahale/metrics/MetricRegistry.java#L84) and recursively add the component metrics, deriving the names as it goes. On the other hand, `.remove` [only removes a single metric](https://github.com/dropwizard/metrics/blob/ed96867/metrics-core/src/main/java/com/codahale/metrics/MetricRegistry.java#L158).

(This is at the bottom of a pile of yak-shaving for me, so I'm not sure I can offer a PR in good faith.)

**Comment by ryanrupp** [comment]
As an alternative you can use [https://github.com/dropwizard/metrics/blob/ed96867/metrics-core/src/main/java/com/codahale/metrics/MetricRegistry.java#L171](removeMatching) and have `MetricFilter` that matches on the prefix that you used for the MetricSet name (could get false positives if you register other metric sets or unrelated metrics under the same name prefix though).

**Comment by timmc** [comment]
@mostafakashif I saw some commits regarding this issue. Any chance a PR is in the works? (This is no longer directly relevant for me, as it came up at my job, and I'm now on a different team—but it might be useful for others.)
