### ISSUE TITLE
Thoughts on Gauge-backed Histogram

### ISSUE THREAD

**Issue by jhaber** [dropwizard/metrics#1009]
Sorry if this issue is a duplicate, but I searched around and couldn't find anything. We have an issue that affects a lot of our usages of `Gauge`. We have gauges for things like number of active HTTP requests, the sizes of various thread pools, connection pools, etc. Our applications report metrics every minute but the data from these gauges isn't particularly useful because it's just a snapshot at the instant that the application happened to report in, so if there's a short spike it's unlikely to be captured and at this granularity you don't get any sense of the distribution of values over the report interval. We could temporarily increase the reporting frequency when debugging an application but this would ship a lot of extra datapoints for which minute granularity is fine and also we often want to diagnose problems in the past where we're not able to retroactively increase the granularity.

Our idea for how to make these gauges more useful is to have a new type of metric that's essentially a histogram backed by an underlying gauge. You'd fetch the value from the gauge at a fixed interval (configurable when you create the metric, but let's use 1 second as an example) and update the histogram and then report the histogram distributions like usual. Using thread pools as an example, this would give you much more insight into what's going on than a single snapshot taken at the end of the report interval. We can implement something like this ourselves on top of the existing API, but we were wondering if (a) does the problem and our solution make sense to you and (b) does this seem useful enough to include in the library itself.

Let me know what you think, thanks

**Comment by marshallpierce** [comment]
I think it's a quite valid problem, but I'm not sure it makes sense to try to tackle inside this library as it feels inherently pretty customized to what you're doing. Would it address your need to simply be able to record histograms on some schedule of your choosing and send them to a system that knows how to manipulate histograms (e.g. https://github.com/Searchlight/khronus)? (Note: I'm biased towards making the hdrhistogram encoded form the de facto wire format for histogram transfer and moving histogram processing to the aggregated store, whether in the metrics library or in other systems.)

**Comment by jhaber** [comment]
I think this issue is more about how you actually generate that histogram. For things like # of busy connections in a pool, # of active HTTP requests, etc. it is natural to represent them with a gauge but the resulting data isn't particularly useful. A histogram populated by polling these values at a fixed interval provides much more insightful data, but I don't see an easy way to achieve this with the existing API. I guess you could make a second metrics registry specifically for these types of gauges and register a reporter that runs at the desired interval to poll all the gauges and update the histograms in the main metrics registry, but it seems like it could be a lot easier if it was a first-class feature. We've already added this functionality to our fork though, so I'm happy to close this issue if you don't think it's a use-case you want to handle.

**Comment by cowwoc** [comment]
I'm also interested in this feature.

**Comment by jhaber** [comment]
Just wanted to chime in before this gets auto-closed that we've found this feature to be invaluable in providing better insight into the utilization of thread pools, connection pools, queues, etc.

Here's an example from one of our production services when using a standard gauge to monitor the utilization of its HTTP thread pool:
![gauge](https://i.imgur.com/8hRvYBO.png)

Because it's just capturing the instantaneous value once per minute, you're losing so much detail of what happened during that minute. Empirically, we've found that these graphs almost always look totally fine even when the service is queueing requests or otherwise unhealthy.

Here's the same thread pool monitored for the same service over the same time period when using this sort of "polling" gauge (sampled once per second) (green is median, orange is 99th): 
![histogram](https://i.imgur.com/6aPuIpI.png)

We see that there are brief spikes to near 100% utilization, and we don't have nearly as much headroom as the other graph indicated

**Comment by jhaber** [comment]
I started working on a PR for this, and realized that a lot has changed since we forked this repo and it would now be harder to implement. Our fork predates this commit which removed all the thread pools:
https://github.com/dropwizard/metrics/commit/c72830f27eabe00bfddea82d2c520e12fc8b1ec5

Since those thread pools still exist in our fork, it was relatively easy to just have this thread also poll the gauges and update their corresponding histograms. Without this, I'm not sure the best way to implement it. I guess you could have the caller supply a `ScheduledExecutorService` and put the burden on them to manage its lifecycle (since `MetricRegistry` doesn't have any sort of shutdown method anymore either).

But at that point the user might as well just create the histogram themselves and schedule a runnable to update it on an interval. So it seems like this issue doesn't really have a future. Anyone who wants this can do it themselves with something like:
```java
Histogram histogram = registry.histogram(someMetricName);
ScheduledFuture<?> future = executor.scheduleAtFixedRate(() -> {
    try {
        histogram.update(someLongOrIntegerGauge.getValue());
    } catch (Throwable t) {
        // log or something
    }
}, 1, 1, TimeUnit.SECONDS);
```
