### ISSUE TITLE
HdrHistogram reservoir

### ISSUE THREAD

**Issue by randomstatistic** [dropwizard/metrics#1024]
Anyone interested in having a conversation about this again? The idea of making this a first-class citizen came up in PR #729, but I haven't found anything since.

Looks like @marshallpierce has continued to maintain hdrhistogram-metrics-reservoir since then.

I'm mostly interested in getting access to HdrHistogram's `recordValueWithExpectedInterval`, but one thing at a time.

**Comment by marshallpierce** [comment]
I could expose that functionality on the reservoir, though you'd have to use reflection to get at the reservoir, so I'm not sure that's much of a win. Anyway, I'm curious what your use case is for the CO-corrected record functionality. It's not a common use case but it's certainly a valid one.

**Comment by randomstatistic** [comment]
I have the feeling the case is uncommon due to ignorance, rather than desire. Any histogram intended to track latency might benefit. My use case is simply that I have services that take traffic, and I want to be able to notice if there are latency issues. 

Predicting the rate could be interesting, but I think the primary thing would be to catch issues where the service stops responding, for example due to GC pauses.

**Comment by marshallpierce** [comment]
If you're on the receiving end of unpredictable traffic, you probably don't have to worry about CO, by the way, but it's hard to say without really digging into your situation. Anyway, that doesn't diminish from the real need to be able to do this. :)

**Comment by randomstatistic** [comment]
Well, traffic is predictable enough, but does change sometimes. By "tricky", I was mostly griping about rate changes driving a code change. Anyone considered tying this to a Meter?

More generally, my immediate intent with this issue was mostly just to discuss why HdrHistogram isn't the default reservoir for Metrics-Histograms. Are there cases where the current ExponentiallyDecayingReservoir is a better choice? Is it more about code compatibility? Performance? Simplicity?

**Comment by saadmufti** [comment]
Well for one thing ExponentiallyDecayingReservoir by design represent roughly the last five minutes (though it depends on active traffic to keep updating the metric). Doesn't HdrHistogram represent the lifetime of the metric? Having the metric quantiles represent just the most recent 'n' minutes would seem to be useful.

**Comment by marshallpierce** [comment]
Hence the need for the ResetOnSnapshot variant -- a side effect of a larger problem, I think. IMO everything should be reset on a regular cadence, and if you want to accumulate that locally into a "since the service cam up" view, that's ok! But it shouldn't be the default. 

EDR is the wrong choice almost always because the mathematical approximation it does is (1) only valid for normal distributions, which latency isn't, and (2) tends to mask outliers, which are the actually interesting part for latency.

**Comment by saadmufti** [comment]
Valid point, after reading around the net on this I agree with you, exponentially decaying makes too many assumptions. From something I read a couple of years ago, I belive BDFL Coda was against reset functionality, can't recall why.

**Comment by randomstatistic** [comment]
I gather it was related to doing the right thing around concurrency. Coincidentally, I also filed Issue #1021 on that subject.

**Comment by jmason** [comment]
I think EDR makes a little more sense if you are using a Reporter which doesn't write to a time-series-oriented store -- if you poll a JMX reporter, then seeing a value which represents the past N minutes is valuable.  However if you are reporting to something like Graphite, which has its own concept of a time dimension to every recorded data point, then resetting in line with that cadence makes more sense.

**Comment by marshallpierce** [comment]
True, though it's easy enough to build a "since the system came up" view on top of a "reset every x ms" view by locally buffering -- the other way is not so easy! That's why I'd prefer to have the former way: it's more flexible.

**Comment by vladimir-bukhtoyarov** [comment]
@randomstatistic please look to the rolling-metrics library. It seems to me that HdrHistogram integrated to Metrics Core as first class citizen in scope of this library.

**Comment by randomstatistic** [comment]
@vladimir-bukhtoyarov Thanks for the pointer, interesting.

So now I'm aware of two distinct hdrhistogram-as-a-metrics-reservoir implementations. This lends strength to the "it should be in core" argument, I'd think.

@saadmufti has a good point though, about metrics lifetimes and reporting. I agree that HDR doesn't feel right unless you're doing resetOnSnapshot, which classic metrics types don't assume.

**Comment by vladimir-bukhtoyarov** [comment]
> This lends strength to the "it should be in core" argument, I'd think.

If everything will be in the core, then core will be too big, or totally unusable. It is better to follow Open/Closed principle and provide ability for external developers(like me or Marshall) to extend library by custom implementations.
