### ISSUE TITLE
GraphiteReporter for commonj WorkManager

### ISSUE THREAD

**Issue by dimovelev** [dropwizard/metrics#1026]
Hi,

are you interested in an implementation of the GraphiteReporter for use in JEE environments (via commonj WorkManager)? I had to build one because we are not allowed to start our own threads in JEE applications but have to rather use the threads provided by the container. The main difference is the way that the start / stop the reporter and unfortunately in the run() method we need to manually sleep for the flush period.

Cheers,
Dimo

**Comment by marshallpierce** [comment]
You might be better off building a `ScheduledExecutorService` that runs on top of WorkManager; that way you wouldn't have to rebuild each reporter.

**Comment by dimovelev** [comment]
that is a good idea - I will look into that. In the mean time I have refactored the graphite reporter on my end so that the two main aspects are placed in separate classes - mapping metrics to graphite format (the report* methods) and the actual scheduling. This way I can reuse the report* stuff in multiple contexts (using JEE timer service, using JMX timer service, ...).
