### ISSUE TITLE
healthcheck endpoint on core service resource port

### ISSUE THREAD

**Issue by karux** [dropwizard/metrics#1027]
healthcheck is currently implemented on admin port.    can i specify /healthcheck should be a path on the standard core service resource port? 

To integrate with AWS ALB and deploy with dynamic container port registration, a single dynamic port assignment is required. 

my workaround is to create and register a separate resource class file that calls healthcheck.execute().

**Comment by jplock** [comment]
If you are using dropwizard, you can configure a simple server to host both the admin and normal resources - http://www.dropwizard.io/1.0.5/docs/manual/configuration.html#simple
