### ISSUE TITLE
Exponentially Decaying Reservoir Rescale On Fetch

### ISSUE THREAD

**Issue by saadmufti** [dropwizard/metrics#1030]
Timer and other metrics based on an exponentially decaying reservoir are great for frequently updated metrics, but sometimes a metric stops being updated for a while because traffic stops coming in, for example. It would be great in that case if the metric would gracefully degrade over time. As it is they become stuck at their last updated value until new traffic comes in forcing the metric to be rescaled.

I have take a brief look at the code, and it would seem the solution would be as simple as calling "rescaleIfNeeded" in the getSnapshot method, so that every time you try to get the reservoir's underlying distribution it would be rescaled to roughly represent the last five minutes.

Anyone know what downside if any there is in doing that? I would gladly submit a pull request if this is deemed useful, it is just a one line change but was wondering if there is something obvious I'm missing.

Thanks.

**Comment by IstvanM** [comment]
I would agree on fixing this issue, especially as the other reservoirs have this capability of cleaning up by time.

**Comment by IstvanM** [comment]
Created Pull request for this:

https://github.com/dropwizard/metrics/pull/1135

**Comment by arteam** [comment]
Fixed  via #1135
