### ISSUE TITLE
Nothing shows up in Graphite web UI

### ISSUE THREAD

**Issue by mayooran99** [dropwizard/metrics#1031]
I have setup a Graphite server and I am trying to print my Java metrics into the graphite UI. Graphite is up and running as I can see its web UI in localhost. I used the below code to redirect my metrics results to graphite console.

     `Graphite graphite = new Graphite(new InetSocketAddress("http://localhost", 80));
    GraphiteReporter reporter = GraphiteReporter.forRegistry(this.metricRegistry)
            .convertRatesTo(TimeUnit.SECONDS)
            .convertDurationsTo(TimeUnit.MILLISECONDS)
            .filter(MetricFilter.ALL)
            .build(graphite);
    reporter.start(1, TimeUnit.MINUTES);`

But nothing appears on the web UI. What am I doing wrong here? Do I need to specify any additional configuration for graphite? After installing graphite, I didn't add any configurations.Any help would be much appreciated.

**Comment by saadmufti** [comment]
usually the port on which you report metrics into the Graphite server is different from the web UI port of 80. You have to check your graphite server to see which port it is exposing for publishing metrics to.

**Comment by saadmufti** [comment]
This might help : http://graphite.readthedocs.io/en/latest/feeding-carbon.html

**Comment by mayooran99** [comment]
@saadmufti  It was the port! Thank you very much! Really appreciate that!
