### ISSUE TITLE
Can registerall with prefix in MetricRegistry be public

### ISSUE THREAD

**Issue by raghavan20** [dropwizard/metrics#1032]
I have a few MetricSets from Oracle Jvm Jmx beans (MemoryUsageGaugeSet, ..) that I want to group under prefix 'jvm' but the following method is private

```
private void registerAll(String prefix, MetricSet metrics) 
```

can this method be made public?

thanks

**Comment by ryantenney** [comment]
This isn't necessary. `MetricSet` implements `Metric`, therefore you can pass it to `register(String, Metric)`.

**Comment by raghavan20** [comment]
@ryantenney I would like to register all metrics in the metricset at one go but if I use register, I would have to iterate all metrics in MetricSet or is there another way? can you please give an example?

**Comment by raghavan20** [comment]
okay i got what you meant

```
        metricRegistry.register("jvm", new MemoryUsageGaugeSet());
        metricRegistry.register("jvm", new GarbageCollectorMetricSet());
```

it works. thanks
