### ISSUE TITLE
Maven doesn't know that the groupId changed

### ISSUE THREAD

**Issue by OrangeDog** [dropwizard/metrics#1044]
For example, I have in my project two dependencies. One uses `com.codehale.metrics:metrics-core:3.0.2` and the other `io.dropwizard.metrics:metrics-core:3.1.2`.

As it currently stands, Maven doesn't know that these are in conflict. Fragile manipulation of the classpath order is required in order to ensure the newer version is used.

There are instructions here about how to tell Maven about the change: http://maven.apache.org/guides/mini/guide-relocation.html#How_to_relocate_a_Maven_2_artifact_to_a_different_groupId

**Comment by OrangeDog** [comment]
Not stale

**Comment by OrangeDog** [comment]
bump

**Comment by joschi** [comment]
We can try making another release, but I'm not even sure anyone has access to the `com.codehale.metrics` groupId anymore. 🤔

**Comment by joschi** [comment]
@ryantenney I don't have permission to write into `com.codahale.metrics`.
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-deploy-plugin:2.7:deploy (default-deploy) on project metrics-parent: Failed to deploy artifacts: Could not transfer artifact com.codahale.metrics:metrics-parent:pom:3.0.3-20200408.064213-1 from/to sonatype-nexus-snapshots (http://oss.sonatype.org/content/repositories/snapshots): Access denied to: https://oss.sonatype.org:443/content/repositories/snapshots/com/codahale/metrics/metrics-parent/3.0.3-SNAPSHOT/metrics-parent-3.0.3-20200408.064213-1.pom -> [Help 1]
```
Since you made the last release of Metrics 3.0.x (ff7a9a5c90900a77b7e7a8d87e27827b7653d23d), could you perform a final release?

**Comment by ryantenney** [comment]
I think Coda revoked my access, as I had also looked into resolving this issue by pushing a POM with the relocation info, but never completed it....  will get back to you in the morning.

**Comment by joschi** [comment]
Given that we don't have the permissions to publish anything under the `com.codahale` group ID on Maven Central, I'm closing this issue.
