### ISSUE TITLE
Is there a way to override how the MetricRegistry forms the dotted name from the class name?

### ISSUE THREAD

**Issue by StephenGoodall** [dropwizard/metrics#1053]
Is there a way to override this behaviour?
When making a graph in Grafana, it seems like i have to add multiple metrics to cover the varying number of nodes in the names. I think if we were able to somehow override this method in MetricRegistry:

    public static String name(Class<?> klass, String... names) {
        return name(klass.getName(), names);
    }

Then we could keep the class name within 1 node, by using dashes perhaps:

    public static String name(Class<?> klass, String... names) {
        String unDotClass = klass.getName().replace(".", "-");
        return name(unDotClass, names);
    }

This would enable us to just use prefix.*.m1_rate to show all the m1_rate metrics across multiple applications. Without this we may need to add multiple metrics, eg:
```prefix.*.*.m1_rate
prefix.*.*.*.m1_rate
prefix.*.*.*.*.m1_rate
```
If we had applications that were reporting metrics from classes called foo.bar, foo.bar.bar and foo.bar.bar.bar.

Apologies for the terrible example - you can probably tell I'm not too experienced with code! Or Grafana - maybe there is something I can do in there that would mean this wasn't needed :smiley:

**Comment by arteam** [comment]
I believe there is no possibility to provide to the user the ability to override the `name(Class<?> klass, String... names)` method in `MetricRegistry`, because it's static.

Regarding your Grafana issue, is there a possibility to use regular expressions to match metric names? I think a greedy regex like `prefix.(.+).m1_rate` should be able to match all metrics with dots in the middle.

**Comment by StephenGoodall** [comment]
@arteam Thanks for the reply, I'm not sure if you can use regex when defining the metric in grafana when using a Graphite data source.
I'll have a look into that and perhaps ask on the grafana github page.
Thanks

**Comment by husseincoder** [comment]
I think its possible .. we use graphana and graphite as backend .. and most of our queries contain regex ..

**Comment by mixalturek** [comment]
What reporter do you use? For example `JmxReporter.Builder` has method `createsObjectNamesWith(ObjectNameFactory onFactory)` that allows you to modify the metric names according to logic defined in your code.

**Comment by StephenGoodall** [comment]
@mixalturek We are using a Graphite Reporter with Pickled Graphite:
com.codahale.metrics.graphite.GraphiteReporter
com.codahale.metrics.graphite.PickledGraphite

It's been a while since I looked at this so the above might not be what you meant! We've been getting round this by just having multiple lines with lots of *.*.*.*.* in the middle of them....not ideal but we can at least see the metrics this way :)
