### ISSUE TITLE
change io.dropwizard.metrics.ObjectNameFactory to throw exception

### ISSUE THREAD

**Issue by rconn01** [dropwizard/metrics#1065]
While breaking changes can still be made on the 4.x branch, would it make sense to change the signature of `io.dropwizard.metrics.ObjectNameFactory#createName` to throw a `MalformedObjectNameException`. This way implementations can throw that exception if they can't generate an object name. This would ultimately bubble up to the listener methods, such as `onCounterAdded` where a `JMException` is caught and logged. 

As the code stands now there is no way for an `ObjectNameFactory` to give up. The best option would be to throw a RuntimeException, which could break application flow.

I'm willing to propose a change but wanted to get some feedback first

**Comment by arteam** [comment]
I think it's a good idea. I would accept a pull request for the 4.x branch.

**Comment by ryantenney** [comment]
Tracking in #1076
