### ISSUE TITLE
Change groupId on 4.x

### ISSUE THREAD

**Issue by rconn01** [dropwizard/metrics#1069]
Are there any plans to change the maven `groupId` on the current master (4.x) branch. Since it shares the same groupId `io.dropwizard.metrics` with the 3.1.x branch there is no way for the two versions of the code to live in the same code base. All of the java code looks like it was repackaged from `com.codahale.*` to `io.dropwizard.*` which is good so the classes of the two versions can live side by side. But there is no way to pull in the two artifacts with the same group

**Comment by arteam** [comment]
I also think this a good idea. Maybe we can switch to the `io.dropwizard.metrics4` group.

**Comment by ryantenney** [comment]
I agree that the groupId change to version 3.1 was unfortunate, however I'm not concerned about this. We created the [`metrics-adapter`](https://github.com/dropwizard/metrics/tree/master/metrics-adapter) module which will wrap metrics 4 and is bytecode compatible with versions 3.1 and 3.2. In addition to practical concerns about ensuring the I'm generally opposed to versioning in the groupId or package name, but if we could go back and do the groupId change over again, perhaps I would have chosen `io.dropwizard.metrics3`, leaving `io.dropwizard.metrics` free for version 4.

**Comment by rconn01** [comment]
I didn't realize the [metric-adapter](https://github.com/dropwizard/metrics/tree/master/metrics-adapter_ module existsed. Looking at this however it looks like it only provides binary compatiability for most of `metrics-core` ,but it doesn't provided compatiability for the other modules. How do invision a project to make the upgrade to 4.x when some of its dependencies still make use of some of the 3.x modules that are packaged under `com.codahale.*`. So something like the `http-client` module for example

**Comment by ryantenney** [comment]
Ah okay, that didn't occur to me.

**Comment by rconn01** [comment]
So is the consensus the groupId should change. If so what should it change to.
`io.dropwizard.metrics4` or are there other ideas

**Comment by ryantenney** [comment]
I guess we have to.
