### ISSUE TITLE
GraphiteReporter public reportMetric methods

### ISSUE THREAD

**Issue by maksim-kosolapov** [dropwizard/metrics#1070]
I think it's good idea to add public method GraphiteReporter.reportGauge(String name, Gauge gauge). This provides possibility to send not periodical metrics to graphite in custom time moment. 

```java
public void reportGauge(String name, Gauge gauge){
  SortedMap emptyMap = new TreeMap<>();
  SortedMap<String, Gauge> map= new TreeMap<>();
  map.put(name, gauge);
  reporter.report(map, emptyMap, emptyMap, emptyMap, emptyMap);
}
```

**Comment by arteam** [comment]
My biggest concern with the proposed change is that caller must manually manage the `GraphiteSender` object in the reporter before sending metrics (open a connection, flush the output, close the connection).
I's not obvious and may lead to a confusion. I think every public method of a reporter should not require the caller to know its internal details.
