### ISSUE TITLE
Document CpuProfileServlet and how to parse its output

### ISSUE THREAD

**Issue by arteam** [dropwizard/metrics#1081]
#929 had added support for CPU profiling to `AdminServlet`. Unfortunately, it's not really clear how to use it. The servlet produces some binary output which should be loaded to an external tool. We need to:

* Add a link to https://github.com/papertrail/profiler
* Add a link to https://github.com/gperftools/gperftools
* Document how to install `google-pprof` on a dev machine 
* Document how generate a human readable report, e.g.
```
curl http://127.0.0.1:8081/pprof > cpu_profile
google-pprof --pdf cpu_profile > report.pdf
```

**Comment by ARentz07** [comment]
Just had to do this today, and found it pretty easy to install gperftools on the Mac, just following their readme. Maybe just link to it somewhere? https://github.com/gperftools/gperftools
