### ISSUE TITLE
documentation for creating hierarchical jmx entries?

### ISSUE THREAD

**Issue by mebigfatguy** [dropwizard/metrics#1082]
Hi folks,

perhaps i missed something obvious, but am trying to build hierarchical folders with metrics-core similar to what you would do like
    new ObjectName("foo.com:00=folder,01=subFolder,name=SomeBean");

if someone could point me in the right direction, would be appreciated.

**Comment by ryanrupp** [comment]
I'm not sure if there's documentation on this but for Metrics 3.x where the metric name is just a dot delimited string by default the JMX view won't have any hierarchy represented in the ObjectName (flat list domain + name). However, the ObjectNameFactory is pluggable on the JmxReporter [here](https://github.com/dropwizard/metrics/blob/4f96bb201230e139acf422b9a0135ad0fd6d83f8/metrics-core/src/main/java/com/codahale/metrics/JmxReporter.java#L39) so you could add a custom reporter that splits up the name and tries to introduce a hierarchy based on that using just autogenerated keys somewhat like you have there e.g.:

"my.metric.name" --> "L1=my,L2=metric,L3=name"

I'm not sure how this will end up working in Metrics 4.x but the naming pattern has a name + key/value pairs (tags) - can see this on master.

**Comment by mebigfatguy** [comment]
ah nice, thanks.

**Comment by ryanrupp** [comment]
Yeah I think technically the key/value pairs in the ObjectName by the JMX spec say they're unordered it's just tools like VisualVM/JConsole respect their order to build out a hierarchy view. Also some other quirks like if you have a key called "type" VisualVM MBean view will always put that at the top of the hierarchy, guessing you just auto generated the "key" names though like the L1,L2 etc. example. The downside of this is while you get a nice hierarchy view in these tools your consuming client will need to know the naming scheme you used e.g. take the metric "name" and inject the "L{n}" key for each key/value in the hierarchy. Personally I've found JMX nice for realtime/casual browsing but preferred the pushed base reporting (Graphite, console etc.) for collecting the metrics externally. JMX is nice though in that it's a standard so a decent amount of tools will support it.
