### ISSUE TITLE
getCount() of com.codahale.metrics.JmxReporter$JmxHistogram is not correct?

### ISSUE THREAD

**Issue by kristoheero** [dropwizard/metrics#1083]
Hi! I'm using  Dropwizard metrics-core 3.1.0 and the method _getCount()_ of the class _com.codahale.metrics.JmxReporter$JmxHistogram_ seems to be incorrect:

```
@Override
public long getCount() {
    return metric.getCount();
}
```

It should be return the metrics _Shapshot_ size not the total count in the metrics object?

```
@Override
public long getCount() {
    return (long) metric.getSnapshot().size();
}
```

**Comment by arteam** [comment]
I guess it depends how you interpret it. I think most of users don't care about the number values in the snapshot, but rather about the number of recorded values. E.g. we know we wrote 10000 events, it doesn't matter much with which approach we calculated percentiles (sliding time window or .exponentially-decaying random sampling).

**Comment by kristoheero** [comment]
OK! We are then not the most! :-) But, can you add an extra method to _com.codahale.metrics.JmxReporter$JmxHistogram_ class for asking _metric.getSnapshot().size()_?

**Comment by arteam** [comment]
I think that's doable. Should be an easy improvement.

**Comment by kristoheero** [comment]
Thanks!
