### ISSUE TITLE
Might be wise to upgrade the Maven release plugin

### ISSUE THREAD

**Issue by mrmanc** [dropwizard/metrics#1087]
Had a problem in a fork of this project where the release plugin was creating tags containing poms with the wrong (old, not bumped) version in them, leading to releasing the old SNAPSHOT rather than the new release. Managed to resolve this by upgrading to `2.5.3`. The problem seemed very much like [this one](http://stackoverflow.com/questions/16650698/maven-release-plugin-prepare-creates-tag-of-snapshot-version-instead-of-releas). It’s probably a combination of my Maven version (`3.1.1`), Git version (`2.9.1`) and the plugin version (`2.4.1`).

**Comment by arteam** [comment]
Accidentally, I did just that today during releasing 3.2.0 and 3.1.3! See https://github.com/dropwizard/metrics/commit/817782b8a6eed91ff23e15d447dc8ed322c0e393

**Comment by erebe** [comment]
By the way do you plan to release the 3.2 on maven soon ?

**Comment by arteam** [comment]
I've released 3.2.0 and 3.1.3 to the Maven Central today. They should be available in a couple of hours as soon as the Central replica servers will be synchronized with the origin.

**Comment by erebe** [comment]
What can I say if not thanks :+1:

**Comment by mrmanc** [comment]
Wow, what are the chances! Good work… I guess it wasted a few hours of your time too… 😆 Also, great to see a new release out. It’s inspired me to finally submit a [PR](https://github.com/dropwizard/metrics/pull/1091)!
