### ISSUE TITLE
Metrics library - Changing metrics very small exponential number E-109 values to 0

### ISSUE THREAD

**Issue by kamalvpm777** [dropwizard/metrics#1106]
Hello,
we are using metrics library to pull the metrics from springboot apps. On pushing the metrics to AWS cloudwatch  and whenever there is a small value found in metrics value like 
(4.784335455263847E-109)  cloudwatch rejects those values and breaks completely updating the other positive (>0) metrics too.

After spoke with AWS cloudwatch we found that these very smaller values (E-169) need to be converted to 0 before sending the same metrics to cloudwatch. Could we get some approach how to to modify these smaller values as 0 which is a solution that we are looking ?

# Actual Behaviour:
com.sam.work.rest.controller.ServiceControllerV1.getData.oneMinuteRate:2.721723306412017E-169

2017-03-11T07:56:42Z E! Error writing to output [cloudwatch]: InvalidParameterValue: The value 0 for parameter MetricData.member.10.Value is invalid.
The value 0 for parameter MetricData.member.12.Value is invalid.

# Desired Behaviour to resolve this issue:
com.sam.work.rest.controller.ServiceControllerV1.getData.oneMinuteRate:0

2017-03-14T22:15:51Z D! Output [cloudwatch] wrote batch of 74 metrics in 11.133616242s

Please refer the below link as explained by AWS rejecting those metrics lesser than E-109
http://docs.aws.amazon.com/AmazonCloudWatch/latest/APIReference/API_PutMetricData.html

**Comment by arteam** [comment]
Hello. I guess this depends how you actually report data to CloudWatch. Do you use a third-party reporter, parse a some servlet output or read out a `MetricsRegistry` manually? The best way I think is write some decorator where you can perform any needed conversion. For instance, `GraphiteReporter` converts measurements to 2 digits after the point.  See [here](https://github.com/dropwizard/metrics/blob/3.2-development/metrics-graphite/src/main/java/com/codahale/metrics/graphite/GraphiteReporter.java#L349).

**Comment by kamalvpm777** [comment]
I forgot to mention that we use Telegraf to pull the HTTP JSON metrics and write it to cloudwatch.

In our case telegraf not able to convert the measurements , which is the bug confirmed by telegraf. So here is what recommened by telegraf team as a quick workaround. So looking for some guidance on what needs to be implemented on server to adjust the values to 0  before they enter in telegraf?

Recommendations from Telegraf:
"Update the server that your httpjson input uses as its source to adjust the values before they enter telegraf. We will try to get a fix done for this before the next release"

[[inputs.httpjson]]
servers = [
"http://localhost:2960/metrics"
]

**Comment by arteam** [comment]
I believe you use `MetricsServlet` which outputs metrics in the JSON format via HTTP. The actual JSON conversion is handled by Jackson in `MetricsModule`. Unfortunately, it can't be customized. The simplest option as I see is too copy-paste `MetricsServlet` and `MetricsModule` and make needed adjustments. Another option is too contribute to the original module the ability to configure a threshold for measurements.

**Comment by abhi-jha** [comment]
Hey, was there any progress on this?

**Comment by joschi** [comment]
@abhi-jha This has to be fixed in your metrics reporter or in the monitoring system you're using.
