### ISSUE TITLE
PickledGraphite.isConnected() can't detect right socket status when the carbon daemon is shutdown?

### ISSUE THREAD

**Issue by elloooooo** [dropwizard/metrics#1123]
> @Override
    public boolean isConnected() {
        return socket != null && socket.isConnected() && !socket.isClosed();
    }

This method will return true even the carbon daemon is shutdown. It leads the situation that the graphite reporter can't reconnect to the carbon when carbon need to be restart.

**Comment by arteam** [comment]
I believe it should be fixed in 3.2.1 and 3.1.4. The Graphite reporter should reconnect to a server any time it sends new data. This is achieved by closing the TCP connection after each sending.

**Comment by elloooooo** [comment]
Thank you for your reply. Could you show me the PR?

**Comment by arteam** [comment]
#1936 and #1047

**Comment by elloooooo** [comment]
It sovles my problem. I encounter this problem in the graphite-emitter extension base on this project for Druid. It used some method in PickledGraphite.class but not the GraphiteReporter directly. So I will fix the bug in graphite-emitter as the way you do in GraphiteReporter.
Thank you.
