### ISSUE TITLE
JmxReporter with complex Gauge

### ISSUE THREAD

**Issue by longtimeago** [dropwizard/metrics#1127]
I'm trying to achieve the following visible structure of jmx beans (to met company standards):
```
- com.my_company
----- AppClient 
---------- Attributes
-------------- attribute1
-------------- attribute2
-------------- attribute3
```
I've tried to use Gauge with complex type, like:
```java
class AppClient {
    Boolean attribute1;
    String attribute2;
    String attribute2;
}
```
But it seems like this approach is not supported.
Is there any way to achieve bean structure mentioned above?

**Comment by longtimeago** [comment]
As far as I understand, single `Gauge` is mapped to a single MBean (with default attribute name `Value`).
But what I would like to have is a way to map a `Gauge` to mbean attribute, so I would have several attributes in the same mbean

**Comment by DmitriyO** [comment]
Hi @longtimeago , have you resolved this somehow?

**Comment by longtimeago** [comment]
@DmitriyO hey :) Nah, we've stopped using jmx as a transport for metrics in favor of https://github.com/prometheus/client_java.
JMX appears to be not suitable when using container orchestrator solutions like Kube
