### ISSUE TITLE
is influxDB supported?

### ISSUE THREAD

**Issue by rony13** [dropwizard/metrics#1130]
https://github.com/influxdata/influxdb, ATT

**Comment by osigida** [comment]
see http://metrics.dropwizard.io/3.2.2/manual/third-party.html
`metrics-influxdb provides a reporter which announces measurements to InfluxDB`

**Comment by rony13** [comment]
thanks , BTW,  in my project, i may need to record thousands of different keys, if i use metrics, i need to create as much Metric Object as keys. While by useing statsd, i only need to Initialize a StatsDCLient.

**Comment by darrenfu** [comment]
Does the [third party library](https://github.com/davidB/metrics-influxdb) above support influxdb v1.3 as well? Looks like it only supports v0.13.

**Comment by arteam** [comment]
We probably need to update the page. https://github.com/iZettle/dropwizard-metrics-influxdb and https://github.com/kickstarter/dropwizard-influxdb-reporter are more active and relevant InlfuxDB reporters.
