### ISSUE TITLE
Drop-in replacement of sliding time window reservoir

### ISSUE THREAD

**Issue by storozhukBM** [dropwizard/metrics#1138]
Hi @arteam,
I'm currently working on PR that will provide drop-in replacement of `SlidingTimeWindowReservoir`. It provides **2.5x faster** writes, **3.5x faster** snapshots much lower memory footprint. And most importantly it has radically lower garbage emissions, that gives **40x lower GC pauses**.
All this work was based on **3.2-development** branch and is fully compatible with its **1.6** target.
Now, when you created **4.0-development** branch, would you suggest me to migrate all code to **1.8** target, or maybe I can create PR for **3.2** branch and then port to **4.0**?

**Comment by storozhukBM** [comment]
Closed by accident, sorry.
cc: @arteam

**Comment by arteam** [comment]
If your solution is compatible with Java 6, you can submit a pull request against the 3.2 branch. If it works, I will make another 3.2.* release and just rebase the 4.0 branch against 3.2. 4.0 doesn't contain any new features, just changes of the build and dependencies.

**Comment by storozhukBM** [comment]
👍 I'm almost finished with it. Will make PR next week.
Here is small sneak peek of profiling results on the same load pattern:
<img width="1409" alt="comparison" src="https://user-images.githubusercontent.com/3532750/26981648-76acd1dc-4d3e-11e7-90af-848e674df9b7.png">

**Comment by storozhukBM** [comment]
Merged. Closing issue.
