### ISSUE TITLE
Metrics CSV inconsistent behavior 

### ISSUE THREAD

**Issue by aljohnso** [dropwizard/metrics#1149]
I am encountering difficulty running a CsvReporter in my JUnit tests, I run into the issue that the reporter does not create any csv files.
```java			
CsvReporter reporter = CsvReporter.forRegistry(metricRegistry)
					.formatFor(Locale.US)
					.convertRatesTo(TimeUnit.SECONDS)
					.convertDurationsTo(TimeUnit.MILLISECONDS)
					.build(new File("C:\\Users\\ajohnson\\"));
```
I have been trying this as well on a Linux vm and it has worked about 50% of the time I am starting it in Junits @beforeClass decorator and stopping it in the @afterClass decorator, one thought I considered for this issue was if it could be because of the need for object to be static in the above tags.

my main question is this given the lack of consistency with this are there some debugging steps I can take or am I simply using this tool in a way its not supposed to be

**Comment by arteam** [comment]
Could you share your unit test? Do you call the `report` method on the reporter explicitly?

**Comment by aljohnso** [comment]
appears to have been a permissions issue
