### ISSUE TITLE
Multiple @ExceptionMetered annotations on the same method?

### ISSUE THREAD

**Issue by dougbacelar** [dropwizard/metrics#1153]
I have a controller that can throw two different exceptions.

**Groovy code:**

    ResponseEntity<Response> testController(@RequestParam(value = 'test', required = true) String test) throws Exception {

        if(validationError()){
            throw new ValidationException ('failed to validate request')
        }
        //more code
        if(resourceNotFound()){
            throw new ResourceNotFoundException('could not find any results for the given parameter')
        }
    }

I want to keep metrics for both of these exceptions separately. As one is a `ValidationException` and the other a `ResourceNotFoundException`, there would not be much point to let the annotation group them together...

I am able to store one of them with the following code:
`@ExceptionMetered(name = "ResourceNotFoundException", absolute = true, cause = ResourceNotFoundException)`

However if I try to add another  `@ExceptionMetered` annotation to the same method I get an error as the annotation is not Repeatable.

I also tried to create a new method that will throw the validation exception and annotate this new method with the `@ExceptionMetered` instead. 

However this does not work either, the first exception is recorded fine but the second is always 0, doesn't matter how many times I trigger it.

**Question: How to keep track of multiple exceptions separately? Is this just not possible?**

Thank you!

**Comment by ryanrupp** [comment]
Can you clarify if you're using the [metrics-spring](https://github.com/ryantenney/metrics-spring) library? I'm guessing you are based on the use of ReponseEntity/RequestParam - this main metrics repository only has interceptors for Jersey. As for the repeatable annotation, that isn't supported as Metrics 3.x is Java 6 based and repeatable annotations were introduced in Java 8.

As for making this work by separating the exception throwing into seperate methods this will most likely not work for Spring Metrics as Spring AoP will not be able to intercept method calls you're making from within the the class itself (see disclaimer in Spring Metrics readme "A Note on the Limitations of Spring AOP" - it mentions only public/externally called methods can be intercepted although I think in some cases protected methods can be intercepted too see [here](https://jira.spring.io/browse/SPR-15354)). Technically, you can use AspectJ with Spring to intercept private methods although not sure that works with metrics-spring. As a hack you could delegate the actual throwing of the exception to another class and mark those methods but would be pretty hacky.

Short term I think you would just have to do the meter marking programmatically. Longer term maybe support for repeatable annotations for ExceptionMetered can be added (and the intercepting libraries updated to support this) in metrics 4 (which uses Java 8).

**Comment by dougbacelar** [comment]
**Can you clarify if you're using the metrics-spring library?**
Yes, I am using the following library: https://github.com/ryantenney/metrics-spring

**As a hack you could delegate the actual throwing of the exception to another class**
I did something similar to get around this. I created an exception handler class for the application, which is responsible for intercepting all exceptions and handling them accordingly. 

I have one public method for each exception in the handler class, so I could annotate those with `@Metered`. Now all exceptions are being recorded!

Thank you so much for your detailed response, I now understand the problem much better.

**Comment by ryanrupp** [comment]
That works! I wasn't sure if you needed the exception counts to be sliced by the controller that caused them or not.

**Comment by dougbacelar** [comment]
I won't need that for the time being. In the future I intend to create different exceptions for each controller so that won't be a problem :)

Thank you so much for your help!

**Comment by ojharavi-fk** [comment]
@dougbacelar Were you successfully able to track multiple exceptions separately? I'm trying to solve the exact same problem. I created a public class called `ExceptionHandler` which contains public static methods to throw the exception. I have annotated those methods with `@ExceptionMetered` and then call them as `ExceptionHandler.throwResourceNotFoundException()` from the API method, however, I don't see the data logged by `ConsoleReporter`. Am I missing anything? 

Would be very helpful if you shared a gist of the exception handler class. 

PS: A Python guy moving to Java stack, please excuse any stupidity :)

**Comment by ravi-ojha** [comment]
@dougbacelar Were you successfully able to track multiple exceptions separately? I'm trying to solve the exact same problem. I created a public class called `ExceptionHandler` which contains public static methods to throw the exception. I have annotated those methods with `@ExceptionMetered` and then call them as `ExceptionHandler.throwResourceNotFoundException()` from the API method, however, I don't see the data logged by `ConsoleReporter`. Am I missing anything? 

Would be very helpful if you shared a gist of the exception handler class. 

PS: A Python guy moving to Java stack, please excuse any stupidity :)

**Comment by dougbacelar** [comment]
@ravi-ojha 

I use an `ExceptionHandler` class to handle the exceptions (not throw them). 

I throw the exceptions inside my services and the `ExceptionHandler` catches those exceptions.

If you can use that approach, you can simply annotate the methods in the `ExceptionHandler` class with the `@Metered` annotation to gather metrics from different exceptions.

I created [this repository](https://github.com/dougbacelar/dropwizard-issue1153) as an example of the above. I hope this helps you  😄

**Comment by ravi-ojha** [comment]
Thank you @dougbacelar! The demo repo is very helpful. ^_^
