### ISSUE TITLE
metrics-core is not compact2 profile compatible

### ISSUE THREAD

**Issue by ViToni** [dropwizard/metrics#1155]
I would love to use metrics-core on a constrained system. For this system there is only a compact2 profile available. As metrics-core contains also JMX stuff that's not possible.

For compact profiles see: [Java SE 8 Embedded Compact Profiles Overview](http://www.oracle.com/technetwork/java/embedded/resources/tech/compact-profiles-overview-2157132.html)

It would be great if the JMX part could be an artifact on its own.

What do you think?

**Comment by arteam** [comment]
Yes, I think this is a good idea for the 4.0 version which will target Java 8. I will try to extract a `metrics-jmx` module.

**Comment by ViToni** [comment]
Sounds great! 

Do you have a planned timeline for 4.0?

**Comment by arteam** [comment]
I don't have any specific date, but I think I could cut a beta release in a couple of weeks, if nothing big comes up. The current code in the 4.0-development branch, you can try it out if you want.

**Comment by ViToni** [comment]
The changes for 4.0 look great. It seems though one class slipped through:
`Clock` has class `CpuTimeClock` which uses JMX to get its information.

**Comment by arteam** [comment]
Thank you for pointing this out! I moved it to the `metrics-jvm` module. Could you please check the new snapshot of 4.0? I spend some time adapting 4.0 for Java 8 and think I can cut an alpha version soon.

**Comment by ViToni** [comment]
I am looking forward to test the alpha version. 
Regarding compact2, it looks good:

	/z/git/metrics/metrics-core/target (4.0-development)
	$ jdeps.exe -P metrics-core-4.0.0-SNAPSHOT.jar
	metrics-core-4.0.0-SNAPSHOT.jar -> not found
	metrics-core-4.0.0-SNAPSHOT.jar -> C:\Program Files\Java\jdk1.8.0_131\jre\lib\rt.jar (compact1)
	   com.codahale.metrics (metrics-core-4.0.0-SNAPSHOT.jar)
		  -> java.io                                            compact1
		  -> java.lang                                          compact1
		  -> java.lang.invoke                                   compact1
		  -> java.lang.ref                                      compact1
		  -> java.nio.charset                                   compact1
		  -> java.text                                          compact1
		  -> java.util                                          compact1
		  -> java.util.concurrent                               compact1
		  -> java.util.concurrent.atomic                        compact1
		  -> java.util.concurrent.locks                         compact1
		  -> java.util.function                                 compact1
		  -> org.slf4j                                          not found
