### ISSUE TITLE
Release notes mistake

### ISSUE THREAD

**Issue by storozhukBM** [dropwizard/metrics#1156]
In 3.2.3 version:
`ChunkedAssociativeLongArray` should be replaced with `SlidingTimeWindowArrayReservoir`.
`ChunkedAssociativeLongArray` is only storage.

**Comment by arteam** [comment]
Thank you for pointing this out! I've updated the release notes on Github.

PS. I will push new documentation to http://metrics.dropwizard.io shortly, unfortunately it's a manual process which requires coordination between Sphinx, Maven and git.

**Comment by storozhukBM** [comment]
Thank you @arteam.

**Comment by arteam** [comment]
The website has been updated. 

* http://metrics.dropwizard.io/3.2.3/manual/core.html#sliding-time-window-reservoirs
* file:///home/artem/Programs/metrics/docs/target/site/about/release-notes.html#v3-2-2-mar-20-2017
