### ISSUE TITLE
Timer - batch processing

### ISSUE THREAD

**Issue by kushal256** [dropwizard/metrics#1159]
Is there a way to use the Timer class for batch processing?  For example, I'm timing sending off a batch of X requests to an external service, and when I get back results for them, call Timer.Context.stop(), which eventually calls Meter::mark(1).  But really I want it to call Meter::mark(X), so is it possible to have a Timer.Context.stop(X) which would do this?

Or is there another recommendation for dealing with batch processing?  If so please advise.

**Comment by ryanrupp** [comment]
Not out of the box no but you can use the metrics as primitives to build out what you want e.g. create a new `BatchTimer` class (which encompasses a Metrics Timer and Meter) that allows you to do a start/stop call where you pass in the count.

**Comment by kushal256** [comment]
OK will make my own, but think it would be great to see this built into the Timer class.

Thanks.
