### ISSUE TITLE
The current javdoc link on the home page is broken.

### ISSUE THREAD

**Issue by StuAtGit** [dropwizard/metrics#1160]
Not sure where the best place to report this is, but, in the user manual:
http://metrics.dropwizard.io/3.2.3/manual/index.html

There's a link to:
http://metrics.dropwizard.io/3.2.3/apidocs/

Which currently returns 404.

**Comment by leizhiyuan** [comment]
@StuAtGit  It seems 3.2.3 don't exsit.

but 3.2.2 can be visited
http://metrics.dropwizard.io/3.2.2/apidocs/
