### ISSUE TITLE
Metrics generated from e.g. @Timed or @ExceptionMetered have inconvenient names

### ISSUE THREAD

**Issue by tobilarscheid** [dropwizard/metrics#1165]
I am trying to gather Metrics from all my REST-Service interfaces.

In order to do so, I usually annotate `@Timed` and `@ExceptionMetered` on class level. This then generates a number of prometheus metrics with names like the following: `com_example_myapp_myclass_method1_count`, `com_example_myapp_myclass_method2_count`, `com_example_myapp_myclass_method3_count` and so on.

I find that rather inconvenient when then reusing the metrics with the prometheus exporter - my understanding of good metric naming would be to have one `count` metric (propably prefixed with something like `com_codahale_metrics`) and then distinguish the separate metrics by using labels - essentially the way everyone (including @juliusv and @brian-brazil) [recommends it](https://github.com/prometheus/prometheus/issues/2671).

**Comment by ryanrupp** [comment]
I think you're referring to tags e.g.:

count;method=foo_bar_baz,some_other_tag=tag_value

This naming style is used in relatively newer timeseries databases such as InfluxDB, OpenTSDB and I think Prometheus (not that familiar with it). Metrics in its current state follows just String based naming or dot delimited similar to what is used in older timeseries database such as Graphite. On `master` tags were actually introduced via a `MetricName` [here](https://github.com/dropwizard/metrics/blob/master/metrics-core/src/main/java/io/dropwizard/metrics/MetricName.java#L52) although I'm not sure this is going into 4.0 anymore (it would massively break the API at least). Related pull request https://github.com/dropwizard/metrics/pull/561 with more context.

**Comment by tobilarscheid** [comment]
Thanks for your detailed feedback! I am glad to see that this is worked on.
Do you guys see no way of introducing that into 4.0 backwards compatible, for example by using a configuration switch to stay with the old behaviour? And where is the introduction of this feature tracked? The PR you referenced is closed!
