### ISSUE TITLE
BOM for metrics?

### ISSUE THREAD

**Issue by victornoel** [dropwizard/metrics#1169]
I noticed there is no bom for metric artefacts, it could be nice to have one.

For example latest dropwizard uses metrics 3.2.2 and 3.2.3 was released: if I want to use latest version I have to add lots of dependency management just to force the version…

**Comment by arteam** [comment]
I think that's a good idea, thanks for suggesting it. I recently started to
extracting all metrics dependencies in one place in 4.0,  so I think I can
take a spin on the BOM artefact as well.

That's also a good reminder to upgrade Dropwizard's dependency on metrics.
