### ISSUE TITLE
mean metric of Timer returns Double.NaN in some cases

### ISSUE THREAD

**Issue by altery** [dropwizard/metrics#1173]
There is a bug in WeightedSnapshot/ExponentiallyDecayingReservoir that causes the mean to return a value of NaN instead of 0.0 in some cases. The error occurs, if there are only 0.0 weights in the snapshot (ie. very old samples) while calculating the normWeights in WeightedSnapshot. I created a small example, that reproduces the problem: https://gist.github.com/altery/0efd06c4f8d0c83a44bd718e8170a49e

**Comment by estekhin** [comment]
Seems related to #1005 which was fixed in  3.1.3, but I am getting a lot of timer.mean=NaN with 3.2.3 version.

**Comment by altery** [comment]
Forgot to mention it: The problem occurs with 3.2.3.

**Comment by philmtd** [comment]
Looks to me like #1135 let this issue appear.

I added #1230 to fix this.

**Comment by arteam** [comment]
Closed via #1230
