### ISSUE TITLE
CsvReporter should set separator in dependence of locale-dependent decimal separator

### ISSUE THREAD

**Issue by siom79** [dropwizard/metrics#1174]
Using the CsvReporter for example with a German locale, results in a CSV file that uses the comma as separator between the columns but additionally also as decimal separator:
```
1502448484,100,1,081546,0,610664,0,441010,0,097851,0,596013,0,643630,0,794799,0,971580,1,080447,1,081546,11,095617,0,090692,24,310302,69,889724,calls/minute,milliseconds
```
In the line above it is not clear where each column starts.

As the JDK class [DecimalFormatSymbols](http://docs.oracle.com/javase/6/docs/api/java/text/DecimalFormatSymbols.html) provides the decimal separator derived from the given locale, it should be possible to use a different char for the column separator. 

In general it would be useful to be able to provide the separator char for columns as parameter to the CsvReporter builder.

**Comment by ryanrupp** [comment]
Alternatively or additionally, double quote values that can potentially contain a comma. Can be fancy and just check the decimal formatter output on startup to see if it's going to generate comma producing values e.g. US locale wouldn't need double quote ever.
