### ISSUE TITLE
Error in documentation

### ISSUE THREAD

**Issue by shreejay** [dropwizard/metrics#1177]
In the [getting-started page](http://metrics.dropwizard.io/3.2.3/getting-started.html) `/metrics/docs/source/getting-started.rst `

The `mainClass `in the mvn command is incorrect. 
`mvn package exec:java -Dexec.mainClass=sample.First`

It should be 
`mvn package exec:java -Dexec.mainClass=sample.GetStarted`

**Comment by mveitas** [comment]
@shreejay Please feel free to open a pull request to get this fixed!
