### ISSUE TITLE
which latest version of io.dropwizard.metrics is compatible with java 7

### ISSUE THREAD

**Issue by shashank-devisetty** [dropwizard/metrics#1190]
i'm using metrics in my application running on java 7. Need to know the version so that i could add the dependency in my pom.xml

**Comment by arteam** [comment]
The 3.2.* releases are Java6-compatible. 4.0.* releases will target Java8.

**Comment by shashank-devisetty** [comment]
So,
`<dependency>
      <groupId>com.palominolabs.metrics</groupId>
      <artifactId>metrics-guice</artifactId>
      <version>3.2.2</version>
      <scope>compile</scope>
    </dependency>
    <dependency>
      <groupId>io.dropwizard.metrics</groupId>
      <artifactId>metrics-servlets</artifactId>
      <version>3.2.3</version>
      <scope>compile</scope>
    </dependency>`
this is fine for Java 7 right

**Comment by arteam** [comment]
Yes, Metrics 3.2.3 should be compatible with Java 7.
