### ISSUE TITLE
Setup Checkstyle

### ISSUE THREAD

**Issue by mveitas** [dropwizard/metrics#1198]
Copy the checkstyle [config](https://github.com/dropwizard/dropwizard/blob/master/checkstyle.xml) from the parent Dropwizard project and set up an integration with [Code Climate](https://codeclimate.com/github/dropwizard/dropwizard) to detect such issues automatically during a pull request

**Comment by mveitas** [comment]
It probably makes sense to look to create a common configuration file that all of the dropwizard organization projects can use

**Comment by arteam** [comment]
Checkstyle has been configured and you can browse issues in CodeClimate or locally with the maven-checkstyle plugin.
