### ISSUE TITLE
Automatically add listeners when register child registry

### ISSUE THREAD

**Issue by LMnet** [dropwizard/metrics#1214]
Statement from the docs:
> Generally you only need one MetricRegistry instance per application, although **you may choose to use more if you want to organize your metrics in particular reporting groups.**

I'm using the second approach: I have one base (parent) `MetricRegistry` and some child registries. Child registries may have metrics or dynamic metrics.
When I register child metric registries inside parent registry I'm expecting to register all static and dynamic metrics inside parent registry. But at the current moment only static metrics registered:

```java
class Child extends MetricRegistry {
  public void cnt(i: Int) { // dynamic metric
    counter("test-" +i).inc()
  } 
}

MetricRegistry parent = new MetricRegistry
MetricRegistry child = new Child

child.cnt(1)
parent.register("child", child)
child.cnt(2)
```
Expected result:

In child | In parent
------------ | ---------
test-1 -> 1 | child.test-1 -> 1
test-2 -> 1 | child.test-2 -> 1

Actual result:

In child | In parent
------------ | ---------
test-1 -> 1 | child.test-1 -> 1
test-2 -> 1 | 

Of course, I can manually add listeners and register all newly created child metrics in the parent. But I think it should be done automatically.

**Comment by arteam** [comment]
Closed via #1393
