### ISSUE TITLE
Contribution Guidelines

### ISSUE THREAD

**Issue by zharvey-welltok** [dropwizard/metrics#1218]
I'm interested in contributing to this project (DW metrics, not DW core). Where can I find documentation on:

1. Building locally, especially w.r.t. tool setup (Code Climate, etc.)
2. Proper process to follow (do I fork and then put in a PR against my forked version, etc.)?
3. Code conventions/styling, etc.?

**Comment by arteam** [comment]
Hi! Sorry, we don't have a contribution document, but maybe it makes sense to add one. Answering your questions:

* For local development your only need Maven. CodeClimate is run only on the server side when submitting a pull request. If you have errors reported by CodeClimate you can verify them locally with the checkstyle plugin by running `mvn checkstyle:check`

* Yes, we follow the standard GitHub flow: https://guides.github.com/introduction/flow/
* We use `checkstyle` for detecting code style issues, but generally we stick to the Google Java Style Guide: https://google.github.io/styleguide/javaguide.html

**Comment by bitbythecron** [comment]
Thanks @arteam ! Final question (should have asked it originally): if I want to propose a new feature/enhancement, do I just submit the PR or should I get approval for it first (here? Google Groups? etc.). Thanks again!

**Comment by arteam** [comment]
> if I want to propose a new feature/enhancement, do I just submit the PR or should I get approval for it first (here? Google Groups? etc.).
You can just submit a PR is the work is done or create a new issue if you have a proposal.
