### ISSUE TITLE
Maven Enforcer failing with dependency convergence error because of bad Maven POMs

### ISSUE THREAD

**Issue by bitbythecron** [dropwizard/metrics#1220]
Hoping/looking for some advice here.

I forked this repo and [made some changes](https://github.com/bitbythecron/metrics/commit/0997e644ac6d712818e2f353075200ac6fb8c195) (added a new `metrics-akka` subproject/module alongside all the others (`metrics-core`, `metrics-annotation`, etc.). This new `metrics-akka` module pulls in the following Akka dependency:

    <dependency>
        <groupId>com.typesafe.akka</groupId>
        <artifactId>akka-actor_2.11</artifactId>
        <version>2.5.6</version>
    </dependency>

When I run `mvn clean install` I get the following errors:

    Dependency convergence error for org.scala-lang:scala-library:2.11.11 paths to dependency are:
    +-io.dropwizard.metrics:metrics-akka:4.0.0-alpha4-SNAPSHOT
      +-com.typesafe.akka:akka-actor_2.11:2.5.6
        +-org.scala-lang:scala-library:2.11.11
    and
    +-io.dropwizard.metrics:metrics-akka:4.0.0-alpha4-SNAPSHOT
      +-com.typesafe.akka:akka-actor_2.11:2.5.6
        +-org.scala-lang.modules:scala-java8-compat_2.11:0.7.0
          +-org.scala-lang:scala-library:2.11.7

If I'm reading this correct, it looks like this "Maven Enforcer" is failing because the Akka/Scala POMs are broken in Maven Central. Looks like `akka-actor_2.11:2.5.6` depends on both `scala-java8-compat_2.11:0.7.0` and `scala-library:2.11.11`, but that the former also depends on `scala-library:2.11.7`, and the Enforcer doesn't like that.

What are my solutions here? Fix the Akka/Scala POMs somehow? Configure the Enforcer to ignore this error? Something else?

I *do* plan on submitting a PR and trying to convince this community to accept the `metrics-akka` module addition, so whatever solution we cook up will hopefully be something that would be permissible in a PR code review. Thanks in advance!

**Comment by bitbythecron** [comment]
Looking at the [Maven Enforcer plugin docs](https://maven.apache.org/enforcer/maven-enforcer-plugin/usage.html) a little closer (I'm not all that familiar w/ Maven) I was able to get my build succeeding via:

    mvn clean install -Denforcer.fail=false

Would this be an acceptable workaround for the community?

**Comment by arteam** [comment]
I think the best solution would be to fix the Akka POM somehow. I would like to keep the enforcer plugin running, because it's very valuable to detect dependency conflicts.
