### ISSUE TITLE
Timers with exponentially-decaying reservoirs

### ISSUE THREAD

**Issue by joschi** [dropwizard/metrics#1223]
_From @LukaszP1 on November 16, 2017 9:7_

I've used Timers for meter API calls with different frequency which is chaging over time. I faced up problem with some metrics with low calls count, that old metrics are kept for very long time. In result, graphs in Graphite show inaccurate values - old ones.
The problem has been described in this article "Don’t use Timers with exponentially-decaying reservoirs in Graphite' (http://taint.org/2014/01/16/145944a.html).

Author said that:

>  In reality, if the frequency of updates to such a timer drops off, it could take a lot longer, and if you stop updating a timer which uses this reservoir type, it’ll never decay at all. The GraphiteReporter will dutifully capture the percentiles, min, max, etc. from that timer’s reservoir every minute thereafter, and record those to Graphite using the current timestamp — even though the data it was derived from is becoming more and more ancient.

Workaround suggested by author is:

> What we eventually did in our code was to use this Reporter class instead of GraphiteReporter; it clears all Timer metrics’ reservoirs after each write to Graphite. This is dumb and dirty, reaching across logical class boundaries, but at the same time it’s simple and comprehensible behaviour: with this, we can guarantee that the percentile/min/max data recorded at timestamp T is measuring events in that timestamp’s 1-minute window — not any time before that. This is exactly what you want to see in a time-series graph like those in Graphite, so is a very valuable feature for our metrics, and one that others have noted to be important in comparable scenarios elsewhere.

What is your reccomendation to deal with such problem?

_Copied from original issue: dropwizard/dropwizard#2212_

**Comment by joschi** [comment]
@LukaszP1 You probably want to post this issue in another repository: https://github.com/dropwizard/metrics

**Comment by joschi** [comment]
_From @LukaszP1 on November 16, 2017 9:35_

@joschi  Yes, you're right. I'm sorry - I'm new on github.
Is it possible to move this issue, or should I close this issue and open another in https://github.com/dropwizard/metrics ?

**Comment by vladimir-bukhtoyarov** [comment]
Hello joschi ,

If you need detailed control for retention time you can use:
- Built-in to core [SlidingTimeWindowReservoir](https://github.com/dropwizard/metrics/blob/4.0-development/metrics-core/src/main/java/com/codahale/metrics/SlidingTimeWindowReservoir.java), but be careful if your event rate is high.
- Third-party reservoir from [Rolling-Metrics](https://github.com/vladimir-bukhtoyarov/rolling-metrics/blob/master/histograms.md), which has stable memory footprint independent of event rate.

**Comment by LukaszP1** [comment]
Hello Vladimir,
 In this case third-party reservoir you mentioned is better than default one?
Or even more (according to Rolling-Metrics description) it is better in most of the cases?

@joschi Thank you for moving my issue.

**Comment by vladimir-bukhtoyarov** [comment]
There is no simple answer, you need to make decision by yourself. 

Rolling-Metrics advantages:
- Garbage-free
- Lock-free
- Predictable and fixed memory footprint
- Never loses min and max

Rolling-Metrics disvantages:
- In comparision with ExponentialDecayingReservoir the average is not weighted.
- Built-in SlidingTimeWindowReservoir has better accuracy because it stores each event independently, when Rolling-Metrics does not store events independently from each other, instead it relies on approximation algorithms implemented in HdrHistogram.

**Comment by storozhukBM** [comment]
@joschi @LukaszP1 
We  have drastically improved version of `SlidingTimeWindowReservoir` called `SlidingTimeWindowArrayReservoir` it is available from version `3.2.3`
Its memory allocation is still dependent from event rate but actual footprint is so small that it shouldn't be a problem unless you want to update it more than 50K times per second.
Take a look at hint from [documentation](http://metrics.dropwizard.io/3.2.3/manual/core.html#sliding-time-window-reservoirs).
