### ISSUE TITLE
Nested timers, the inner timer is larger than the outer timer

### ISSUE THREAD

**Issue by chyangzhang** [dropwizard/metrics#1228]
Hi there,
I have started using dropwizard metrics for monitoring the server's performance for a while, but I encountered this very strange situation.
I have a set of nested timers set up for monitoring a whole function let's say T1, and another timer monitoring some part of the function let's say T2. But somehow, at some time T2's metric is larger than T1 which should not happen at all. Since T1 has a lot more works to do other than the part that T2 is measuring. 
More details: T1 actually is using Histogram instead of Timer but the time is returned by Timer.stop() and T2 is using Timer
Any thoughts why this happened.
<img width="467" alt="screen shot 2017-12-07 at 4 28 35 pm" src="https://user-images.githubusercontent.com/11203184/33745485-fc4763aa-db6b-11e7-96ee-3c3fb78d29c7.png">

**Comment by vladimir-bukhtoyarov** [comment]
1. Be sure that T1 and T2 use same time units.
2. Does frequncy of events reported to T2 equal to frequency of events reported to T1?

**Comment by storozhukBM** [comment]
I think it can be possible due to `ExponentiallyDecayingReservoir` (default Histogram implementation) random nature. As @vladimir-bukhtoyarov mentioned we need to now the updates frequency of T1 and T2 and what percentiles you're rendering here. It will help to clear this situation.

**Comment by chyangzhang** [comment]
@vladimir-bukhtoyarov 
1. The display time units are both milliseconds
2. You are right actually, T1's frequency is less than T2's
That makes sense then

**Comment by chyangzhang** [comment]
@storozhukBM 
Thanks for your replay, I'm rendering the max of the t1 and t2 here. I think @vladimir-bukhtoyarov 's question explained the situation here
