### ISSUE TITLE
Send JMX metrics to a remote machine

### ISSUE THREAD

**Issue by srijiths** [dropwizard/metrics#1235]
Hi Team,

Is it possible to send the JMX metrics through JMX Reporter to a JMX port which is already running in local/remote ?

I could not see any settings like IP:Port when initiating JMX Reporter.

Regards,
Srijith

**Comment by arteam** [comment]
I'm not aware that it's possible with JMX. I think your best bet to report metrics locally and then enabled a JMX agent. There are many 3rd party reporters which supported reading JMX metrics from a JVM instance.

**Comment by srijiths** [comment]
Thank you Arterm,

I was checking whether is there a way to avoid those JMX agents.  The
number of  JMX agents are proportional to the number of applications that
reports metrics.

In my case what i was thinking, i have a kafka cluster with JMX enabled on
a port.  And i have number of kafka connectors enabled with dropwizard
metrics. Instead of using separate agents per application, would be great
if we can centralize JMX reporting.

Just checking the feasibility. Thank you
