### ISSUE TITLE
IncompatibleClassChangeError caused by Timer.Context refactor

### ISSUE THREAD

**Issue by arkigabor** [dropwizard/metrics#1243]
The following commit changed Timer.Context from a class to an interface:
https://github.com/dropwizard/metrics/commit/1bacf4d645803f6241aeb0a9365dc44d2c43f2cf#diff-7423b8a39b3ee1cb8ad641557972ab24

This is causing a unique runtime issue (even if not a bug per se). If a class was compiled with an older version of Metrics where context was a class but is run on a new version of Metric where Context is an interface, Java is trowing:

> Caused by: java.lang.IncompatibleClassChangeError: Found interface com.codahale.metrics.Timer$Context, but class was expected

This basically renders v4.0 fully incompatible with v3.x if a dependency is using the Timer.Context class.

**Comment by arteam** [comment]
Thanks for bringing this up! I will revert this change, because I would like to see code compiled against 3.x to work with 4.x.

**Comment by arteam** [comment]
Closed via #1244

**Comment by arteam** [comment]
@arkigabor I've released Metrics 4.0.1 to Maven Central, could you please take a look?

**Comment by davidkarlsen** [comment]
@arteam
I see there is a github release: https://github.com/dropwizard/metrics/releases/tag/v4.0.1 - but nothing on central? http://repo1.maven.org/maven2/io/dropwizard/metrics/metrics-bom/

**Comment by arkigabor** [comment]
@davidkarlsen 
I'm still waiting for 4.0.1 making it to central too, although I think it can take up to a day for releases to appear there.

**Comment by arteam** [comment]
@davidkarlsen @arkigabor Sorry, my mistake, I didn't sync the Nexus staging repository with Central.
I've run it now, and it usually it takes a couple of hours for the Centrals replicas to sync.

**Comment by arkigabor** [comment]
4.0.1 is available in Central and this issue has been resolved. Thanks for the quick fix.
