### ISSUE TITLE
Inconsistency registring gauges and health checks

### ISSUE THREAD

**Issue by erikvanoosten** [dropwizard/metrics#1245]
When once registers a gauge under the name of an already registered metric, this fails with an exception. A similar operation; registering a health check under the name of an already registered health check fails silently, its a no-op.

You could argue either way but I think that `HealthCheckRegistry.register` should throw when the name is already in use.

**Comment by erikvanoosten** [comment]
If the maintainers agree, I can create a pull request to throw an exception from `HealthCheckRegistry.register`.

**Comment by arteam** [comment]
Yes, this sounds like a good improvement and should prevent incidental overriding of existing health checks.
