### ISSUE TITLE
Change package for new major releases (4.x.x, 5.x.x)

### ISSUE THREAD

**Issue by udoprog** [dropwizard/metrics#1248]
Changing the package name when doing major releases is critical to avoid a special kind of dependency hell for libraries.

There are two concepts here which collide:
* A major change implies a [binary compatibility break](https://wiki.eclipse.org/Evolving_Java-based_APIs_2).
* Libraries are transitively embedded into the dependencies of any project.

Let's say you have a dependency graph which contains both `3.x.x` and `4.x.x`. Because the fully qualified name of the classes conflict, only one will be used due to how the classpath _currently_ works. If it attempts to do something which is not compatible with the given major version that they are using code interacting with this class will crash at runtime. This is especially egregious if it happens because one of your dependencies use one version or the other.

By not having separate packages for the different major versions, it is now exceedingly difficult to introduce compatibility layers as the ecosystem is moving from one version to another. Given a [hard enough incompatibility](https://groups.google.com/forum/#!topic/protobuf/cXbnth6QVnU), you'll end up in a catch 22 where no one is able to upgrade without resorting to something like shading every dependency and the entire ecosystem is stuck in a lock step of major upgrades.

With different package names we can do things like introduce a shim metric registry that provide an API for a previous version. This can then be used by the application providing the MetricRegistry to decide which version of the library to use.

For more detailed information, I've written about this topic in the past: https://udoprog.github.io/programming/2015-09-03/semantic-versioning-java.html

Note that this also applies to having a distinct *groupId*:*artifactId* combo for maven packages, since that is how it currently prunes its dependency graph. This did change from 3.x.x -> 4.x.x, but currently doesn't seem to be the direction with 5.x.x: https://github.com/dropwizard/metrics/blob/5.0-development/metrics-core/pom.xml#L6

RxJava is a good example of a project that took this seriously for their 1.x -> 2.x transition: https://github.com/ReactiveX/RxJava

P.S. It should be noted that some libraries are less offensive in this regard, since they primarily exist in the periphery in the dependency graphs, and types provided by them aren't shared as much.

**Comment by arteam** [comment]
Thanks for the very insightful comment!

I do think it makes sense to change the Maven coordinates and package names for _5.0.*_. The situation right now is very confusing. Metrics went from `com.codahale.metrics` to `io.dropwizard.metrics` Maven coordinates during the _3.0.*_ - _3.1.*_ transition, but the package name didn't change! For the sake of trying to make _4.0.*_ a drop-in replacement for _3.2.*_ in Java 8/9, I didn't change the package name. For _5.0.*_ I want to go with new Maven coordinates and package names to clearly mark that Metrics _5.0.*_ will not be compatible with the previous generation of Metrics.

I really like RxJava's approach to versioning. I'm thinking adding some information about different Metrics version and their status to README.

**Comment by rconn01** [comment]
Agree that coordinates and package names should be changed with the move to 5.0. Linking previous discussions around this from when 4.0 was going to be the version that introduced breaking changes with tags https://github.com/dropwizard/metrics/pull/1097
