### ISSUE TITLE
Using Timer when start and stop happen on two different threads?

### ISSUE THREAD

**Issue by zharvey-welltok** [dropwizard/metrics#1257]
In my (Java) web app, when a new user signs up, the backend sends them an email so that they can verify their email address. They then check their email, click the link we sent them, this "activates" their account and they can now log in.

I'm interested in collecting metric data about *how long (on average)* it takes users to verify their email from the time they sign up and we email them. The problem here is: I'm trying to use a Dropwizard `Timer` to take the time differential between events happening (essentially) on two different threads! The first thread is the HTTP request thread when the user signs up. The second thread is the HTTP request thread when the user clicks the verification link in their email.

```
// Groovy pseudo-code
@RestController
@RequestMapping('/users')
class UserController {
    @Autowired
    MetricRegistry metricRegistry

    // lots of other stuff here

    @PutMapping
    @ResponseBody
    void onNewUserSignUp(@RequestBody NewUserSignUp newUserSignUp) {
        Timer.Context timer = metricRegistry.timer('new.user.signup').time()

        // Create a User record in the DB, mark it as "unverified" so they can't log in yet.

        // Send the user an email with a link they have to click to "verify" themselves.
    }

    @GetMapping('/{userId}')
    @ResponseBody
    void onClickVerifyLinkFromEmail(@RequestParam String verificationToken) {
        // Not only would this probably not work (!!!) but it also isn't user-specific...
        Timer.Context timer = metricRegistry.timer('new.user.signup').stop()

        User user = lookupFromVerificationToken(verificationToken)

        user.verified = true
        // Save modified user back to DB
    }
}
```

So this question is really: **how do I use Dropwizard Metrics' `Timer` to record duration between start/stop events that occur on two different threads?**

I *suppose* I could keep a cache of `Timer` instances in memory...but then I might have tens/thousands of open timer instances just hanging out. I guess its not a huge deal but seems kind of kludgy, especially if DW Metrics has a better way to solve it!

**Comment by arteam** [comment]
It seems to me that the latter approach is the way to go.You can just keep `Timer.Context` instances in an expirable hash map by user ids. When the user has verified its account, you get the corresponding context from the map and call stop on it. `Timer.Context` is immutable, so it should be safe to share it between threads.

**Comment by zharvey-welltok** [comment]
Thanks @arteam -- wouldn't you be worried about hogging memory though? Say I have a huge promotional event that drives 10,000+ users to my app...I'd have a `Timer.Context` for each of them, memory would explode, no?!

**Comment by vladimir-bukhtoyarov** [comment]
@zharvey-welltok first of all - in-memory collection will not work for:
- Cluster of servers, if welcome mail sent from one server and confirmation procedure happen on another.
- Even in case of one server, in-memory collection does not survive the restart of server.

You already have a database, just store the time of welcome email within user record, and re-use it inside confirmation procedure:

```java
    @PutMapping
    @ResponseBody
    void onNewUserSignUp(@RequestBody NewUserSignUp newUserSignUp) {
        // blah-blah

       // remember timestamp of welcome email
       user.setWelcomEmailTimestamp(System.currentTimeMillis());

        // Create a User record in the DB, mark it as "unverified" so they can't log in yet.

        // Send the user an email with a link they have to click to "verify" themselves.
    }

   @GetMapping('/{userId}')
    @ResponseBody
    void onClickVerifyLinkFromEmail(@RequestParam String verificationToken) {
        User user = lookupFromVerificationToken(verificationToken);
       
         long confirmationTimeMillis = System.currentTimeMillis() - user.getWelcomeEmailTimestamp();
        Timer timer = metricRegistry.timer('new.user.signup');
        timer.update(confirmationTimeMillis, TimeUnit.MILLISECONDS);

        user.verified = true
        // Save modified user back to DB
    }
```

**Comment by zharvey-welltok** [comment]
Thanks @vladimir-bukhtoyarov makes perfect sense. Just one quick question though: do I need to call `timer.stop()` after `timer.update` to stop the timer from counting any further? Thanks again!

**Comment by vladimir-bukhtoyarov** [comment]
@zharvey-welltok you need not to use TimerContext when using ```update``` directly.
