### ISSUE TITLE
API improvements

### ISSUE THREAD

**Issue by pulquero** [dropwizard/metrics#1261]
I have a suggestion to improve your
`Counter counter(MetricName name, final MetricSupplier<Counter> supplier) `
style methods in MetricRegistry. I see two drawbacks for a consumer:
1) I would naturally tend to write `MetricSupplier<MyCounter>` inner class rather than `MetricSupplier<Counter>`
2) I have to cast the result to MyCounter (MyCounter might extend Counter with some extra methods I need to call).

You could consider
`<T extends Counter> T counter(String name, final MetricSupplier<T> supplier)`
instead. This overcomes both of the above mentioned limitations. Further, you can have a stricter `isInstance()` method in your anon MetricBuilder than just `Counter.class.isInstance(metric)`. It is likely that the actual supplier impl will have a literal generic type, e.g. `MetricSupplier<MyCounter>`. Using reflection, it is possible to extract this from the declaration, you could then do `declaredCounterType.isAssignableFrom(metric.getClass())`
In the worst case, you have to fallback to Counter.class.

**Comment by arteam** [comment]
This makes a lot of sense. It seems extending is the only possible way to customize counter, so users can expect that we provide an type-safe API for dealing with extended counters. This also follows the API guidelines from _Effective Java Item 28. Use bounded wildcards to increase API flexibility_.

**Comment by arteam** [comment]
Closed via #1268

**Comment by pulquero** [comment]
How about the other metric types?
