### ISSUE TITLE
Timing On Tag Support

### ISSUE THREAD

**Issue by smojtabai** [dropwizard/metrics#1266]
I see tag support is in development for 5.x branch, any thoughts on timeline or ideas of what the interface will look like when implemented?

Thanks!

**Comment by arteam** [comment]
In the 5.0 version there will be a new abstraction: [MetricName](https://github.com/dropwizard/metrics/blob/5.0-development/metrics-core/src/main/java/io/dropwizard/metrics5/MetricName.java). It will encapsulate the name of a metrics and the maps of tags associated with it. This abstraction will be accessible to reporters, so they can transform tags to the corresponding time-series database format. Users will be able to tag metrics via the `MetricName` API and register a metrics with based on `MetricName`. Take a look at [MetricRegistry](https://github.com/dropwizard/metrics/blob/5.0-development/metrics-core/src/main/java/io/dropwizard/metrics5/MetricRegistry.java).

**Comment by smojtabai** [comment]
Thank you, this is very helpful, any thoughts on release timeline?

**Comment by arteam** [comment]
I want to merge the module with an adapter for Metrics 4 and after that make an alpha-release.

**Comment by arteam** [comment]
I've released 5.0.0-rc0: https://github.com/dropwizard/metrics/releases/tag/v5.0.0-rc0
It should be available soon in the Maven central repository. Try it out!

**Comment by smojtabai** [comment]
Amazing, we definitely will
