### ISSUE TITLE
Meter vs Counter explanation and use cases

### ISSUE THREAD

**Issue by JeremyColton** [dropwizard/metrics#1271]
Hi, I am yet to find a good explanation of meter vs counter.  From what I've read:
- meter records a value over time eg records a value between submissions to DataDog's agent and resets to zero after each submission.  (NB DataDog records this as a Gauge! https://docs.datadoghq.com/developers/metrics/#how-do-submission-types-relate-to-datadog-in-app-types )
- counter increases in size always (ignore processing a queue that can decrease in size) but it never resets so the counter will get larger and larger. If the server running this metrics library restarts, then the counter resets.

1. Correct?
2. When should I use each metric type?

**Comment by arteam** [comment]
1. Not exactly. A `Meter` records  rates 1-, 5-, and 15-minute weighted moving averages. Newer data has bigger weight than old, but the old data don't reset between reporting, they just become less significant.
2. You should use a `Counter` if you want to see an exact _mean_ value for a time interval. You report the counter value to the database, and ask it to calculate a mean value between two data intervals.
`Meter` is useful when you don't want to report data very often or/and you don't care about exact averages, but for trends. For example, if you measure a volatile process, EWMA allows you to smooth out the effect of outliers to an average value.

**Comment by JeremyColton** [comment]
1. Thanks so much.

2. 'Volatile process' meaning it's unknown how often it executes?

My use-case is to record every time a specific event occurs (eg page view) and to see the sum of the views per time interval (not the _mean_).  This allows me to see how many page views happened in the last hour, day, week etc. (NB I'm sending my metrics to DataDog if this helps...)

**Comment by cowolter** [comment]
I think a meter tracks a rate (a value in connection with another unit). For example, the gas meter records the amount of gas that has been used within a certain period of time. The same holds true for a water meter. A counter by contrast tracks only one value.

**Comment by sandeshjkhoros** [comment]
> 1. Thanks so much.
> 2. 'Volatile process' meaning it's unknown how often it executes?
> 
> My use-case is to record every time a specific event occurs (eg page view) and to see the sum of the views per time interval (not the _mean_). This allows me to see how many page views happened in the last hour, day, week etc. (NB I'm sending my metrics to DataDog if this helps...)

@JeremyColton Did you find a solution for this problem ? What was the dropwizard metric type that you had to use finally to achieve what you were looking for ? I have a similar requirement, and thought using the "Counter" type would help, but in datadog I am not seeing the "sum by" option for this metric.
