### ISSUE TITLE
Expansion filter for Slf4jReporter

### ISSUE THREAD

**Issue by fabienrenaud** [dropwizard/metrics#1273]
The slf4j reporter is too verbose by default and I'd like to be able to filter which expansions (as defined by [coursera-metrics-datadog](https://github.com/coursera/metrics-datadog)) are logged.

Proposed api:

```java
var expansions = EnumSet.of(COUNT, RATE_1_MINUTE, RATE_15_MINUTE, MEDIAN, P95, P99);
Slf4jReporter.forRegistry(registry)
                .outputTo(LoggerFactory.getLogger(Foo.class))
                .withExpansions(expansions)
                .convertRatesTo(TimeUnit.SECONDS)
                .convertDurationsTo(TimeUnit.MILLISECONDS)
                .build()
```

If there is no objection to this proposition, I will submit a pull request within the next few days.

**Comment by arteam** [comment]
Hi. The proposal looks good and a PR will be welcomed. We have implemented this ability for [GraphiteRepoter](https://github.com/dropwizard/metrics/blob/4.1-development/metrics-graphite/src/main/java/com/codahale/metrics/graphite/GraphiteReporter.java#L177) and [ConsoleReporter](https://github.com/dropwizard/metrics/blob/4.1-development/metrics-core/src/main/java/com/codahale/metrics/ConsoleReporter.java#L171), would be nice to have for `Slf4jReporter` too. The enum is called `MetricAttribute` and we stick to the name convention `disabledMetricAttributes`.

**Comment by fabienrenaud** [comment]
I submitted a PR. Let me know of any feedback.

**Comment by arteam** [comment]
Thanks, I will take a look shortly.

**Comment by arteam** [comment]
Closed via #1275

**Comment by fabienrenaud** [comment]
You introduced a defect with https://github.com/dropwizard/metrics/commit/4384903a1f170a6be83e571afa6a203ad9a83218

The StringBuilder is reused across calls to the log* methods, so `setLength(0)` is required. This helps reducing the frequency of buffer resize/copy and generates less garbage (which is good since we want logging to be as cheap as possible).
There is no test in `Slf4jReporterTest` verifying logging multiple metrics in a row outputs the expected result.

**Comment by arteam** [comment]
Ah, sorry for that. I had presumed we build one message they and log it. I've brought resetting of the builder back and added a unit test for logging several metrics in 010c2dfd8d09911dbfa0e5764577148bdb9b16da. Thank you for spotting the regression!
