### ISSUE TITLE
Is there a way to just report a subset of metrics?

### ISSUE THREAD

**Issue by adkathuria** [dropwizard/metrics#1277]
Example, if we need snapshot.95thPercentile and snapshot.98thPercentile and no other snapshots to be reported, is there a way to customize the metric registry.

Also, if we need to suppress all Rates ( e.g oneMinuteRate, fiveMinuteRate etc) , is that achievable via MetricFilter

**Comment by arteam** [comment]
Hi, you can customize a `Reporter` and filter out metric attributes. Some reporters support that, for  example:
* [GraphiteReporter](https://github.com/dropwizard/metrics/blob/4.1-development/metrics-graphite/src/main/java/com/codahale/metrics/graphite/GraphiteReporter.java#L177)
* [ConsoleReporter](https://github.com/dropwizard/metrics/blob/4.1-development/metrics-core/src/main/java/com/codahale/metrics/ConsoleReporter.java#L171)

**Comment by regispl** [comment]
@arteam Out of curiosity - is there any specific reason why it's not possible in other reporters, e.g. JMX one? Just a missing feature or is there a potential issue that I'm not aware of? :-)
