### ISSUE TITLE
ExponentiallyDecayingReservoir empty list check?

### ISSUE THREAD

**Issue by psyopguy** [dropwizard/metrics#1278]
Hi just wondering why there can't be a NoSuchElementException in ExponentiallyDecayingReservoir line 105. Since it seems possible that the list is still empty - assuming all 1028 threads before it got preempted before inserting a value to the list.

Another issue with this method - Isn't it more efficient to only create the object WeightedSample if it is selected to be stored?

**Comment by arteam** [comment]
Hi @psyopguy,

* Looks like it actually can, but the probability of such an event is very low. Nevertheless, we probably should check the size of the `value` map before calling `firstKey` to hold the invariant "map is not empty".
* It is, but I presume the branch "priority is lower than the first element" is not executed very often, so it doesn't affect the performance of the method much. In comparison to using locks and the cost of an additional allocation is insignificant. On the other hand, switching to allocating `WeightedSample` in place should be very simple.

**Comment by vdoleans01** [comment]
Hi.
I use your library in my project and it work well the majority of time but unfortunatly we have time to time the java.util.NoSuchElementException : at java.util.concurrent.ConcurrentSkipListMap.firstKey(ConcurrentSkipListMap.java:2053)
would it be possible to reconsider the priority of the fix ?
Thanks

**Comment by kevinherron** [comment]
@arteam We're seeing this now as well. Not sure why now, as this code has been running on many machines for a long time.

```
java.util.NoSuchElementException: null
	at java.util.concurrent.ConcurrentSkipListMap.firstKey(ConcurrentSkipListMap.java:2053)
	at com.codahale.metrics.ExponentiallyDecayingReservoir.update(ExponentiallyDecayingReservoir.java:104)
	at com.codahale.metrics.ExponentiallyDecayingReservoir.update(ExponentiallyDecayingReservoir.java:83)
	at com.codahale.metrics.Histogram.update(Histogram.java:39)
	at com.codahale.metrics.Timer.update(Timer.java:149)
	at com.codahale.metrics.Timer.update(Timer.java:86)
	at com.codahale.metrics.Timer$Context.stop(Timer.java:35)
```
