### ISSUE TITLE
Sending delta values to Graphite for Counters

### ISSUE THREAD

**Issue by simondean** [dropwizard/metrics#1279]
Hi. Due to the way my metrics are stored and aggregated, for Counters I need to send delta values to Graphite instead of ever increasing values. In order to do this, I’ve had to extend GraphiteReporter, override the report method and then copy GraphiteReporter’s implementing of the method. 

It would be easier to implement this if the reportCounter method’s visibility was changed from private to protected so it could be overridden in the subclass. 

Alternatively, it would be great if GraphiteReporter (or another higher-level part of the metrics lib) supported generating delta values for counters out of the box

**Comment by genuss** [comment]
Take a look at this project https://github.com/vladimir-bukhtoyarov/rolling-metrics
It has everything you need.
If you don't want to depend on one more library, you can use `nonNegativeDerivative` function from graphite.
