### ISSUE TITLE
Customizable MetricsServlet

### ISSUE THREAD

**Issue by rahulravindran0108** [dropwizard/metrics#1281]
I would like to propose the change of accepting a customized MetricsModule into MetricsServlet.
There are some customization issues on MetricsModule itself,  since members such as rateUnit, durationUnit, showSamples and filter are private, it is not possible to override. My suggestions are:

- Make members of MetricsModule protected so it is easier to add in new serializers in the setupModule function. This is particularly helpful if we want to limit the rollups being provided for each metric type such as Counters, Timers etc. I think this should be owned by the metric type itself, however it is fine for now if we can add in customizable serializers since it would be the same effect.
- Do the same for MetricsServlet or let a MetricsModule *like* class be injectable in the constructor. This should make it possible to customize the response from MetricsServlet.

I would be happy to work on a PR if my suggestions look good.

**Comment by rahulravindran0108** [comment]
@arteam any thoughts on this ?

**Comment by arteam** [comment]
Sounds reasonable, I will happily review a PR for customizing `MetricsModule`. As a plus, #1240 would be easier to incorporate to the upstream.

**Comment by rahulravindran0108** [comment]
@arteam I've opened a PR for this. Do take a look at it.
