### ISSUE TITLE
Use collectd-metrics with network cryptography

### ISSUE THREAD

**Issue by defeng-song** [dropwizard/metrics#1284]
Hi, we want to use collectd-metrics in our project, but looks like there is no support for network cryptography.
For example, as described in collectd wiki: https://collectd.org/wiki/index.php/Networking_introduction
In order to send metrics to our collectd server, we need to provide credentials and `SecurityLevel "Encrypt"`. Do you have plans on this?
Thanks!

**Comment by arteam** [comment]
Thanks for your interest in metrics! You're right, the library doesn't support encryption for Collectd, but I took a look at the encryption part the binary protocol https://collectd.org/wiki/index.php/Binary_protocol, and it seems not terribly complicated to implement. I will take a swing on it next week.

**Comment by defeng-song** [comment]
Hi, thank you for taking this up. The required client side config which works for us is something like this:
```
LoadPlugin network
<Plugin network>
    <Server "10.0.0.1" "25826">
        SecurityLevel Encrypt
        Username "user"
        Password "pass"
    </Server>
</Plugin>
```
Thanks!
