### ISSUE TITLE
Feature Request: SSL/TLS encrypted GraphiteReporter

### ISSUE THREAD

**Issue by Mexx77** [dropwizard/metrics#1295]
Hey Dear metrics supporters,

I need to write my Apache flink metrics towards a carbon-relay (Graphite endpoint) that accepts TLS-encrypted TCP traffic only. This is a security constraint of my company. dropwizard/metrics does not seem to support TLS encryption as far as I can tell.
Any chance to implement such an option?

Thanks, Mexx

**Comment by arteam** [comment]
Hi @Mexx77! You can pass a `SSLSocketFactory` to `Graphite` and it will force SSL/TLS sockets on the client side. For example,
```java
Graphite tlsGraphite = new Graphite("carbon.hostedgraphite.com", 20030, SSLSocketFactory.getDefault())
```

You can then use this instance in `GraphiteReporter`. If the Carbon relay is uses an SSL certificate signed by a CA, that should be enough. In case the certificate is self-signed than you would need to add it a trustore and register it in the JVM via the system property `javax.net.ssl.trustStrore`.
