### ISSUE TITLE
All Reporters are Closeable?

### ISSUE THREAD

**Issue by tjcelaya** [dropwizard/metrics#1305]
It seems #743 was closed without a merge because the forked repository was deleted? I cloned this repo to verify that all classes which implement `Reporter` (directly or indirectly) also implement `Closeable`. I'd be happy to submit a PR like #743 and provide attribution to @obfischer if it's an acceptable improvement.

**Comment by arteam** [comment]
I believe all the reporters provided by metrics implement `Closeable` (directly or via  `ScheduledReporter`).

**Comment by arteam** [comment]
57739fc4b9e703f65e30f4f41230c9224972adb2

**Comment by tjcelaya** [comment]
I guess I should've provided a code sample, but what I'm specifically asking about is whether or not #1307 would be a useful patch. It seems cumbersome to have all reporters implement both interfaces but force the user to choose between the types when referring to a generic reporter.

If the PR seems silly then feel free to disregard the change.
