### ISSUE TITLE
Loss of binary compatibility between 3.x and 4.x - JMX package change

### ISSUE THREAD

**Issue by michaelbraun** [dropwizard/metrics#1306]
ObjectNameFactory in Dropwizard Metrics 3.x is located in package com.codahale.metrics
ObjectNameFactory in Dropwizard Metrics 4.x is located in package com.codahale.metrics.jmx

Ditto for the JMXReporter class.

Because of this, it's not possible to drop in 4.x jars for any code using JMX related classes. This affects projects like Apache Solr which references these classes in code (see https://github.com/apache/lucene-solr/blob/master/solr/core/src/java/org/apache/solr/metrics/reporters/jmx/JmxMetricsReporter.java) 

My understanding was the 4.x releases should be compatible as mentioned in https://github.com/dropwizard/metrics/issues/1248

One motivating factor to move to Metrics 4.x is for Java 9+ compatibility as found in https://github.com/dropwizard/metrics/pull/1236 - right now there doesn't appear to be a backport of that fix to the 3.x line.

**Comment by arteam** [comment]
You're right. Unfortunately, it was not possible to move JMX to a new module without breaking backwards compatibility. For Solr, I would advice to add `metrics-jmx` module to the build and change the JMX imports. 

Nevertheless, I will try to produce a Metrics4 build with JMX in the core, so users will be able to swap a Metrics3 jar to Metrics4 jar.

**Comment by arteam** [comment]
Here's a branch: https://github.com/dropwizard/metrics/commits/4.0-jmx

**Comment by rsouhrain** [comment]
Hi @arteam, when would 4.0-jmx be released?

Thanks
