### ISSUE TITLE
InstrumentedExecutorService: no idle time for callables

### ISSUE THREAD

**Issue by mziccard** [dropwizard/metrics#1313]
https://github.com/dropwizard/metrics/pull/1180 introduced idle time (time spent in the executor queue) for instances of `Runnable` submitted to an `InstrumentedExecutorService` (via `InstrumentedRunnable`). Idle time was not added the same way to `Callable` (i.e. to `InstrumentedCallable`).

What this done on purpose?

If not, I can send a PR, should be an easy fix.

**Comment by arteam** [comment]
Nice catch! I don't know any specific reason why we don't track `idleTime` for `Callable` tasks, I guess it was just an oversight. I would gladly review a PR for adding it.
