### ISSUE TITLE
report method is not catching  exception IllegalStateException("Already connected")  in 3.1.15

### ISSUE THREAD

**Issue by lumeche** [dropwizard/metrics#1314]
I  was  troubleshooting  a problem  I have  with my metric server  so  I  decided to call the report() method from com.codahale.metrics.graphite.GraphiteReporter by hand (I know that this  is not suppose to be done that way but  the  method is public so why not :) ) This  method is called  by the start() method of it's  parent class  com.codahale.metrics.ScheduledReporter.

Basically what I found  is  that if two threads comes to the  method report() almost at the same time, the  first  one will  connect. If  the second  thread tries  to connect before  the  first one  has finished an IllegalStateException("Already connected") exception is  thrown by  com.codahale.metrics.graphite.Graphite. This  exception is  not caught by the report() method  and  it dies. If  you  are unlucky enough that this method was running by the  thread started  by the start method of com.codahale.metrics.ScheduledReporter, your application won't send metrics  anymore

**Comment by lumeche** [comment]
This may relates to https://github.com/dropwizard/metrics/issues/1122

**Comment by arteam** [comment]
Can you please specify the version of Metrics that you are using? There have been a few changes in Metrics 3.2 regarding `GraphiteReporter`.

**Comment by lumeche** [comment]
I observed in 3.1.15

**Comment by arteam** [comment]
Got it. You can try to upgrade to 3.2.4, but I think it shouldn't help much. `GraphiteReporter` is unfortunatelly stateful and can't report metrics from several threads. The `report` method is usually invoked by a scheduler from the `start` method, which catches all exceptions, so it usually not an issue.

Nevertheless, I think we can fix it by introducing a synchronized block in the `report` method of `GraphiteReporter`. This shouldn't be a big performance hit for a single-threaded reporting, but it will avoid `IllegalStateException("Already connected")` if the method is invoked from several threads.
