### ISSUE TITLE
How to drop a timing session emitted from Timer?

### ISSUE THREAD

**Issue by zd-project** [dropwizard/metrics#1321]
For example, I would only like to consider the timing of a complete try block execution but discard all timing when an exception occurs. I'm worried if the underlying GC might mess up the metrics if I simply just drop the object reference. Is there any method I can call to drop the timing session? Or can I open a PR for this feature?

**Comment by vladimir-bukhtoyarov** [comment]
As you can see [source code](https://github.com/dropwizard/metrics/blob/4.1-development/metrics-core/src/main/java/com/codahale/metrics/Timer.java#L18), Context does not override ```finalize```, and  [context initialization](https://github.com/dropwizard/metrics/blob/4.1-development/metrics-core/src/main/java/com/codahale/metrics/Timer.java#L111) does not register any reference, so you should not worry about GC. Just interact with context directly and avoid to use it inside ```try``` statement if you want to ignore exceptional cases.

**Comment by zd-project** [comment]
What do you mean by avoid using it? Do you mean not to declare it as a resource in try block? 

I think I can do something like so right?

```
timing = timer.time();
try {
     // something...
     timing.stop();
} catch(exception e) {
     LOG.warn(...);
}
```

**Comment by vladimir-bukhtoyarov** [comment]
exactly

**Comment by zd-project** [comment]
Thanks
