### ISSUE TITLE
Jetty 9 asynchronous requests are incorrectly reported

### ISSUE THREAD

**Issue by tnn** [dropwizard/metrics#1324]
It appears https://github.com/dropwizard/metrics/pull/1074 has reappeared. 

We just observed this on `3.2.3`, `3.2.6` and `4.0.2`:
```
jetty_active_requests -4.0
jetty_active_suspended -5.0
```
We have verified this on multiple systems. Our service were this is observed, uses the following setup:
jetty: 9.4.8.v20171121
jersey: 2.25.1
Java: 9.0.0, 9.0.4, 10.

We are using Jersey/JAX-RS AsyncResponse. We have inspected the heap and threads - and found no evidence that the AsyncResponse has not properly been resumed. We have verified running both as `-jar` and `jmod`.

It appears that when a request is immediately completed (buffered by Jersey), but still a AsyncResponse, the `if (state.isSuspended())` branch in `InstrumentedHandler` is never hit, because while the request has state (`HttpChanelState`):
```
_state = {org.eclipse.jetty.server.HttpChannelState$State@7071} "DISPATCHED"
_async = {org.eclipse.jetty.server.HttpChannelState$Async@7072} "COMPLETE"
_asyncRead = {org.eclipse.jetty.server.HttpChannelState$AsyncRead@7073} "IDLE"
```

The state while incrementing (line 224, `if (state.isInitial()) {`):
```
_state = {org.eclipse.jetty.server.HttpChannelState$State@7071} "DISPATCHED"
_async = {org.eclipse.jetty.server.HttpChannelState$Async@7229} "NOT_ASYNC"
_asyncRead = {org.eclipse.jetty.server.HttpChannelState$AsyncRead@7073} "IDLE"
```

So it appears that the `activeSuspended.dec();` on line 232 needs to take into account if the request is async, is completed and that the `async` state has gone from `NOT_ASYNC` to `COMPLETE`.

Please let us know, if we can help in anyway.

**Comment by tnn** [comment]
@arteam Any update on this?

**Comment by scottjohnson** [comment]
We are experiencing this same issue, while using Spring Webflux/Reactor to handle asynchronous requests.

For requests that get suspended as part of handling the request, the `active-suspended` metric is reported correctly.

However for requests that complete immediately (without getting suspended as part of handling the request), the `active-suspended` metric is decremented in  `InstrumentedHandler#onComplete` without having first been incremented in the `#handle` method's `if (state.isSuspended()) {` condition. This causes the metric to have a monotonically growing negative value as an increasing number of requests are handled by the server.

Our set up is:

Metrics: 4.0.3
Jetty: 9.4.12.v20180830
Spring Webflux: 5.1.2
Reactor-core: 3.2.2
Java: 8, 9, 10

As stated by @tnn, is appears that the `activeSuspended.dec()` in `#onComplete` needs to take in to account whether the request was first suspended before trying to decrement this metric.
