### ISSUE TITLE
Log4j2 MetricsAppender is not detected

### ISSUE THREAD

**Issue by carterkozak** [dropwizard/metrics#1335]
We can apply the `log4j-core` module as an annotation processor to `metrics-log4j2` in order to avoid setting a package in the log4j2 configuration.

This creates a discoverable `META-INF/org/apache/logging/log4j/core/config/plugins/Log4j2Plugins.dat` resource to allow plugins to be discovered at runtime.

**Comment by carterkozak** [comment]
@arteam @dhatanian did you mean to reference and close #1355? I don’t think this issue is fixed.

**Comment by dhatanian** [comment]
@carterkozak no apologies, I must have referenced the wrong issue number when writing that commit.
The issue I meant to refer is #1355
