### ISSUE TITLE
The Metrics BOM causes issues for projects depending transitively on Logback

### ISSUE THREAD

**Issue by srdo** [dropwizard/metrics#1336]
Hi,

I have a project depending on the cassandra-all artifact (e.g. https://mvnrepository.com/artifact/org.apache.cassandra/cassandra-all/3.11.3). It has dependencies on logback-classic and logback-core.

When I add the Metrics BOM to my project, the logback-classic version is overridden to 1.2.3, but logback-core is left at 1.1.3.

I think either the BOM should only lock versions for the Metrics artifacts (as e.g. JUnit and Camel do https://mvnrepository.com/artifact/org.junit/junit-bom/5.2.0, https://mvnrepository.com/artifact/org.apache.camel/camel-bom/2.22.0) and not all dependencies, or the BOM should set logback versions for all 3 artifacts (logback-core, logback-classic and logback-access) from the Logback project.

**Comment by facboy** [comment]
I think the general approach for BOMs seems to be that they should only manage the versions of a project's own artifacts, not the versions of its transitive dependencies.

**Comment by ryantenney** [comment]
This should be addressed in 4.0-maintenance, 4.1-development, and 5.0-development.
