### ISSUE TITLE
Unecessary allocations in WeightedSnapshot Sorting

### ISSUE THREAD

**Issue by CodingFabian** [dropwizard/metrics#1338]
https://github.com/dropwizard/metrics/commit/28db0b4f7529a4437fa7e2cd6432bee99c6807fc
seems to have introduced unnecessary allocations of objects by using a Long object Comparator instead of a long primitive.

<img width="885" alt="screen shot 2018-09-10 at 10 39 40" src="https://user-images.githubusercontent.com/176132/45286346-d80c5f00-b4e5-11e8-845b-e5cad8fa75a6.png">
<img width="883" alt="screen shot 2018-09-10 at 10 41 10" src="https://user-images.githubusercontent.com/176132/45286404-0e49de80-b4e6-11e8-97bf-de09372b3bd1.png">

**Comment by CodingFabian** [comment]
It still is a cood idea to reuse the comparator instance, but it shouldn't box the value

comparingLong() might also work

**Comment by arteam** [comment]
Fixed via #1354
