### ISSUE TITLE
Status of v5

### ISSUE THREAD

**Issue by LukeDefeo** [dropwizard/metrics#1341]
Hey guys what is the status for v5.

I see there is some work to add tags / labels to metrics for services like prometheus / stackdriver that have this concept. on the developmentv5 branch there seems to be a metricname class which implements this.

https://github.com/dropwizard/metrics/commit/7d8479c86057ac62196f888648ac6ac9fe9d03a0

It looks like its implemented at the registry level but doesnt seem to be added to the metric classes themselves, e.g Meter, counter etc

Is this work still going on?

**Comment by Sharpie** [comment]
Interested in this as well. The sum component added to timers in #1254 would be very helpful.

**Comment by randymo** [comment]
Is there an update on this? I am very interested in the dimensional features of this release but it's most recent maven push was 5.0.0-rc2 almost a year ago. It looks like work has been done of the development branch too.

**Comment by mgreene** [comment]
Also interested.

**Comment by Sharpie** [comment]
@arteam Any updates on the status of v5 or blockers to getting it shipped? In addition to having Timers that track sums, I'm starting to look at splitting hostnames out into proper JMX ObjectName keys or tags for InfluxDB/Prometheus/etc. and the new MetricName feature in v5 would make this really straight-forward.

**Comment by mbrannstrom** [comment]
It was a while ago since 5.0.0-rc2 was released. 

@arteam Could you at least create a new 5.0.0-rc3 release of the current 5.0-development branch. It would be nice with the fixes for avoid boxing of longs, as this avoids some garbage created.

Even better would be a plan for the 5.0.0 release... :-)

**Comment by LukeDefeo** [comment]
I would look at micrometer, its similar to dropwizard but has dimensional metrics and much more.  This project seems to show no movement of late.

https://github.com/micrometer-metrics/micrometer

**Comment by Sharpie** [comment]
I took a look at Micrometer and it does have some nice features. However, it also has a dependency on DropWizard and several important implementations, such as Graphite and JMX, delegate to DropWizard.

So, it's not a replacement for our use cases :)

**Comment by mingfai** [comment]
in v5, would you guys consider to add a reset() method for every metrics to set the count and other internal state? 

for my use case, I want my metrics reset daily. And I have to remove those metrics from registry manually and re-create the instance. Not a big deal, but it is nice if there is a way to reset. 

I took a glance at the code. All supporting classes such as MovingAverages interface need to have that reset method.
