### ISSUE TITLE
Support tagged metrics with JMX 

### ISSUE THREAD

**Issue by dlsrb6342** [dropwizard/metrics#1347]
I'm using metrics-core:5.0.0 and metrics-jmx:5.0.0

From v5, I know that MetricsName is added to support tags.
But with JmxReporter in metrics-jmx, if use the default setting, DefaultObjectNameFactory, all the tags added to MetricName are gone and only domain and name remain. 
It doesn't report tagged metrics.

I think DefaultObjectNameFactory implementation should be changed to support tags.
Is there any plan for this issue?

**Comment by arteam** [comment]
Closed via #1352.
