### ISSUE TITLE
Configurable Meter time intervals

### ISSUE THREAD

**Issue by zaharidichev** [dropwizard/metrics#1349]
Hi there I noticed that `Meter` is keeping data for the 1,5 and 15 minutes MA interval.  I am wondering if there is any other way to achieve more custom behaviour.  For example, I want to measure the average throughput of  a task in terms of msg/s. I do however want to have the data sampled every 5 seconds. So At the end of the day I will end up with a series of data indicating what was my average throughput for every interval of size `T`, where `T` is configurable. Sorry for dropping this here, if not relevant.

**Comment by genuss** [comment]
You can always use `count` metric which is produces by `Meter` and manipulate with it, for example take a derivative to get a rate.
