### ISSUE TITLE
Pretty print option for Slf4jReporter

### ISSUE THREAD

**Issue by anadendla-zscaler** [dropwizard/metrics#1351]
Add pretty print option to Slf4jReporter.

The console reporter output is well formatted and easy to read. The slf4j output is in a single line which is not easy to read in development environment.

Having a pretty print out would help.

**Comment by arvindn05** [comment]
would like to see this addressed if possible...so bump

**Comment by joschi** [comment]
@anadendla-zscaler @arvindn05 How would you imagine the pretty-printed output of the SLF4J reporter to look like?

**Comment by arvindn05** [comment]
Console reporter uses below for showing timers

```
-- Timers ----------------------------------------------------------------------
x.y.z.Ingester.Insert times
             count = 0
         mean rate = 0.00 calls/second
     1-minute rate = 0.00 calls/second
     5-minute rate = 0.00 calls/second
    15-minute rate = 0.00 calls/second
               min = 0.00 milliseconds
               max = 0.00 milliseconds
              mean = 0.00 milliseconds
            stddev = 0.00 milliseconds
            median = 0.00 milliseconds
              75% <= 0.00 milliseconds
              95% <= 0.00 milliseconds
              98% <= 0.00 milliseconds
              99% <= 0.00 milliseconds
            99.9% <= 0.00 milliseconds
```
and the slf4j reporter shows the same information as below. It would be good to allow the option to print like above in multiple lines. 

`type=TIMER, name=x.y.z.Ingester.Insert times, count=0, min=0.0, max=0.0, mean=0.0, stddev=0.0, median=0.0, p75=0.0, p95=0.0, p98=0.0, p99=0.0, p999=0.0, mean_rate=0.0, m1=0.0, m5=0.0, m15=0.0, rate_unit=events/second, duration_unit=milliseconds
`

Maybe an API like below to set pretty print?

`Slf4jReporter.forRegistry(metricRegistry).setPrettyPrinting().build()`
