### ISSUE TITLE
Rxjava does not play well with ExceptionMetered

### ISSUE THREAD

**Issue by jeffzoch** [dropwizard/metrics#1357]
RxJava exceptions are propagated through their own pipeline which make it look like errors that originated in a different class came from the class from which you are calling the method. This means that @ExceptionMetered does not work at all (as the proxy doesnt work for methods called in their own class).

**Comment by ryantenney** [comment]
The only module that this would likely be applicable to would be metrics-jersey2, however as a dependency on rxjava isn't desirable, it's out of scope for the project.
