### ISSUE TITLE
Basic Question - Slf4jReporter Configuration

### ISSUE THREAD

**Issue by abennet** [dropwizard/metrics#1377]
I configured a basic sl4j reporter for a metrics registry. This is the reporter configuration:

```
Slf4jReporter.forRegistry(metricRegistry)
                .outputTo(slf4jLogger)
                .convertRatesTo(TimeUnit.SECONDS)
                .convertDurationsTo(TimeUnit.MILLISECONDS)
                .build();
        reporter.start(30, TimeUnit.SECONDS);
```

The logs I am receiving are not what I expected (expected a parseable output of the timers, counters registered wtih metricRegistry). This is what I am actually seeing every 30 seconds (which matches the reporter configuration):

> .... java:55) org.slf4j.helpers.FormattingTuple@39fda09e

Is there anyway to get a useful representation of the codehale metrics (timers, counters etc) in the logs?

Thanks!

**Comment by arteam** [comment]
Can you share the configuration of the underlying logging framework?

**Comment by abennet** [comment]
It's not very straightforward to expose in entirety. The slf4j logger I am using is a custom slf4j adapter (extends MarkerIgnoringBase implements LocationAwareLogger) to an extension of a java.util logger.

Is there a more advisable way to configure a java.util logger for metric registry reporting?

Thank you.
