### ISSUE TITLE
Support for Softhealthchecks to be Async

### ISSUE THREAD

**Issue by mohakkataria** [dropwizard/metrics#1405]
I have reached a point where in I need a softhealthcheck to be async. There is no support currently since https://github.com/dropwizard/metrics/blob/4.1-development/metrics-healthchecks/src/main/java/com/codahale/metrics/health/AsyncHealthCheckDecorator.java is not public and cannot be checked for against in any of the healthcheck registry implementation we try to make. Is there a reason why this was public till now ?

**Comment by dhatanian** [comment]
@mohakkataria you might want to close this as soft healthchecks are not a feature provided by Dropwizard
