### ISSUE TITLE
Minor backwards incompatibilities make upgrading from metrics 3.x -> metrics 4.x harder than it needs to be

### ISSUE THREAD

**Issue by natalie-zamani** [dropwizard/metrics#1440]
There were some classes that were moved out of metrics-core, and into the metrics-jvm and metrics-jmx modules (I believe) in the upgrade from Metrics 3.x to 4.x. This isn't problematic in itself, but what *is* problematic is that the packages changed for several classes.

For instance:

`com.codahale.metrics.JmxAttributeGauge` was changed to `com.codahale.metrics.jvm.JmxAttributeGauge`
`com.codahale.metrics.JvmAttributeGaugeSet` was changed to `com.codahale.metrics.jvm.JvmAttributeGaugeSet`

This has been a source of issues for us in upgrading applications that have transitive dependencies on metrics 3, when our application has upgraded to metrics 4.

We solved this problem internally at our company by creating a compatibility shim that we add as a runtime dependency, that adds those classes back. 

This could be solved in one of two ways, that I can see:
1. Add the old classes with the old package names to their respective modules as deprecated classes, that simply extend the new class.
2. Create a separate compatibility shim that can be added as a runtime dependency for people performing the upgrade. 

I'm happy to contribute either of these two approaches, but would like some input on which option is preferable to the maintainers.

Also, I'm curious if this is a problem you guys are aware of, and what you guys may have done to mitigate it yourselves.

**Comment by arteam** [comment]
There's the `4.0-jmx` branch with the JMX stuff moved back to `metrics-jvm`, but it has never been released to Maven Central. Maybe it makes to do it, if people are interested in a 3.x compatible version of Metrics 4.

**Comment by natalie-zamani** [comment]
It would make our upgrade story a little bit simpler for sure if that could be done.
