### ISSUE TITLE
default Timer with ExponentiallyDecayingReservoir lose all statistical data(all 0) after a period of time

### ISSUE THREAD

**Issue by yamasaLine** [dropwizard/metrics#1448]
**codahale metrics core version: 3.2.6**
**issue description**:
we use default timer with ExponentiallyDecayingReservoir to log latencies in our Production and also our service exposed `/metrics/metrics?prettyPrint=true` servlet to quick check metrics stats. However, after the system ran a period, we found that all Timer statistical data were 0 but the counters, meters and gauges data seemed to be correct. One Timer data inside it would be like:
`"someLatencyTimer": {
"count": 1169,
"max": 0,
"mean": 0,
"min": 0,
"p50": 0,
"p75": 0,
"p95": 0,
"p98": 0,
"p99": 0,
"p999": 0,
"stddev": 0,
"m15_rate": 5.71319603390943e-34,
"m1_rate": 2.964393875e-314,
"m5_rate": 6.495641728940849e-95,
"mean_rate": 0.0028346848490537267,
"duration_units": "seconds",
"rate_units": "calls/second"
}`, you could see indeed there ever be some traffic through the system.
I don't understand ExponentiallyDecayingReservoir's behavior well, could you help me explain how this could happen, and why? Should I use another Reservoir to avoid this?

**Comment by mhietajarvi** [comment]
I was using a go port of this library, and encountered similar issue where histogram data from expdecay sample would turn to garbage after 12 minutes or so.

It seems to me that the rescale threshold is by default set to too large value (one hour), when it should be less than ln(max float64 value)/alpha seconds.
