### ISSUE TITLE
Meters with SlidingTimeWindowArrayReservoir

### ISSUE THREAD

**Issue by melhindi** [dropwizard/metrics#1452]
Hi,

is it possible to initialise a Meter with a SlidingTimeWindowArrayReservoir?
I want to measure the moving average throughput within e.g. the last 10 seconds (not 1, 5 and 15min as is the default behaviour).
I tried to do this using a Timer (which can be initialised with a SlidingTimeWindowArrayReservoir), however, while the latency metrics are correct the rate metrics are not reported correctly, ie, when there are no requests coming in the latency is zero, but the reported (mean) rate is non zero, although there were no new requests in the last 10 seconds.

I assume this is due to Timers using Meters under the hood, which in turn use Exponentially Decaying Reservoirs internally.

Thanks in advance!

**Comment by storozhukBM** [comment]
Hi @melhindi,

You can use `Timer.getSnapshot()` method to fetch you histogram metrics. The snapshot contains all latency metrics, but you can also access `Snapshot.size()` value and in the case when you are using `SlidingTimeWindowArrayReservoir` it will return the exact count of measurements observed in the sliding window.

I hope it will help.
