### ISSUE TITLE
Conversions makes overly strong assumptions and are more confusing than beneficial

### ISSUE THREAD

**Issue by rasmusbergpalm** [dropwizard/metrics#1472]
For instance the Histogram implicitly assumes it's measuring a duration, which is a pretty strong assumption. Actually in your own example here https://metrics.dropwizard.io/4.0.0/getting-started.html#Histograms it's measuring bytes, which the conversion to duration will then turn into... what exactly?

I think I'd prefer a solution that did not try to convert at all, and just logged/reported whatever you gave it. I think the conversions are more confusing than beneficial. If I want to measure something in MS now I have to know what the durationConversion is so that I can multiply with the inverse such that I can log in what I want.

**Comment by vladimir-bukhtoyarov** [comment]
Hello @rasmusbergpalm 

Could you point to concrete lines in the source code of [Histogram](https://github.com/dropwizard/metrics/blob/4.1-development/metrics-core/src/main/java/com/codahale/metrics/Histogram.java) or Reservior where you see assumptions about the nature of measured numbers? I do not see them at all.

**Comment by rasmusbergpalm** [comment]
I cannot. Maybe it's been fixed or I've been confused. Thanks! I'll close the issue.
