### ISSUE TITLE
LongAdder is not available in Android API Level 23 (6.0)

### ISSUE THREAD

**Issue by sibinlu** [dropwizard/metrics#1479]
in https://github.com/dropwizard/metrics/blob/4.1-development/metrics-core/src/main/java/com/codahale/metrics/EWMA.java the library is using LongAdder which is only available from Android API 24. https://developer.android.com/reference/java/util/concurrent/atomic/LongAdder

Could you replace LongAdder with BigInteger to fix the issue?
https://docs.oracle.com/javase/1.5.0/docs/api/java/math/BigInteger.html

**Comment by arteam** [comment]
The Metrics library targets back-end Java applications on JDK8+, where `LongAdder` exists. If can try to use `metrics` < 4.0.0 which should use `AtomicLong` instead.
