### ISSUE TITLE
The documentation page has a broken link to the javadocs (404)

### ISSUE THREAD

**Issue by ecerulm** [dropwizard/metrics#1485]
https://metrics.dropwizard.io/
redirects to 
https://metrics.dropwizard.io/4.1.0/

if I click on User Manual I get to 
https://metrics.dropwizard.io/4.1.0/manual/index.html

On that page if I click on Javadoc I get
https://metrics.dropwizard.io/4.1.0/apidocs/

which gives a 404.

I guess it should point to 
https://www.javadoc.io/doc/io.dropwizard.metrics/metrics-core/4.1.0

**Comment by apodkutin** [comment]
PR is here #1489
