### ISSUE TITLE
Looking for clarification on JmxReporter comment

### ISSUE THREAD

**Issue by markaalvaro** [dropwizard/metrics#1506]
There is a warning here:
https://metrics.dropwizard.io/4.1.0/manual/core.html#man-core-reporters-jmx
that says 

> We don’t recommend that you try to gather metrics from your production environment. JMX’s RPC API is fragile and bonkers. For development purposes and browsing, though, it can be very useful.

Is this implying the JmxReporter isn't ready for production use, or it's the opinion of the metrics team that JMX itself or metrics in general shouldn't be used in production?

**Comment by joschi** [comment]
@markaalvaro It's the opinion of the original author of the Dropwizard Metrics library:
https://github.com/dropwizard/metrics/blame/eeac39ba4daa664f00f63a4f10bcdba8a87798bd/docs/source/manual/core.rst#L356

I would agree with him that JMX might not be the most suited protocol go gather metrics from an application nowadays, given that it's specific to Java and good alternatives for fetching metrics exist.
