### ISSUE TITLE
HttpClientMetricNameStrategy should also have PATH_AND_METHOD

### ISSUE THREAD

**Issue by shashank-babu** [dropwizard/metrics#1529]
**Problem:**
`com.codahale.metrics.httpclient.HttpClientMetricNameStrategies` should also provide `PATH_AND_METHOD` because most of the time we are interested only in path information.

Currently, to get path metrics we use `QUERYLESS_URL_AND_METHOD`. This is not a good practice because endpoints change frequently. Suppose if we have dashboards, alerting system or other dependents in place, we need to change all of them with new metric names each time endpoint changes, it will be really painful.

**Solution**
we need something like this
```
public static final HttpClientMetricNameStrategy PATH_AND_METHOD =
            (name, request) -> {
                final URIBuilder url = new URIBuilder(requestURI(request));
                return name(HttpClient.class,
                        name,
                        url.getPath(),
                        methodNameString(request));
            };
```

**Comment by joschi** [comment]
@shashank-babu Thanks for opening this issue.

> we need something like this
> 
> ```java
> public static final HttpClientMetricNameStrategy PATH_AND_METHOD =
>             (name, request) -> {
>                 final URIBuilder url = new URIBuilder(requestURI(request));
>                 return name(HttpClient.class,
>                         name,
>                         url.getPath(),
>                         methodNameString(request));
>             };
> 
> ```

Is there anything preventing you in Dropwizard Metrics 4.1.x from defining this very `HttpClientMetricNameStrategy` in your own code and use it in `InstrumentedHttpClients.createDefault(MetricRegistry, HttpClientMetricNameStrategy)` or `InstrumentedHttpClients.custom(MetricRegistry, HttpClientMetricNameStrategy)`?

**Comment by shashank-babu** [comment]
@joschi Thanks for acknowledging.

Currently, we are doing the same, defining `HttpClientMetricNameStrategy` in our own code.
I personally felt that this should be supported by **dropwizard-metrics**, as this is the most common use case.

**Comment by joschi** [comment]
@shashank-babu Care to open a pull request for adding this preconfigured `HttpClientMetricNameStrategy`?

**Comment by shashank-babu** [comment]
@joschi Sure will do that.

**Comment by shashank-babu** [comment]
@joschi find the PR.
https://github.com/dropwizard/metrics/pull/1578
