### ISSUE TITLE
Instrument ThreadPoolExecutor and ForkJoinPool

### ISSUE THREAD

**Issue by pkwarren** [dropwizard/metrics#1535]
The current instrumentation for ExecutorService doesn't expose several useful properties of subclasses which can be helpful when determining how to properly size an executor. The current instrumentation exposes the following:

* Meter: submitted, completed
* Counter: running
* Timer: idle, duration

Micrometer exposes quite a few additional properties of both ThreadPoolExecutor and ForkJoinPool: https://micrometer.io/docs/ref/jvm. It would be helpful to expose these in addition to the current metrics (in particular, the gauges for the number of threads, size of queued tasks, etc.)

**Comment by joschi** [comment]
@pkwarren I think this makes sense and would be a nice addition. 👍

Would you be able to provide a PR for this for Dropwizard Metrics 4.2.x?

**Comment by pkwarren** [comment]
Yep - I've been meaning to raise a PR to add this. Hope to get to it shortly.

**Comment by joschi** [comment]
@pkwarren Did you get any chance to start working on this?

**Comment by pkwarren** [comment]
@joschi - No I haven't. I'm not currently using DW at work and haven't had as much time as before for OSS work.

**Comment by joschi** [comment]
Closed via https://github.com/dropwizard/metrics/pull/1928
