### ISSUE TITLE
InstrumentedExecutorService does not unregister metrics, nor expose a way to do so

### ISSUE THREAD

**Issue by Trinition** [dropwizard/metrics#1552]
InstrumentedExecutorService registers several metrics in its constructor, but they are never removed.  It is debatable whether `shutdown`/`shutdownNow` would be appropriate to hook into to unregister.  If it is not, then it would be up to the user of InstrumentedExecutorService to unregister them; however, doing so requires the caller to know the internals of InstrumentedExecutorService because it does not expose it's metrics.

I propose either exposing some sort of `unregister` method, or exposing the metrics/metric-names themselves.

**Comment by Trinition** [comment]
My work-around has been to explicitly remote the metrics I _know_ the InstrumentedExecutorService sets up in my own tear down method.

Example setup:
```new InstrumentedExecutorService(pool, Metrics.registry, name)```

Example teardown:
```    Metrics.registry.remove(MetricRegistry.name(name, "queued"))
    Metrics.registry.remove(MetricRegistry.name(name, "submitted"))
    Metrics.registry.remove(MetricRegistry.name(name, "running"))
    Metrics.registry.remove(MetricRegistry.name(name, "completed"))
    Metrics.registry.remove(MetricRegistry.name(name, "idle"))
    Metrics.registry.remove(MetricRegistry.name(name, "duration"))
```

**Comment by joschi** [comment]
@Trinition Could you please describe your use case for unregistering these metrics?

**Comment by Trinition** [comment]
Sure!

I have a system with various components that are started or stopped during it's normal course of operation. Some of those components are dynamic, and some use thread pools which I want to instrument.  So when such a component starts, I want it initializes an InstrumentedExecutorService named with the component's name, and I start getting metrics for it while that component is active.  When the component is done, it shuts down and ends its threadpool. But the metrics live on because InstrumentedExecutorService does not remove the metrics it had registered. As more components start and then stop, the registry becomes full of "dead" metrics for thread pools that won't come back (because they're dynamically named, even if the same type of component is activated again, the metrics have different names).

**Comment by Trinition** [comment]
I'm not aware of any progress on this.  It's still a (non-critical) issue for me.

**Comment by gitseti** [comment]
Any update on this? :) 

I have a use case where I have to re-initialize a `InstrumentedExecutorService` with the same name and MetricRegistry. 
With the newer updates of metrics (#1928), I see that there is now the `register` method used in the `InstrumentedExecutorService` , which makes my application throw the  following expection:
```
java.lang.IllegalArgumentException: A metric named my-metric already exists
```

For my use case it would actually be enough to reuse existing metrics by, for example, replacing 
```java
registry.register(MetricRegistry.name(name, "pool.size"), (Gauge<Integer>) executor::getPoolSize);
``` 
with
```java
final MetricRegistry.MetricSupplier<Gauge<Integer>> supplier = () -> executor::getPoolSize;
registry.gauge(MetricRegistry.name(name, "pool.size"), supplier);
``` 
Also, this seems to be consistent with the previous behavior, which reused the created metrics:
```java 
this.submitted = registry.meter(MetricRegistry.name(name, "submitted"));
this.running = registry.counter(MetricRegistry.name(name, "running"));
this.completed = registry.meter(MetricRegistry.name(name, "completed"));
this.idle = registry.timer(MetricRegistry.name(name, "idle"));
this.duration = registry.timer(MetricRegistry.name(name, "duration"));
```

I would be willing to create a PR for all metrics, if this suggestion would be approved :)

**Comment by mixermt** [comment]
@gitseti not sure I understand the status of the fix you've merged long time ago. 
Did it reach actually some released version ? 

If not, is there any workaround for this ? 
Trying to upgrade, and have too many duplicate registration cases of `InstrumentedExecutorService`
