### ISSUE TITLE
CachedGauge is not thread-safe

### ISSUE THREAD

**Issue by Ethanlm** [dropwizard/metrics#1565]
(I am not sure if `CachedGauge` is meant to be thread-safe. But the `shouldLoad` method indicates the intention of making it thread-safe.)

In https://github.com/dropwizard/metrics/blob/4.1-development/metrics-core/src/main/java/com/codahale/metrics/CachedGauge.java#L48-L54

```
    @Override
    public T getValue() {
        if (shouldLoad()) {
            this.value = loadValue();
        }
        return value;
    }
```
Imaging `thread-1` and `thread-2` invoking `getValue()` at the same time at very beginning and assume `thread-1` arrives a little bit earlier than thread-2. So according to the `shouldLoad` method, it returns `true` for  `thread-1` and `false` for `thread-2`.

Now `thread-1` is on ` this.value = loadValue();` and `thread-1` is on `return value;`.

The result for `thread-2` will be different depending on which one finishes first.  If `thread-1` finishes `this.value = loadValue();` first, the value returned for `thread-2` is the new value, which is correct. 
But if `return value` finishes for `thread-2` first, then `thread-2` gets the original value (which is `null`) and can cause NPE.  This is what we are seeing in `CachedThreadStatesGaugeSet`. And this is wrong because `thread-2` should get the new value (remember `shouldLoad` returned `false` for `thread-2`)

An example of using `CachedThreadStatesGaugeSet` on multiple threads:
```
Exception in thread "Thread-1" java.lang.NullPointerException
	at com.codahale.metrics.jvm.ThreadStatesGaugeSet.getThreadCount(ThreadStatesGaugeSet.java:95)
	at com.codahale.metrics.jvm.ThreadStatesGaugeSet.access$000(ThreadStatesGaugeSet.java:20)
	at com.codahale.metrics.jvm.ThreadStatesGaugeSet$1.getValue(ThreadStatesGaugeSet.java:56)
```

**Comment by the-thing** [comment]
Hi @Ethanlm,

The issue has been reported before https://github.com/dropwizard/metrics/issues/711. I created a pull request.

**Comment by Ethanlm** [comment]
Thanks @the-thing
