### ISSUE TITLE
PeakThreadCount information should be added in ThreadStatesGaugeSet

### ISSUE THREAD

**Issue by SubhamSinghal** [dropwizard/metrics#1600]
ThreadStatesGaugeSet should include PeakThreadCount information as well.

Currently we have only following metrics in ThreadStateGauseSet.
 ```
gauges.put("count", (Gauge<Integer>) threads::getThreadCount);
        gauges.put("daemon.count", (Gauge<Integer>) threads::getDaemonThreadCount);
        gauges.put("deadlock.count", (Gauge<Integer>) () -> deadlockDetector.getDeadlockedThreads().size());
        gauges.put("deadlocks", (Gauge<Set<String>>) deadlockDetector::getDeadlockedThreads);
```

**Comment by joschi** [comment]
@SubhamSinghal `ThreadStateGaugeSet` currently doesn't have any internal state. If we started recording the min/max/mean/quantiles of the number of threads, daemon threads, and number of deadlocks, we'd have to maintain this state information.

Typically, the metrics exposed by Dropwizard Metrics are shipped to third party systems such as Prometheus or Graphite which support aggregations and other operations on the recorded data, so you can get the information there.

**Comment by SubhamSinghal** [comment]
ThreadMXBean does provide peakThreadCount information right. We just have to add one more gauge there.
`gauges.put("peakThreadCount", (Gauge<Integer>) threads::getPeakThreadCount);`

**Comment by joschi** [comment]
Ah, now I see. Thanks for the explanation!
