### ISSUE TITLE
Support for older versions

### ISSUE THREAD

**Issue by jeffkbkim** [dropwizard/metrics#1618]
Hi,

I'm submitting an issue as people aren't active in the mailing list group. 

The readme shows support for versions 3.1.x and up. Does this mean there is no support for older versions (i.e. 2.2.0)? Thanks!

**Comment by joschi** [comment]
Currently only Metrics 4.1.x is actively supported and Metrics 4.2.x is in development.
Metrics 5.0.x is on ice for the time being.

Versions older than Metrics 4.1.x are not supported anymore.

**Comment by joschi** [comment]
@jeffkbkim Thanks for bringing this up!

I've updated the README in our default branch to make more clear which versions of Dropwizard Metrics are still actively maintained and which are not.

**Comment by jeffkbkim** [comment]
@joschi thanks for the clarification!

**Comment by jeffkbkim** [comment]
@joschi is there any supported version that's backwards compatible with `2.2.0`?

**Comment by joschi** [comment]
@jeffkbkim Metrics 2.2.0 was still using the `com.yammer.metrics` group ID in Maven and the `com.yammer.metrics` package for its Java code when it was released 8 years ago in 2012: https://github.com/dropwizard/metrics/tree/v2.2.0

Unless somebody else forked off from that version and maintained it until now, there's no maintained version of Metrics which is backward-compatible with this.
