### ISSUE TITLE
io.dropwizard.metrics:metrics-core package lost support for the JPMS between version 4.1.10 and 4.1.11

### ISSUE THREAD

**Issue by myurchen** [dropwizard/metrics#1625]
In io.dropwizard.metrics:metrics-core version 4.1.11 JPMS support was broken.
Specifically, this line is now missing from META-INF/MANIFEST.MF:
 Automatic-Module-Name: com.codahale.metrics

**Comment by joschi** [comment]
@myurchen Thanks for reporting this!

It looks like this was introduced with #1617 and `maven-bundle-plugin:5.1.1` removes this manifest attribute.

**Comment by njdoyle** [comment]
The change of module name breaks any dependants that used the old module name. If this package follows SEMVER, this change in module name would necessitate a full major version bump as it is not backwards compatible.

**Comment by joschi** [comment]
@njdoyle You're right. I'll publish a patch release to fix that.
