### ISSUE TITLE
Use separator property for CSV-header

### ISSUE THREAD

**Issue by DarkJenum** [dropwizard/metrics#1670]
Heder of generated csv's doen't use separator-property:

`builder.withSeparator(";")`

result:
`t,count,mean_rate,m1_rate,m5_rate,m15_rate,rate_unit`
`1602241286;820;86.729095;18.000000;18.000000;18.000000;events/second`
`1602241296;2610;134.256393;41.893171;23.093552;19.716253;events/second`
`1602241306;4419;150.062515;62.712585;28.158275;21.460740;events/second`

**Comment by joschi** [comment]
@DarkJenum Great find, thanks for reporting this and even providing a PR! ❤️
