### ISSUE TITLE
Generify MetricRegistry.gauge()

### ISSUE THREAD

**Issue by klitoskyriacou** [dropwizard/metrics#1693]
Typical usage of the `gauge` method is as follows:

    class MyCustomGauge implements Gauge<Long> { ... }
    ...
    MyCustomGauge myGauge = (MyCustomGauge) metrics.gauge("name", MyCustomGauge::new);

It would be great if the cast were unnecessary so that we could drop the repeated class name:

    MyCustomGauge myGauge = metrics.gauge("name", MyCustomGauge::new);

This could be made possible if the signature of `gauge` were:

    public <T extends Gauge<?>> T gauge​(String name, MetricRegistry.MetricSupplier<T> supplier)

The added advantage of this is that with newer versions of Java, we can then use the following syntax:

    var myGauge = metrics.gauge("name", MyCustomGauge::new);

Where `myGauge` would have the required compile-time type, and no repetition at all (DRY principle).

**Comment by joschi** [comment]
@klitoskyriacou @jeff303 I think this has been addressed in https://github.com/dropwizard/metrics/pull/1607.
Could you please check and either close https://github.com/dropwizard/metrics/pull/1695 or adapt it to the latest `release/4.2.x` branch? Thanks. 😃

**Comment by klitoskyriacou** [comment]
@joschi thanks, I see that one of the commits in the PR you mention does in fact address this issue.
