### ISSUE TITLE
Limit cached metrics

### ISSUE THREAD

**Issue by chokdee** [dropwizard/metrics#1705]
Hi,

we are using the great framework together with an influx db.
If the influx db isn't available we are facing the problem, that the report will send all collected metrics in one request. And this causes an out of memory error.

Is there the possibility to limit the collected metrics?

Thanks 
juergen

**Comment by joschi** [comment]
@chokdee Which reporter are you using specifically?

**Comment by chokdee** [comment]
InfluxdbReporter from https://github.com/davidB/metrics-influxdb

**Comment by joschi** [comment]
@chokdee Since reporters can control how exactly data is sent to the receiver, it would probably make sense to file a feature request at https://github.com/davidB/metrics-influxdb.

**Comment by chokdee** [comment]
Hm, I think there should be a limit in the metrics core too. If I understand the code, the MetricsRegistry will add the values in a Map. What will happen when you add too many values in the map for the configured memory?

**Comment by joschi** [comment]
@chokdee Could you please provide some more details about your setup and where exactly the `OutOfMemoryError` occurs?

If possible, a minimal project to reproduce the issue would be great.
