### ISSUE TITLE
Reconcile `5.0-development` and `release/5.0.x`

### ISSUE THREAD

**Issue by joschi** [dropwizard/metrics#1735]
The `5.0-development` and `release/5.0.x` have diverged and need to be reconciled (by merging `5.0-development` into `release/5.0.x`)

In the future, only the `release/5.0.x` branch should be used.

**Comment by hdost** [comment]
Of the two which is considered to be more up to date?

**Comment by joschi** [comment]
@hdost `5.0-development` has more up-to-date commits right now.

**Comment by joschi** [comment]
I've tried my best to get the changes from `5.0-development` into `release/5.0.x` in https://github.com/dropwizard/metrics/commit/4b1e128544fe8d2d082355b4abd3e28c32ba6d56.

@arteam Please check if the merge commit contains all relevant changes.

**Comment by arteam** [comment]
LGTM!

**Comment by joschi** [comment]
Closed via https://github.com/dropwizard/metrics/commit/4b1e128544fe8d2d082355b4abd3e28c32ba6d56 and https://github.com/dropwizard/metrics/commit/88ddc44b89de61cfa28b3add8cc044d5a02f91f7.

**Comment by hdost** [comment]
Should `5.0-development` be deleted?
