### ISSUE TITLE
Dropwizard Metric 5 and JMX reporter

### ISSUE THREAD

**Issue by maneeshbhunwal123** [dropwizard/metrics#1753]
[Dropwizard metric][1] added support for adding tags while adding a metric value in version 5.x. This is a good feature, But I don't see JMXReporter as there was one for older version 3.x. 

For Metric 4.x it was moved to a different project ([source][2]).

I have few questions

1. Current state of 5.0.x is showing as on [pause](https://i.stack.imgur.com/3X5XH.png). Is it a good idea to use dropwizard metreic 5.x?

2. How can we integrate with JMXReporter with metric 5.x?

3. Is there any other workaround for using tags?

**Comment by joschi** [comment]
> But I don't see JMXReporter as there was one for older version 3.x.

`JmxReporter` in:
* Dropwizard Metrics 4.1.x: https://github.com/dropwizard/metrics/blob/v4.1.17/metrics-jmx/src/main/java/com/codahale/metrics/jmx/JmxReporter.java
* Dropwizard Metrics 4.2.x: https://github.com/dropwizard/metrics/blob/v4.2.0-beta.1/metrics-jmx/src/main/java/com/codahale/metrics/jmx/JmxReporter.java
* Dropwizard Metrics 5.0.x: https://github.com/dropwizard/metrics/blob/v5.0.0-rc4/metrics-jmx/src/main/java/io/dropwizard/metrics5/jmx/JmxReporter.java

**Comment by maneeshbhunwal123** [comment]
thanks @joschi , can you please answer
```Current state of 5.0.x is showing as on pause. Is it a good idea to use dropwizard metreic 5.x?```
as well?

**Comment by joschi** [comment]
@maneeshbhunwal123 Currently only @arteam is putting any work into the 5.0.x branch.

Maybe he could give some insights?

See also the [5.0.0 milestone](https://github.com/dropwizard/metrics/milestone/22).
