### ISSUE TITLE
Allow for fine-grained filtering of metrics

### ISSUE THREAD

**Issue by codahale** [dropwizard/metrics#178]
Currently reporters' outputs can be filtered by `MetricName`, but it would be preferable to have more fine-grained filters than that, ideally down to the measurement level.

Pull request #91 by @cburroughs attempted to address this, but it's still an open issue.

**Comment by ryantenney** [comment]
Lots of demand for this, will aim to get this in v4.

**Comment by ryantenney** [comment]
Going to follow the approach outlined in #837

**Comment by bentatham** [comment]
Great!  So I'll throw away the PR #836 in favour of this approach?

**Comment by ryantenney** [comment]
@bentatham Sounds good.

**Comment by bentatham** [comment]
Is this still planned for 4.0.0?  My idea in #837 is targeted for 5.0.0.  Would love to have something in place.  

I'm happy to attempt a PR, if I have hope it will be looked at for 4.0.0.
