### ISSUE TITLE
Time frame for 4.2 release?

### ISSUE THREAD

**Issue by tsegismont** [dropwizard/metrics#1817]
Sorry if this is the wrong place to ask questions.

I am a Vert.x core team member. We plan to upgrade our dependency to Dropwizard Metrics in Vert.x 4.1 (development starting now).

Is there a planned date for the release of Dropwizard 4.2? If the time frame is not too long, I can evaluate beta3, report any issue here and upgrade to 4.2.0 when it's ready.

Otherwise, we'll go with Dropwizard 4.1.

Thank you!

**Comment by joschi** [comment]
> If the time frame is not too long, I can evaluate beta3, report any issue here and upgrade to 4.2.0 when it's ready.

Soon™. There are a few breaking

**Comment by joschi** [comment]
> If the time frame is not too long, I can evaluate beta3, report any issue here and upgrade to 4.2.0 when it's ready.

@tsegismont Thanks for asking!

Dropwizard Metrics 4.2.x should be out soon™. There are a few breaking changes/additions which we'd like to get in, such as the histograms with `double` values.

I think the 4.2.0 milestone gives a good overview: https://github.com/dropwizard/metrics/milestone/27

So I would recommend to start with Dropwizard Metrics 4.2.0-beta.3 and then update to the GA version once it has been released. 😃

**Comment by jg167** [comment]
Peronsally, I'd love to get a beta4, but perhaps that is watiing on the DoubleHIstorgram that is not yet approved.

**Comment by tsegismont** [comment]
@joschi just wanted to let you know that the Vert.x Dropwizard Metrics module test suite passed without any issue when upgrading to 4.2.0-beta.3

**Comment by tsegismont** [comment]
Hi @joschi ! We'll release Vert.x 4.1 beta1 this week. Do you have a better idea of when Dropwizard 4.2 can be released?

**Comment by joschi** [comment]
@tsegismont [Dropwizard Metrics 4.2.0-rc.1](https://github.com/dropwizard/metrics/releases/tag/v4.2.0-rc.1) has been release 9 days ago.

When there are no regressions reported 2 weeks after the release of this release candidate (i. e. end of this week), then we'll release it as Dropwizard Metrics 4.2.0.

**Comment by tsegismont** [comment]
@joschi thanks. Great news! You mean `4.2.0-rc.2`, right?

FYI, Vert.x Dropwizard Metrics tests suite passes with `4.2.0-rc.2`.

**Comment by joschi** [comment]
> @joschi thanks. Great news! You mean `4.2.0-rc.2`, right?

No, I meant `4.2.0-rc.1`. I've published `4.2.0-rc.2` right after. 😂 

Anyway, the plan is still to release Dropwizard Metrics 4.2.0 end of the week/during the weekend.

**Comment by joschi** [comment]
@tsegismont Dropwizard Metrics 4.2.0 has been released: https://github.com/dropwizard/metrics/releases/tag/v4.2.0

**Comment by tsegismont** [comment]
Congrats on the release!
