### ISSUE TITLE
Will the new SettableGauge type (in 4.2.x)  be returned from getGauges()?

### ISSUE THREAD

**Issue by jg167** [dropwizard/metrics#1826]
Just  checking since I did not see this in the tests added for #1811 
The tests do not (as far as I can see) call the new gauge( String ) convience function to create or return an existing SettableGauge. 
Will this function retturn a regular gauge if one exists using this name?

**Comment by joschi** [comment]
All gauges with type `SettableGauge<T>` are handled as regular gauges and will also be returned in the map returned by [`MetricRegistry#getGauges()`](https://www.javadoc.io/static/io.dropwizard.metrics/metrics-core/4.2.0-beta.3/com/codahale/metrics/MetricRegistry.html#getGauges()).

> The tests do not (as far as I can see) call the new gauge( String ) convience function to create or return an existing SettableGauge.

https://github.com/dropwizard/metrics/blob/1f9caec13467843bbe2ecd39c981610d584fd424/metrics-core/src/test/java/com/codahale/metrics/MetricRegistryTest.java#L218-L228
https://github.com/dropwizard/metrics/blob/1f9caec13467843bbe2ecd39c981610d584fd424/metrics-core/src/test/java/com/codahale/metrics/MetricRegistryTest.java#L241-L250

**Comment by jg167** [comment]
thanks!
