### ISSUE TITLE
import com.codahale.metrics.MetricRegistry; does not include settalbeGauge 

### ISSUE THREAD

**Issue by jg167** [dropwizard/metrics#1866]
SInce settableGauges are an extesion what is the best practise wrt imports to use the new types and functions?

**Comment by joschi** [comment]
Please see the Javadoc for [`MetricRegistry#gauge(java.lang.String)`](https://www.javadoc.io/static/io.dropwizard.metrics/metrics-core/4.2.0-beta.4/com/codahale/metrics/MetricRegistry.html#gauge(java.lang.String)) and the respective test cases for usage examples:
https://github.com/dropwizard/metrics/blob/v4.2.0-beta.4/metrics-core/src/test/java/com/codahale/metrics/MetricRegistryTest.java#L218-L275

**Comment by jg167** [comment]
The tests do not include the use of the metricsRegistery.settableGauge(String) convience fucntion.  which is what isn't delcared by importing com.codahale.metics.MetircisRegister';  as the other (counter(), gauge() ) functions are.

**Comment by joschi** [comment]
> The tests do not include the use of the metricsRegistery.settableGauge(String) convience fucntion.

That's because there is no method named `MetricRegistry#settableGauge()`. 😉 

I already pointed you at the respective method in https://github.com/dropwizard/metrics/issues/1866#issuecomment-819478590.

**Comment by jg167** [comment]
ok, (I thought having the convienence function was part of this).  having to do
<SettableGuage> sg = metricsRegister.gauge(...);
sg.setValue(...); 

for any code that wants to use setValue() is a bit incovienent compared to just mr.counter(...).inc() for eacmple, but
workable.
