### ISSUE TITLE
Since 4.1.23, metrics-bom manages dependencies that are not part of Dropwizard

### ISSUE THREAD

**Issue by wilkinsona** [dropwizard/metrics#2042]
The changes made in https://github.com/dropwizard/metrics/commit/f069a88a24f141e04e181270f8dab1b83268aeb4 have resulted in `metrics-bom` managing non-Dropwizard dependencies. We noticed the problem when trying to upgrade Spring Boot to Dropwizard 4.1.23 from 4.1.22. It resulted in AssertJ jumping from 3.19.0 to 3.20.1.

Can `metrics-bom` please be restored to its previous state so that importing it only manages the versions of Dropwizard's own modules?

**Comment by joschi** [comment]
@wilkinsona Thanks for reporting this!

Could you please elaborate on the issue? `io.dropwizard.metrics:metrics-bom:4.1.23` doesn't list any dependency in its `dependencyManagement` section which is not part of Dropwizard Metrics 4.1.23 itself and the commit you've linked to (#1967) only explicitly added the respective dependencies to the non-BOM sub-modules.

https://github.com/dropwizard/metrics/blob/v4.1.23/metrics-bom/pom.xml

```diff
diff --git v4.1.22/metrics-bom/pom.xml v4.1.23/metrics-bom/pom.xml
index f63fb6de..be1a3454 100644
--- metrics-bom/pom.xml
+++ metrics-bom/pom.xml
@@ -5,7 +5,7 @@
     <parent>
         <groupId>io.dropwizard.metrics</groupId>
         <artifactId>metrics-parent</artifactId>
-        <version>4.1.22</version>
+        <version>4.1.23</version>
     </parent>

     <artifactId>metrics-bom</artifactId>
```

**Comment by joschi** [comment]
Ah, it looks like the change came in via `metrics-parent`.

https://github.com/dropwizard/metrics/commit/f069a88a24f141e04e181270f8dab1b83268aeb4#diff-9c5fb3d1b7e3b0f54bc5c4182965c4fe1f9023d449017cece3005d3f90e8e4d8

**Comment by wilkinsona** [comment]
Yeah, that's right. It's inherited via `metrics-parent`.

**Comment by joschi** [comment]
@wilkinsona @snicoll Dropwizard Metrics 4.1.24 and 4.2.2 should be available on Maven Central soon.

**Comment by wilkinsona** [comment]
Thank you!

**Comment by snicoll** [comment]
Thanks @joschi, Spring Boot `2.4.x` and `2.5.x` have upgraded to that version.
