### ISSUE TITLE
How to get current tps ?

### ISSUE THREAD

**Issue by jjz921024** [dropwizard/metrics#2100]
Hi, all

There are any way  to get `current tps` of my running system by metrics?

I use Meter or Time,  but the `mean rate` is not my expected.

**Comment by joschi** [comment]
If you want to get the current value of something at the exact moment in time, then you'll have to use a gauge. All other metric types (except for gauges and counters) are in some way pre-aggregated.

See https://metrics.dropwizard.io/4.1.22/manual/core.html for details.

**Comment by jjz921024** [comment]
got it，thank for you reply @joschi
