### ISSUE TITLE
Adding annotation like @Timed but for Counter only. 

### ISSUE THREAD

**Issue by BeniaminK** [dropwizard/metrics#2119]
Hi, I wanted to create an annotation like `@Timed` however I cannot find a place, where I should insert the logic of this annotation. Could you help me in this? Can I do it outside of the dropwizard-metrics project, i.e. can I create this annotation in my project and implement a logic there?

**Comment by joschi** [comment]
> can I create this annotation in my project and implement a logic there?

Yes, you can implement this yourself for your project. Take a look how [`InstrumentedResourceMethodApplicationListener`](https://github.com/dropwizard/metrics/blob/v4.2.3/metrics-jersey2/src/main/java/com/codahale/metrics/jersey2/InstrumentedResourceMethodApplicationListener.java) in `metrics-jersey2` or `metrics-jersey3` are implemented.
