### ISSUE TITLE
Vulnerability found in metrics-core-3.2.2.jar

### ISSUE THREAD

**Issue by shyam94** [dropwizard/metrics#2414]
Hi,

Veracode scan reported Medium Vulnerabilities found in **metrics-core-3.2.2.jar.**

1. **File:** com/codahale/metrics/ThreadLocalRandom.java
    **Line no:** 98, 155, 170, 304, 365, 382
    **CWE ID:** 331
    **Reason:** Standard random number generators do not provide a sufficient amount of entropy when used for security purposes.
                 Attackers can brute force the output of pseudorandom number generators such as rand(). (Check CWE for more details).

Please let me know if this can be considered false Positive or needs to be addressed.

Thanks,
Shyam Joshi

**Comment by joschi** [comment]
@shyam94 Dropwizard Metrics 3.x has been out of support for a long time.

Please upgrade to a version of Dropwizard Metrics which is still supported:
https://github.com/dropwizard/metrics/security/policy
