### ISSUE TITLE
Missing closing parenthesis in metrics.dropwizard.io manual

### ISSUE THREAD

**Issue by shaskumar** [dropwizard/metrics#2529]
While I was reading through the metrics [documents](https://metrics.dropwizard.io/4.2.0/manual/core.html#man-core-histograms), I found out that there is a missing closing parenthesis in the histogram section. 

```diff
-final Histogram resultCounts = registry.histogram(name(ProductDAO.class, "result-counts");
+final Histogram resultCounts = registry.histogram(name(ProductDAO.class, "result-counts"));
```

**Comment by joschi** [comment]
@shaskumar Thanks for reporting this! We've fixed the documentation. 😄
