### ISSUE TITLE
InstrumentedExecutorService does not remove registered gauges after shutdown

### ISSUE THREAD

**Issue by nicu-da** [dropwizard/metrics#2920]
Similar to https://github.com/dropwizard/metrics/issues/1684.

As the gauges are not removed, once we shutdown the executor service and try to start again with the same name, the executor service can no longer be started.

**Comment by joschi** [comment]
Do you have this issue only in tests or also in production?

If the latter, could you please describe the use case?

**Comment by nicu-da** [comment]
The issue would also happen in production. 
The use-case is caused by having multiple components started within the same java process. As part of specific failure handlers a component can be restarted. As the component itself manages the executor services it uses, this also entails stopping the current execution services and starting them again, using the same name. This in turn is impossible to do because the gauges added as part of https://github.com/dropwizard/metrics/pull/1928 are never removed when the executor service is stopped.
