### ISSUE TITLE
XmlBeanDefinitionStoreException -Premature end of file.

### ISSUE THREAD

**Issue by rajchemmeri** [dropwizard/metrics#322]
Trying to test  metrics spring intergration, Getting following exception,

<beans xmlns="http://www.springframework.org/schema/beans"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:metrics="http://www.yammer.com/schema/metrics"
    xsi:schemaLocation="http://www.springframework.org/schema/beans 
    http://www.springframework.org/schema/beans/spring-beans-3.1.xsd 
    http://www.yammer.com/schema/metrics 
    http://www.yammer.com/schema/metrics/metrics.xsd">

```
<metrics:metrics-registry id="metrics" />
<metrics:health-check-registry id="health" />

<metrics:annotation-driven metrics-registry="metrics"
    health-check-registry="health" />

<metrics:jmx-reporter id="metricsJmxReporter"
    metrics-registry="metrics" />

<!-- other beans -->
```

</beans>

SEVERE: Context initialization failed
org.springframework.beans.factory.xml.XmlBeanDefinitionStoreException: Line 1 in XML document from ServletContext resource [/WEB-INF/spring-context.xml] is invalid; nested exception is org.xml.sax.SAXParseException: Premature end of file.
    at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.doLoadBeanDefinitions(XmlBeanDefinitionReader.java:396)
    at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.loadBeanDefinitions(XmlBeanDefinitionReader.java:334)
    at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.loadBeanDefinitions(XmlBeanDefinitionReader.java:302)

is tFollowing schemas are missin

Please let me know if anyone have solution for this.

**Comment by shadowcole** [comment]
it's working change the 
http://www.springframework.org/schema/context/spring-context-3.1.xsd
to
http://www.springframework.org/schema/context http://www.springframework.org/schema/context/spring-context-3.1.xsd
but  why ? could you tell me  about it . thank you very much
