### ISSUE TITLE
JFR reporter

### ISSUE THREAD

**Issue by hupfdule** [dropwizard/metrics#3253]
I have created a JFR (Java Flight Recorder) reporter: https://github.com/poiu-de/metrics-jfr

Java Flight Recorder is freely available with each JDK from version 11 onwards and is a sophisticated tool for analyzing runtime metrics of the JVM and a running application. 

It makes sense to support it as a backend for the dropwizard metrics library reports.

I would like to donate this library to the dropwizard metrics umbrella to become an “official” reporting backend. Is there any interest on your side in including it? What must be done for that to happen?

**Comment by joschi** [comment]
@hupfdule Thanks for reaching out about this!

As you probably have guessed from the long time it took to answer this issue, the Dropwizard Metrics project currently doesn't have a lot of active maintainers.

This is why I think it would make more sense to keep the JFR reporter as an independent project for now and feature it in our documentation accordingly.

As an alternative, we could adopt the module and you could join the ranks of maintainers of this project. 😉
