### ISSUE TITLE
Remove Striped64 and LongAdder when switching to Java 8

### ISSUE THREAD

**Issue by codahale** [dropwizard/metrics#375]
No real timeline on this, either.

(c.f. ffeed35b063d9be1f3d69ff7d1272612f95b60db)

**Comment by ikedahi** [comment]
I think you can replace UNSAFE with AtomicLongFieldUpdater for Cell's value, AtomcLong for Striped64's base, and AtomicBoolean (or AtomicInteger) for Striped64's busy.

**Comment by matlach** [comment]
Striped64 also hold a reference to ThreadLocal in its actual form.
If you have a look to the latest JDK8 implementation source code this has been removed.

I'm pretty sure this can lead to the same issue discussed in #742 .

**Comment by ikedahi** [comment]
I was surprised but I agree.

In order to avoid holding a specific class via Striped64, it might be fixed by making ThreadHashCode extend ThreadLocal&lt;int[]&gt; (with int[1]) instead of ThreadLocal&lt;HashCode&gt;, which is just used to hold a mutable hash for each thread.
