### ISSUE TITLE
HealthCheckServlet should not return 500 error code

### ISSUE THREAD

**Issue by jdubois** [dropwizard/metrics#484]
The HealthCheckServlet returns an HTTP 500 error code if any healthcheck is invalid, in the "doGet" method.

This is not a correct behavior, from the HttpServletResponse docs:

"Status code (500) indicating an error inside the HTTP server which prevented it from fulfilling the request."

If a healthcheck goes wrong, there isn't a problem inside the HTTP server, in fact the HealthCheckServlet correctly handled the request:
- The return code should be 200 (HTTP OK)
- This will make it possible to use correclty the HealthCheckServlet with some JS libraries like AngularJS (for AngularJS, if you have a 500 code, everything is wrong -> in my case only one of 3 healthchecks is wrong)

**Comment by alexander-suter** [comment]
What happens here?

Dropwizard should implement the HTTP Protocol in the correct way.
