### ISSUE TITLE
Add Elasticsearch Metrics Reporter to Third Party Libraries

### ISSUE THREAD

**Issue by Hocdoc** [dropwizard/metrics#524]
The [Elasticsearch Metrics Reporter](https://github.com/elasticsearch/elasticsearch-metrics-reporter-java) works like a charm for me. (Together with [Kibana](http://www.elasticsearch.org/overview/kibana/) you can display metrics really easy.)

It would be cool if you can add a Link in the [Third Party Libraries](http://metrics.codahale.com/manual/third-party/) documentation so other users can find this reporter as well.

**Comment by bshukhat** [comment]
We experience something like connection leakage: elasticsearch reporter opens multiple connections and they eventually overflow the server limits. Is it a known  issue?
