### ISSUE TITLE
Add support for Influx DB

### ISSUE THREAD

**Issue by felixbarny** [dropwizard/metrics#526]
Influx DB is a promising open-source distributed time series database, similar to graphite.

**Comment by darrenfu** [comment]
Will the next version of influxDB support InfluxDB? I saw the influxDB plugin code is already in dropwizard metrics master branch. Is it a stable version?

https://github.com/dropwizard/metrics/tree/master/metrics-influxdb/src/main/java/io/dropwizard/metrics/influxdb

**Comment by ryantenney** [comment]
Version 4 will have an influxdb reporter, however v4 won't be released for some time.

**Comment by bentatham** [comment]
@ryantenney @arteam Is the metrics-influxdb on master left out of 4.0-development on purpose, or just waiting for someone to copy it over?  If so, I can work on that...
