### ISSUE TITLE
Remove usage of sun.misc.Unsafe

### ISSUE THREAD

**Issue by derabbink** [dropwizard/metrics#539]
[`com.codahale.metrics.Striped64`](https://github.com/dropwizard/metrics/blob/master/metrics-core/src/main/java/com/codahale/metrics/Striped64.java) uses `sun.misc.Unsafe`. This is arguably a bad idea, for the following reasons:
1. `sun.misc.Unsafe` is undocumented, and therefore it [should not be used](http://stackoverflow.com/questions/16819234/sun-misc-unsafe-documentation#comment24246414_16819234).
2. Use of this class is not allowed in some sandboxes (e.g. [GAE](https://developers.google.com/appengine/docs/java/jrewhitelist)) which inhibits the use of depending classes (e.g. [`com.codahale.metrics.Timer`](https://github.com/dropwizard/metrics/blob/master/metrics-core/src/main/java/com/codahale/metrics/Timer.java)) on such platforms.

Feel free to bring forward any additional/counter arguments regarding the use of the `sun.misc.Unsafe` class.

Some time ago, @bartprokop [announced](https://github.com/dropwizard/metrics/pull/522#issuecomment-34460885) to be doing some work regarding this issue, but I thought I'd create an official issue for it anyway.

**Comment by ikedahi** [comment]
Java 7 will be used for a while, and you replace Unsafe in Striped64 and its internal class Cell with AtomicLongFieldUpdater and AtomicIntegerFieldUpdater, which are API classes in the Java standard library. You can also simply use AtomicLong and AtomicBoolean for Striped64's fields, but in that case LongAdder is also required to change.

**Comment by ikedahi** [comment]
The reason I'm concerned to fix the issue is, some projects using metrics would make an effort to switch logic by whether Unsafe is available or not, but updating the version of metrics would waste such an effort.

**Comment by ryantenney** [comment]
@ikedahi Fantastic suggestions, thank you! Working on it right now.

**Comment by ryantenney** [comment]
I've opened #875 which removes Unsafe in favor of AtomicLongFieldUpdater. Seems there is a ~14% performance hit.

**Comment by xmeng1** [comment]
+1
