### ISSUE TITLE
JMX Reporter wraps metric name in quotes

### ISSUE THREAD

**Issue by chrishuttonch** [dropwizard/metrics#559]
When using the JMXReporter, the name of the mBean is wrapped in quotes. This means that the object folder structure is just a single level. e.g.

"com.myorg.utils.internal.metric":type="MyOrgMetrics",name="id_available"

should be
com.myorg.utils.internal.metric:type=MyOrgMetrics,name=id_available

This is when registering a counter as metrics.counter(name(MyOrgMetrics.class, "id_available))

**Comment by vchekan** [comment]
I do not understand the explanation. How come forgetting to call .start() can cause double quotes?

**Comment by acemary4918** [comment]
JMXConnector jmxc = JMXConnectorFactory.connect(url, null);
MBeanServerConnection connection = jmxc.getMBeanServerConnection() connection code is right or wrong???  http://goo.gl/8aE6LK  |  http://goo.gl/UF3TDC
