### ISSUE TITLE
Graphite metrics should clean metrics names

### ISSUE THREAD

**Issue by JensRantil** [dropwizard/metrics#637]
Graphite does not allow metrics/sensors with names containing `'`, but Metrics happily submits them. This makes Graphite log a bunch of errors not being able to create the whisper files yada yada.

I see three different solutions to this:
 * Patch Metrics to not submit these metrics if they have the wrong naming, logging the metrics with the bad naming.
 * Automagically clean the sensor names (removing weird characters etc.) on submission to Graphite/carbon.
 * Keep things the way they are. Possibly adding a static helper method that can be used to clean sensor names from garbage. I am currently wrapping a bunch of sensor names in:

```java
public class MetricsUtils {

    /**
     * Clean graphite metrics names.
     * <p>
     * This was created because I was seeing a lot of stacktraces in Carbon log due to broken metric names.
     * 
     * @param proposal
     *            the proposed metrics' name.
     * @return cleaned metric's name
     */
    public static String cleanMetricName(String proposal) {
        return proposal.replace("'", "");
    }

}
```

Input welcome.

**Comment by JensRantil** [comment]
I just ran into a bug(?) triggered in Graphite when a metric had a parenthesis in it. Filename was `/whisper_root/package/path(something)/1_mean.wsp`. And I was plotting `aliasByNode(package.*.1_mean, 1)`. We are now internally stripping all parenthesis.

**Comment by felixbarny** [comment]
Graphite only supports alphanumeric characters + !#$%&"'*+-.:;<=>?@[\]^_`|~

**Comment by JensRantil** [comment]
@felixbarny Thanks! Do you have a reference for this list? As stated in the initial description, `'` is broke my Graphite.

**Comment by felixbarny** [comment]
I've found it somewhere in Graphite's source code. Can't remember where though...

**Comment by ryantenney** [comment]
I've gone with the following regex: [^a-z0-9!#\$%&"'\*\+\-.:;<=>\?@\[\]\^_`\|~]+

If there are no objections then I will be releasing 3.1.1 today.

**Comment by felixbarny** [comment]
I think the regex is missing the backslash character (`\\`)

**Comment by ryantenney** [comment]
So it is. Thanks!

**Comment by ryantenney** [comment]
Forward slash is legal then?

**Comment by felixbarny** [comment]
No, that's one of the most illegal chars ;)
But look at my sanitizeGraphiteMetricSegment method. I'm replacing it separately by `|` to that URLs don't look like :hankey: . For example `GET /index.html` -> `GET-|index:html` as supposed to `GETindexhtml` or `GET--index-html` but thats a matter of taste I guess...

**Comment by davidkarlsen** [comment]
Any movement on this?

**Comment by nickbabcock** [comment]
With #936 merged, should this be closed?

**Comment by ryantenney** [comment]
Yep looks like it.
