### ISSUE TITLE
Making HealthCheck.Result class extensible

### ISSUE THREAD

**Issue by hmpatel** [dropwizard/metrics#663]
I want to extend the Result class to enhance the health checks module for providing additional details. For e.g. I would add another health state in there - MAINTENANCE to indicate my servers are in the maintenance mode and also provider an optional placeholder Map to provide any additional details. Currently, Result class have only healthy and unhealthy states and furthermore, there is no way to provide additional info other than message. 

So, I tried to extend the HealthCheck class and add these details in there. However, due to absence of default no arg constructor in Result class, it's not possible to subclass Result.

So would like to propose this change or get the feedback.

Thanks!

**Comment by JonMR** [comment]
I'd also like to see this happen.  I'd be open to creating a PR as well.

In our case, the two states of healthy and unhealthy aren't enough.  For us, unhealthy means drop the service from the pool.  I'd like a third state that indicates there's an issue but the service is still able to handle traffic.

Specific example: We have a pool of memcache servers that the server talks to.  If it loses connectivity with one of those server, it's not a big deal, but something to be alerted and investigated.

I suppose we could write a parser for the output, but I'd rather not have to do that for each case.

**Comment by mjvandel** [comment]
+1 yes, please! It would make it possible to add JSON nodes to the response with extra details

**Comment by arnaud-deprez** [comment]
+1 too ! :-)

**Comment by zaphinath** [comment]
+1

**Comment by arnaud-deprez** [comment]
I think it would be possible to allow custom details by adding a Map<String,Object> as spring-boot-actuator does without breaking the API.
Like that, we wouldn't be forced to wait for version 4.0.0.
What do you think ?

**Comment by ryantenney** [comment]
Branch off 3.1-maintenance and I'd be happy to look at a pull request that adds that support for a 3.2 release.

**Comment by arnaud-deprez** [comment]
Okay, I'll take a look asap. Keep in touch.

**Comment by arnaud-deprez** [comment]
So if I get it right, master is for 4.0.0.
I suppose I need to base my code on 3.1-maintenance and make a pull request on a new branch. Correct ?

**Comment by dhay** [comment]
Our use case is this:  We use the health check framework to inform our on-call alerting.  As is, we basically have two states: UP or DOWN.  We wanted a third state, WARN, to indicate a problem with our application, but not worthy of waking someone up in the middle of the night.

So being able to have additional HealthCheck result types would be very helpful.

**Comment by cdeszaq** [comment]
This looks like changes for this was merged into 3.2.0 in https://github.com/dropwizard/metrics/pull/943, so is this issue complete?
