### ISSUE TITLE
Persistent connections in Graphite implementation are not robust enough

### ISSUE THREAD

**Issue by v-garki** [dropwizard/metrics#669]
Changes in https://github.com/dropwizard/metrics/commit/d42bc7f6c20fb33bf9cc6c31e9a649418e76cc01 (Graphite class) are not robust enough. Sockets can stuck in a bad state where isConnected() returns true but every action on the socket results in a "java.net.SocketException: Broken pipe" or something similar. This also includes close() since it is trying to flush first. Because of that the socket and writer are never closed and the next reporting round fails again and again...

**Comment by adamdecaf** [comment]
For what it's worth we're running into issues with keeping connections open. Mainly that we're having to mess around with timeouts to keep idle connections open (and running out of connections available). So we've forked this and reverted the changes to keep connections open and are testing them internally. 

That being said there's been an issue about this [open for some time now](https://github.com/dropwizard/metrics/issues/814) and [our PR with the reverts](https://github.com/Banno/metrics/pull/1). Would those PR's be accepted if we can show that persistent connections to graphite aren't really needed for most use cases?

**Comment by ryantenney** [comment]
@adamdecaf I'm afraid the fix isn't quite that simple, given that commit added new methods to the GraphiteSender interface, I can't remove them.  If you're feeling up to making that change, I'd be happy to accept that PR.
