### ISSUE TITLE
com.codahale.metrics.httpclient.HttpClientMetricNameStrategies#HOST_AND_METHOD not recording host.

### ISSUE THREAD

**Issue by solidjb** [dropwizard/metrics#672]
I am working on a Spring Boot application.  In this application we wanted to use DropWizard metrics to record our outgoing http statistics.  I used `com.codahale.metrics.httpclient.InstrumentedHttpClients.createDefault(com.codahale.metrics.MetricRegistry)` to create our outgoing http client.  This automatically gets us a reference to `com.codahale.metrics.httpclient.HttpClientMetricNameStrategies.HOST_AND_METHOD`.  As configured, the instance of com.codahale.metrics.httpclient.InstrumentedHttpRequestExecutor is not recording the host portion of the outgoing uri in the metrics name.  

In digging into it, it looks like the problem is that the InstrumentedHttpRequestExecutor is actually embedded within an instance of org.apache.http.impl.execchain.ProtocolExec.  ProtocolExec actually rewrites the URI in the HttpRequestWrapper to not contain the host and port (presumably, because these are a part of the route?)  When the naming strategy calls `uri.getHost()` the host is null, because it has been rewritten off of the URI.  

I fixed this temporarily by creating a new NamingStrategy that just does this:
`final RequestLine requestLine = request.getOriginal().getRequestLine()`

instead of this:
`final RequestLine requestLine = request.getRequestLine();`

But it seemed worth bringing up to see if this is a fix that should be applied in the project, or if a new naming strategy should be default...

I am using the following libraries:
DropWizardMetrics - 3.1.0
HttpClient - 4.3.5
spring-boot - 1.1.7.RELEASE

**Comment by theigl** [comment]
I just ran into this as well and also solved it by creating my own naming strategy.

**Comment by OrangeDog** [comment]
Is fixed in 3.2.
