### ISSUE TITLE
Timer.Context should be able to be subclassed

### ISSUE THREAD

**Issue by bkyle** [dropwizard/metrics#686]
Timer.Context cannot be subclassed due to its private constructor.  The constructor should be made protected and optionally the class should be moved out into its own top-level class TimerContext (or something similar).  This would allow TimerContext to be subclassed.  Alternatively, many of the classes within the framework have their interface and implementation separated.  Either of these options would allow for extension where none is currently permitted.

**Comment by RichMacDonald** [comment]
Agreed. Or simply create a Context interface. A trivial change that goes a long way and avoids the hacking some of us currently do. For example:

Using the Timer.Context causes garbage collected instances. Unacceptable in tight loops. If we had a public interface, we could use a pool.

**Comment by arteam** [comment]
I think that's a good change for the 4.0 version. We can create an interface inside `Timer`:
```java
public interface Context extends AutoCloseable {

        long stop();

        @Override
        default void close() {
            stop();
        }
}
```

and a default private implementation:
```java
private static class DefaultContext implements Context {

        private final Timer timer;
        private final Clock clock;
        private final long startTime;

        private DefaultContext(Timer timer, Clock clock) {
            this.timer = timer;
            this.clock = clock;
            this.startTime = clock.getTick();
        }
        
        @Override
        public long stop() {
            final long elapsed = clock.getTick() - startTime;
            timer.update(elapsed, TimeUnit.NANOSECONDS);
            return elapsed;
        }
}
```
