### ISSUE TITLE
HealthCheck should really be an interface, not an abstract class

### ISSUE THREAD

**Issue by stevenschlansker** [dropwizard/metrics#697]
`HealthCheck` would be much more useful as an interface, then classes could mix it in to be monitorable.
The `execute` method could be a default method as of Java 8, or it could move to a helper class.

**Comment by McPringle** [comment]
Meanwhile Java 7 is EOL since more than a year, so focusing on Java 8 and using default methods in interfaces should be the preferred way (in my opinion).
