### ISSUE TITLE
Fine-grain filtering for Graphite reporting

### ISSUE THREAD

**Issue by Crias** [dropwizard/metrics#706]
[Feature request]

I am on a small team attempting to use this library to integrate our Jersey2 project with HostedGraphite.

Because HostedGraphite operates on a quota based on the number of individual "metrics". Currently the GraphiteReporter in this library sends multiple metrics to Graphite as a part of a single Metric.

In order to keep costs under control, but still allow us to measure as many of our REST endpoints as possible, we would like to restrict which of the individual metrics. For example, on a Timer we would prefer to only keep "min", "max", and "mean" for now.

Is this already possible? If not, would it be possible to add this kind of functionality?

**Comment by ryantenney** [comment]
Just reopened #178. This is on the roadmap for v4 as it will require some refactoring.
