### ISSUE TITLE
Support backend influxdb

### ISSUE THREAD

**Issue by JulienChampseix** [dropwizard/metrics#724]
Hi Team,

Is it planned to support backend influxdb ? Could be really usefull to propose it also.

Thanks.
Julien.

**Comment by ryantenney** [comment]
We probably won't add official support for InfluxDB unless it were to surpass graphite as the industry standard timeseries database.

**Comment by raskasa** [comment]
Now that the `metrics-influxdb` module has been added, will the third-party implementation be removed from the third-party listing?

SEE: http://metrics.dropwizard.io/3.1.0/manual/third-party/
