### ISSUE TITLE
Configuring a MetricsServlet.ContextListener

### ISSUE THREAD

**Issue by raskasa** [dropwizard/metrics#726]
I'm using Metrics in a J2EE application on Tomcat 7.  I configured my implementation of `MetricsServlet.ContextListener` as the 3rd listener in my application.  For example:

```xml
<listener>
  <listener-class>com.example.CustomListenerA</listener-class>
</listener>
<listener>
  <listener-class>com.example.CustomListenerB</listener-class>
</listener>
<listener>
  <!-- Implementation of `MetricsServlet.ContextListener` -->
  <listener-class>com.example.metrics.MetricsListener</listener-class>
</listener>
<listener>
  <listener-class>com.example.metrics.HealthCheckListener</listener-class>
</listener>
```

The issue is, the Metrics listener is executing first, although it is 3rd in order in my `web.xml` file.

Is the Metrics library implemented to force the `MetricsServlet.ContextListener` implementation to execute first?  Or is the issue's I'm seeing separate from this library?

Thanks in advance.

**Comment by ryantenney** [comment]
The ContextListeners don't specify execution order, so it must be a tomcat issue.
