### ISSUE TITLE
metrics-ganglia is changing the mod of file /var/run/cassandra which failed command *service cassandra status*

### ISSUE THREAD

**Issue by vitan** [dropwizard/metrics#727]
Hi,
I am using using metrics-ganglia on my cassandra server, after config done, while it works and cassandra runs okay also. but when I run command:
{code}service cassandra status{code},

 it prints:
* could not access pidfile for Cassandra

And I debugged in found the mod changed of file /var/run/cassandra

**Comment by ryantenney** [comment]
The Metric GangliaReporter doesn't interact with the filesystem at all, so it can't be responsible for that issue.
