### ISSUE TITLE
Efficiently create Timers, etc with custom Reservoirs or Clocks

### ISSUE THREAD

**Issue by marshallpierce** [dropwizard/metrics#730]
I'd like to be able to use MetricRegistry's get-or-create semantics for the timer() method when creating Timers with a non-default Reservoir. The same applies to using a non-default Clock.

Unless I'm missing something, my only opportunity to register a metric created outside the MetricRegistry is to use `register(String, T)`. This isn't particularly useful, because the common case for me will be to get an existing timer, but I can't use timer() to get it because that will create it (with the default Reservoir) if it doesn't exist. This is what I end up doing instead: https://bitbucket.org/marshallpierce/jersey2-metrics/src/5ed338d7ef18cdd7411b9e06e901d6e12a288e89/jersey2-metrics-core/src/main/java/org/mpierce/jersey2/metrics/MetricProvider.java?at=master#cl-38

That approach (using my own map to be able to computeIfAbsent) is undesirable for several reasons, not the least of which is that those Timer instances now have a separate collection controlling their lifecycle. 

One way to address this would be to add this overload to MetricRegistry:

```
timer(String name, Supplier<Timer> timerSupplier) // to be invoked if timer is created as a result
```

This is, in effect, exposing (part of) the functionality of the internal MetricBuilder type to the user. You could, of course, use a non-JDK8 type if you're targeting people who live in the sad, sad past. ;)

**Comment by ryantenney** [comment]
I absolutely agree that this is necessary. I'm marking this as a feature that should be included in v4. Depending on how when that comes out, we will probably have to accommodate everyone still living in the pre-JDK8 stone age.

**Comment by eric** [comment]
I've run into this as well and would love for a way to override it on a whole registry level as well (change the default builder for timer for that instance of the registry).

**Comment by jebuselwyn** [comment]
+1 for this feature. Would be good to allow overriding the defaults at a registry level.

**Comment by krishnagopal-jobs** [comment]
I want a way to change the registry settings or implement a new way to change the new MetricsRegistry
