### ISSUE TITLE
SlidingTimeWindowReservoir does not evict measurements when Clock.getTick() returns negative value

### ISSUE THREAD

**Issue by dblezek** [dropwizard/metrics#732]
According to Java, `System.nanoTime()` can return negative values.  The logic in `SlidingTimeWindowReservoir` to calculate this does not take this into account, because `lastTick` is initialized to `0` (the default for `new AtomicLong()`).

Fix is to initialize `lastTick` as such (line 56 of `SlidingTimeWindowReservoir`):

```Java
this.lastTick = new AtomicLong(clock.getTick() * COLLISION_BUFFER);
```

Unfortunately I'm not a Maven developer, so I don't have the first clue how to build/test, OTW would the issue would have been a pull request.

Cheers,
-dan

**Comment by ryantenney** [comment]
The current version of SlidingTimeWindowReservoir initializes lastTick in that way: https://github.com/dropwizard/metrics/blob/69fc970151f509a0dc6ccf34ef7c7e9beed663aa/metrics-core/src/main/java/com/codahale/metrics/SlidingTimeWindowReservoir.java#L44

Which version had this problem?

**Comment by dblezek** [comment]
@ryantenney, Ahh!  I have 3.0.1 for some reason.  I'll upgrade to the latest.

Thanks!

**Comment by dblezek** [comment]
P.S.  the older version of Metrics came from Dropwizard 0.7.0.
