### ISSUE TITLE
Storing timestamps for metrics in the metrics registry

### ISSUE THREAD

**Issue by abhishekjain88** [dropwizard/metrics#735]
Referring to the case of the Graphite reporter specifically, the metrics are sent over to the graphite server with a timestamp generated at the time of the run of the reporter, and appended to the plaintext packet to graphite i.e. `<metric_name> <metric_value> <timestamp>`.

Some times this behavior might be undesired and the timestamp of the individual events would need to be preserved.

Here is an explanation of the scenario:

Case 1: Events are being generated at sporadic intervals as opposed to the periodic scheduled execution of the reporter. This results in the same event being sent over again and again with newer timestamps generated (the time of the run of the reporter) till a new event is seen. Thus a lot of duplicate values in the timeseries. 
Problem: Aggregation of these events becomes a challenge. Suppose I want to calculate the average of the metric values in a given duration. In that case, due to the presence of duplicate values the calculation becomes a little tricky where there would be some post processing required in order to de-duplicate this data to finally get the individual points.

Case 2: Events are being generated in a relatively regular fashion. In this case too, even if the reporter interval is aligned approximately to the event generation interval, there is some approximation applied to the timestamp. To reduce this approximation, if the reporter interval is reduced, then again it might lead to duplicate values being sent and hence, the problem of Case1.
## Proposed solution

Add another field called timestamp in the "Metric" implementations (different kind of metrics) and while populating the metrics in the registry, calculate the clock time and add it to the Metric Object, so that it is available while fetching the metrics from the registry from all reporters. Question here is that I guess these metrics are being captured through JMX and whether timestamp of the object modification is captured by JMX or not?

Logic could then be applied subsequently to the reporters to discard events for timestamps already seen by the reporter. 

This could potentially require a major change in the library but is worth doing it for the scenarios I just explained in my opinion.

**Comment by DonSantuzzi** [comment]
Any update here? We are facing the same issue. Would be nice to support custom timestamps.

**Comment by ihr** [comment]
Indeed, this functionality would be much appreciated. We have similar case.
