### ISSUE TITLE
Unable to deserialize all Metrics Objects from JSON

### ISSUE THREAD

**Issue by voidmain** [dropwizard/metrics#745]
EDIT: This needs to be expanded to all of the Metrics classes. 

It looks like all of the Metrics classes including the Health Check classes have Jackson Serializers but none of them have a Deserializer. This means I can't really re-use an domain object on both sides of a status check API. It would be nice to have a deserializer for everything inside the metrics-json library. 

I have written my own shims for almost everything, but it was pretty tedious.

Also, for some of the classes inside Metrics, I had to ignore some of the information (like the stack traces from the Health Check Result class).

I'll attach all of my code to this issue once I've finished. It should be simple to port it over it in the metrics-json library.

**Comment by m8r-ubnc5g** [comment]
+1

**Comment by anudeepti2004** [comment]
I am working on a project which requires me to persist the metrics and then deserialize it when the project is restarted. Serialization works fine and I can see the contents of the file but when I try to deserialize the MetricsRegistry object it throws an exception. So I just wanted to know if there are any updates on this?

**Comment by earce** [comment]
Hi,

Did you come to a resolution on this issue?
