### ISSUE TITLE
Ability to report only certain components of a metric

### ISSUE THREAD

**Issue by shadow000fire** [dropwizard/metrics#750]
For example, in GraphiteReporter, a Timer reports max, mean, min, stddev, etc.  It would be nice if you could enable/disabled each of these.  

I've started this as a bitmask implementation, but I'm realized that won't be able to cover any custom components that someone might add.  Maybe Timer should have some kind of getReportableComponents() that returns an enum.  That way if someone subclasses an existing Metric class like Timer, they can also subclass the enum.  Thoughts?

**Comment by ryantenney** [comment]
This has become an extremely common request, and I've reopened #178 to track it. This is now on the roadmap for v4 as the proper way to do it will introduce breaking changes.

**Comment by shadow000fire** [comment]
Sorry, I didn't notice that when I searched the existing issues.

**Comment by ryantenney** [comment]
No apology necessary!
