### ISSUE TITLE
How do I instrument ehCache when using it as a 2nd level cache for Hibernate in a Spring Boot app? 

### ISSUE THREAD

**Issue by kmandeville** [dropwizard/metrics#753]
My Spring Boot application is using Hibernate/JPA and ehCache as 2nd level cache. So I do not instantiate the Cache objects myself, nor do I know where if at all, I can access/change how the Cache objects are created in order to wrap them. I think I'm missing something in the autoconfiguration of Hibernate/Spring Boot. Any insight into how to use the InstrumentedEhcache class in this situation would be a big help. 

I have gone down the path of creating a CacheManager bean but typically this returns a Springframework CacheManager, not one that I would have access to decorate the caches that are created. 

Sorry for posting this as an issue here, but I could use more help implementing your metrics for ehCache.

**Comment by kmandeville** [comment]
I figured it out finally myself. Sorry to bother you. I had to add a cache manager configuration to my @Configuration class and in it, I had to loop through all caches and call replaceCacheWithDecoratedCache method.

**Comment by ryantenney** [comment]
Cool! I was also trying to figure it out and came up empty.

**Comment by kmandeville** [comment]
Yeah sorry to have logged an issue. Spring is great, but having everything
just automatically configured for you sometimes makes it pretty tricky when
you need to do something a little non standard.

Since this is probably a common scenario of using ehCache, you might want
to add some documentation for how to instrument ehCache when using it with
Spring and Hibernate.
