### ISSUE TITLE
[metrics-ehcache] Allow metrics for arbitrary jcache implementation.

### ISSUE THREAD

**Issue by ptahchiev** [dropwizard/metrics#758]
I'm not sure it's a bug, maybe it's more a feature but anyways. I would like to see a `jcache-metrics` where the metrics are collected for any arbitrary jcache implementation (ehcache, hazelcast, jcs, etc).

**Comment by paranoiabla** [comment]
I believe the these events can be used: `CacheEntryCreatedListener`, `CacheEntryUpdatedListener`, `CacheEntryRemovedListener`, `CacheEntryExpiredListener`

**Comment by ryantenney** [comment]
I would be open to accepting this as a PR, but I'm afraid I won't have any time to do this myself.

**Comment by henri-tremblay** [comment]
Probably closed by #1010

**Comment by arteam** [comment]
Right.
