### ISSUE TITLE
Feature request: filter attributes of a Metric to report

### ISSUE THREAD

**Issue by jmason** [dropwizard/metrics#763]
Hi there --

We have a Metrics/Graphite-based system which records, among other things, a set of business metrics with the following schema:

HOSTNAME.APPID.METRIC

And of course each Timer, for example, records 15 individual sub-metrics:

        sendInt(epoch, sanitizedName, "count", meter.count());
        sendFloat(epoch, sanitizedName, "meanRate", meter.meanRate());
        sendFloat(epoch, sanitizedName, "1MinuteRate", meter.oneMinuteRate());
        sendFloat(epoch, sanitizedName, "5MinuteRate", meter.fiveMinuteRate());
        sendFloat(epoch, sanitizedName, "15MinuteRate", meter.fifteenMinuteRate());
        sendFloat(epoch, sanitizedName, "min", metric.min());
        sendFloat(epoch, sanitizedName, "max", metric.max());
        sendFloat(epoch, sanitizedName, "mean", metric.mean());
        sendFloat(epoch, sanitizedName, "stddev", metric.stdDev());
        sendFloat(epoch, sanitizedName, "median", snapshot.getMedian());
        sendFloat(epoch, sanitizedName, "75percentile", snapshot.get75thPercentile());
        sendFloat(epoch, sanitizedName, "95percentile", snapshot.get95thPercentile());
        sendFloat(epoch, sanitizedName, "98percentile", snapshot.get98thPercentile());
        sendFloat(epoch, sanitizedName, "99percentile", snapshot.get99thPercentile());
        sendFloat(epoch, sanitizedName, "999percentile", snapshot.get999thPercentile());

we have quite a few hosts, and thousands of app IDs.  This means that recording expensive metric types like Timers and Histograms is quite often not viable, due to the cardinality explosion of (x hostnames * y appids * 15 submetrics-per-Metric).  At times, we've resorted to writing our own hacky min/max tracking code, rather than using Metrics :(

It'd be great if there was a way instead to filter the set of submetrics recorded for a specific Metric object -- for instance, for one particular Timer in this high-cardinality scenario, I might only want to record the 99thPercentile, mean, min, and max, and would be happy to discard all the rest.

Maybe using some kind of filter object supplied to the Metric object's ctor, ideally?  thoughts?

**Comment by cemo** [comment]
see #178

**Comment by jmason** [comment]
Yep, sounds a lot like #178 -- although in this case, it would be a _different_ filter for some Metrics vs others, which is slightly different.

**Comment by ryantenney** [comment]
I'll take it under consideration.

**Comment by jmason** [comment]
btw lemme know if you'd like a pull request for this -- I'm keen to help out, since we have a bunch of related hacks in production I'd like to clean up ;)

**Comment by ryantenney** [comment]
Tracking in #178
