### ISSUE TITLE
Make TICK_INTERVAL configurable in Meter

### ISSUE THREAD

**Issue by doom369** [dropwizard/metrics#764]
Hi there,

I decided to use metrics in order to restrict user message request limit. But currently Meter implementation is uses hardcoded value of 5 seconds for rate update. 
```
private static final long TICK_INTERVAL = TimeUnit.SECONDS.toNanos(5);
```
So user could easly do as many request as he wants within this 5 seconds. I propose to add one more constructor for that.
```
    public Meter(int seconds) {
        this.clock = Clock.defaultClock();
        this.startTime = this.clock.getTick();
        this.lastTick = new AtomicLong(startTime);
        this.TICK_INTERVAL = TimeUnit.SECONDS.toNanos(seconds);
    }
```

What do you think?

**Comment by ryantenney** [comment]
I'm afraid I don't quite understand the application. Could you please elaborate?
