### ISSUE TITLE
metrics-zabbix reporter and metrics-kafka reporter

### ISSUE THREAD

**Issue by hengyunabc** [dropwizard/metrics#771]
https://github.com/hengyunabc/metrics-zabbix

https://github.com/hengyunabc/metrics-kafka

If anyone needs them, I'll be happy. :)

**Comment by derekbassett** [comment]
I will tell you we currently have a metrics-kafka version just like yours, including adding the IP address as  into the JSON as well.  This would be awesome to include into the main product.

I noticed the packages are not the correct.  They are io.github.hengyunabc and not the base package for metrics.

Also  I noticed you use com.alibaba.fastjson.JSONObject rather then the metrics-json, not sure if that is an issue or not but I would think maintaining formats as close as possible would be good.  The adding of the IP address is a hard requirement for us so I would think we should adjust metrics-json if we could.

I was also curious about why you created an Executor thread inside the reporter, as most reporters I've seen just use the reporter thread.

**Comment by derekbassett** [comment]
metrics-zabbix seems to rely on io.github.hengyunabc.zabbix.sender.DataObject, io.github.hengyunabc.zabbix.sender.SenderResult, io.github.hengyunabc.zabbix.sender.ZabbixSender please include those into the metrics-zabbix repo unless those are already published in a separate product.

**Comment by hengyunabc** [comment]
I found that some other reporters use their own package name.
https://github.com/elastic/elasticsearch-metrics-reporter-java  
package name is "org.elasticsearch.metrics".

I don not know metrics-json before, so I use my favorite fastjson.

Kafka Producer.send may block, so I think that use a executor is better.

**Comment by hengyunabc** [comment]
[zabbix-api](https://github.com/hengyunabc/zabbix-api) and [zabbix-sender](https://github.com/hengyunabc/zabbix-sender) are separate libraries.

@derekbassett

**Comment by derekbassett** [comment]
Would be interesting to find out what an actual committer says.

**Comment by ryantenney** [comment]
They don't need to be in the same package unless they're being merged into this project (which we aren't doing anymore, maintenance became very difficult).  I've added them to our list of third party modules: c6a6c0c4422ecb7f72d218e995faddf3f78e4da6
