### ISSUE TITLE
Issue with Graphite Metric Format

### ISSUE THREAD

**Issue by jeunito** [dropwizard/metrics#772]
I don't see my metrics being persisited by graphite to whisper. To replicate, I copied the code in https://github.com/dropwizard/metrics/blob/master/metrics-graphite/src/main/java/com/codahale/metrics/graphite/GraphiteUDP.java#L80-L96 and put it in its own main class: 

```java
import java.nio.channels.DatagramChannel;

import java.net.InetSocketAddress;
import java.nio.ByteBuffer;

import java.nio.charset.Charset;
import java.io.IOException;

public class GraphiteTest {
    public static void main(String args[]) throws IOException {
        DatagramChannel datagramChannel = DatagramChannel.open();
        InetSocketAddress address = new InetSocketAddress("hostname", 2003);
        for (int i=1; i<=10000; i++) {
            StringBuilder buff = new StringBuilder();
            buff.append("deploys.spark_test2");
            buff.append(" ");
            buff.append(i);
            buff.append(" ");
            buff.append(Long.toString(System.currentTimeMillis() / 1000));
            buff.append("\n);

            String str = buff.toString();
            ByteBuffer byteBuffer = ByteBuffer.wrap(str.getBytes(Charset.forName("UTF-8")));

            System.out.println(byteBuffer.toString());
            datagramChannel.send(byteBuffer, address);
        }
    }
}                                                                                                                      
```

I don't see any metrics being persisted. The data is being sent however in the former case because when I do a tcpdump, the packets are being received by the graphite host. I think there must be something wrong with how the data is being formatted. 

When I do something like: 

```bash
echo -e "deploys.spark_test2 5 `date +%s`\n" | nc host 2003
```
I see datapoints so I know graphite is working. 

Any ideas?

**Comment by ryantenney** [comment]
Are you sure your graphite instance is listening on UDP port 2003? Netcat defaults to TCP, so that may explain why that works.

**Comment by jeunito** [comment]
@ryantenney thanks. I will revert back to you on this today.

**Comment by jeunito** [comment]
We do have carbon relay in front of our graphite. The former doesn't listen on UDP port 2003. Will set it up to do so and see what happens.

**Comment by ryantenney** [comment]
Ok. I'm going to close this issue, feel free to reopen if that doesn't resolve it.
