### ISSUE TITLE
GraphiteReporter: Unable to report to Graphite

### ISSUE THREAD

**Issue by ShishirKumar27** [dropwizard/metrics#774]
I am trying to make changes in dropwizard-master\dropwizard-example to integrate with graphite to view metrics dashboard. 
Example version:    <artifactId>dropwizard-example</artifactId>
    <version>0.8.1-SNAPSHOT</version>

Have Made below changes:
In pom.xml added dependency
       <dependency>
            <groupId>io.dropwizard</groupId>
            <artifactId>dropwizard-metrics</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>io.dropwizard</groupId>
            <artifactId>dropwizard-metrics-graphite</artifactId>
            <version>${project.version}</version>
        </dependency>

Within HelloWorldApplication --> run added
        MetricRegistry metrics = new MetricRegistry();
        MetricsFactory mfac = configuration.getMetricsFactory();
        mfac.configure(environment.lifecycle(), metrics);
        Counter counter = metrics.counter("nameOfCounter");
        counter.inc();
        counter.inc();
        counter.inc();
        counter.inc();
        counter.inc();

And example.yml report to graphite server hosted by hostedgraphite.com
metrics:
  reporters:
    - type: console
      timeZone: UTC
      output: stdout
      durationUnit: milliseconds
      rateUnit: seconds
      frequency: 120 seconds
    - type: graphite
      host: hostedgraphite.com
      port: 2003
      prefix: <API_KEY_REGISTERED>

When GraphiteReporter tries report it gives  Connection timed out: connect as below:

WARN  [2015-03-30 10:23:17,851] com.codahale.metrics.graphite.GraphiteReporter: Unable to report to Graphite
! java.net.ConnectException: Connection timed out: connect
! at java.net.DualStackPlainSocketImpl.connect0(Native Method) ~[na:1.7.0_65]
! at java.net.DualStackPlainSocketImpl.socketConnect(Unknown Source) ~[na:1.7.0_65]
! at java.net.AbstractPlainSocketImpl.doConnect(Unknown Source) ~[na:1.7.0_65]
! at java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source) ~[na:1.7.0_65]
! at java.net.AbstractPlainSocketImpl.connect(Unknown Source) ~[na:1.7.0_65]
! at java.net.PlainSocketImpl.connect(Unknown Source) ~[na:1.7.0_65]

I am new to dropwizard usage. Please suggest which configuration is incorrect (tried with port 80 and host as IP address)?

**Comment by ryantenney** [comment]
Are you certain the hostname is correct?

**Comment by ShishirKumar27** [comment]
Thanks. After correcting host/port able to view nameOfCounter in graphite and able to configure few metrics for hibernate active/max connections.
One more help I need. Can we view hibernate query time on graphite which gets written in console as 
INFO  [2015-03-30 15:37:26,462] org.hibernate.engine.internal.StatisticalLoggingSessionEventListener: Session Metrics {
    89309 nanoseconds spent acquiring 1 JDBC connections;
    0 nanoseconds spent releasing 0 JDBC connections;
    61978 nanoseconds spent preparing 1 JDBC statements;
    85075 nanoseconds spent executing 1 JDBC statements;
    0 nanoseconds spent executing 0 JDBC batches;
    0 nanoseconds spent performing 0 L2C puts;
    0 nanoseconds spent performing 0 L2C hits;
    0 nanoseconds spent performing 0 L2C misses;
    184392 nanoseconds spent executing 1 flushes (flushing a total of 1 entities and 0 collections);
    11934 nanoseconds spent executing 1 partial-flushes (flushing a total of 0 entities and 0 collections)

**Comment by ryantenney** [comment]
To my knowledge there is not a metrics module which listens for Hibernate's internal metrics.

**Comment by ymagesh** [comment]
@ShishirKumar27 
I am also facing same connection timeout problem. Below is my config. Pls let me know if any other thing i have to use or is it could be any firewall problem. let me know how you have solved. 

graphite.config.params.hostname=carbon.hostedgraphite.com
graphite.config.params.port=2003
