### ISSUE TITLE
Slf4j Reporter: log the metric type using slf4j parameter 

### ISSUE THREAD

**Issue by nithril** [dropwizard/metrics#775]
Slf4jReporter logs metrics:
```java
loggerProxy.log(marker,
"type=HISTOGRAM, name={}, count={}, min={}, max={}, mean={}, stddev={}, " +
"median={}, p75={}, p95={}, p98={}, p99={}, p999={}",....);
```

Could it logs too the type using parameter?
```java
loggerProxy.log(marker,
"type={}, name={}, count={}, min={}, max={}, mean={}, stddev={}, " +
"median={}, p75={}, p95={}, p98={}, p99={}, p999={}", "HISTOGRAM" , ....);
```

The issue may sound strange. In fact I have a logback json appender which extracts slf4j parameters (`{}`) from the log message and convert them to JSON object (https://github.com/nithril/logback-json-layout). It is only feasible if the value is a parameter.

**Comment by ryantenney** [comment]
Sure, I don't see why not. I don't have the time to do it, but if you were to submit a pull request it would be accepted.

**Comment by geissbock** [comment]
@ryantenney As the Slf4jReporter is about to be touched anyway, I would like to ask if there are any objections against switching all these logXYZ() methods from private to protected?

The current versions of SLF4J apparently don't allow to format the parameters (e.g. doubles) but instead stick to a default format, which sometimes causes troubles when processing the logged data. In the concrete example, some doubles are logged as something like `0.00123` and then suddenly switching to something like `9.905307477103993E-6`. This mixture of formats makes it harder (though of course not impossible) to parse the log messages, and I would simply like to be able to extend the Slf4jReporter and add my own implementations of logXYZ() if necessary.

If this is acceptable, I would add this change to the ones made by @nithril

**Comment by ryantenney** [comment]
@geissbock I just merged to master, feel free to make that change.

**Comment by nithril** [comment]
Thanks!
