### ISSUE TITLE
Make MetricRegistry.registerAll(String prefix, MetricSet metrics) public

### ISSUE THREAD

**Issue by seizmo** [dropwizard/metrics#788]
This version of registerAll allowing for a prefix is currently private but should be public, IMHO. For example, just adding some of the JVM metricsets to a registry leaves you with a hodgepodge of inconsistently named metrics which are hard to match to their respective domain at a first glance. Some are a bit generically phrased, a name collision is also possible. So it would be nice to be able to prefix them with "gc", "threads", etc..

**Comment by ryantenney** [comment]
This is a very common source of confusion… MetricSet implements Metric, so `register(String, T extends Metric)` can be called with a MetricSet, and it isn't necessary to change the visibility of registerAll(String, MetricSet) in order to access this functionality.

**Comment by seizmo** [comment]
Ah, I see. Thanks for the quick reply!
