### ISSUE TITLE
Add name prepender support for MetricRegistry.registerAll

### ISSUE THREAD

**Issue by nerdynick** [dropwizard/metrics#791]
It would be nice to have the option to provide a metric name pretender for MetricRegistry.registerAll() method. This comes in handy when you have a library that provides a MetricSet but the names typically provided by the lib for each metric are not unique between each usage of the library. For example a DB Connection Pool library where you have connections to multiple DB's.

**Comment by ryantenney** [comment]
I'm afraid I don't follow. Could you supply an example?

**Comment by nerdynick** [comment]
Digging deeper into the code it appears what I'm looking for already exists but is marked private "private void registerAll(String prefix, MetricSet metrics)" but digging deeper it appears it is exposed publicly with "public <T extends Metric> T register(String name, T metric)" its just not made as clear that MetricSet is a Metric and will be treated differently with register(). Not sure if just adding to the javadoc for register, adding to the website docs, or just making registerAll public is the best approach to improving clarity and documentation on what actions can be done with a MetricRegistry.

**Comment by ryantenney** [comment]
Correct, I've opened #734 to improve that documentation.
