### ISSUE TITLE
ExponentiallyDecayingReservoir stops registering updates

### ISSUE THREAD

**Issue by sotodel** [dropwizard/metrics#793]
In `ExponentiallyDecayingReservoir`, if enough time has passed since you created it (~13+ hours), the weight calculation https://github.com/dropwizard/metrics/blob/master/metrics-core/src/main/java/com/codahale/metrics/ExponentiallyDecayingReservoir.java#L97 returns `Double.Infinity`, causing `priority` to be also `Double.Infinity`, causing collisions in the `Map` and therefore no new updates (assuming `newCount > size`).

`update` calls are therefore almost no-op. They only increment the `count`.

We originally noticed this in the .NET port https://github.com/danielcrenna/metrics-net/issues/45.

**Comment by nickbabcock** [comment]
Does [longPeriodsOfInactivityShouldNotCorruptSamplingState test](https://github.com/dropwizard/metrics/blob/1668978c5c2ac1a4a2b853347efba88f48044fc0/metrics-core/src/test/java/com/codahale/metrics/ExponentiallyDecayingReservoirTest.java#L65-99) not cover this concern?

**Comment by ryantenney** [comment]
You're right, it does.

**Comment by arteam** [comment]
Should be fixed by #1033
