### ISSUE TITLE
CsvReporter should escape records to fully support locales other than `US`

### ISSUE THREAD

**Issue by arosenf** [dropwizard/metrics#805]
If I use CsvReporter with `Locale.GERMANY` I get lines as follows:

> t,count,max,mean,min,stddev,p50,p75,p95,p98,p99,p999,mean_rate,m1_rate,m5_rate,m15_rate,rate_unit,duration_unit
>  1432733866,0,0,000000,0,000000,0,000000,0,000000,0,000000,0,000000,0,000000,0,000000,0,000000,0,000000,0,000000,0,000000,0,000000,0,000000,calls/second,milliseconds

It's not possible anymore to detect which `,` spearates a record and which `,` is just a decimal point.

**Comment by ryantenney** [comment]
I have concerns about escaping by default, in the event someone is using a naïve CSV parser. I'm curious whether it might make sense to override the locale to Locale.US or another locale which uses `.` and not `,`, or whether there is a reason `Locale.GERMANY` is required. The other option of course would be to add escaping as an opt-in feature.

**Comment by arosenf** [comment]
`Locale.GERMANY` is not required in my case, but since CsvReporter offers locale support I expected it to "just work", which was not the case. The example in the user manual sets a locale, that's why I gave it a try.

**Comment by ryantenney** [comment]
Ah ok. I'll keep this open to track the issue, but it'll be low priority if it's not actively causing a problem for you.

**Comment by wimdeblauwe** [comment]
The drawback with using US locale is that Excel will not parse the CSV file correctly if your computer uses a Locale where , is used as a decimal point. You have to be careful to set the good options each time you import the CSV. I would also not escape by default, just in case comma is used as decimal point.

**Comment by wimdeblauwe** [comment]
Shouldn't this issue be marked resolved as https://github.com/dropwizard/metrics/commit/86d5b01d67b0ef6ade27a962eccef3f5c591b910 claims that it fixes this isssue ?
