### ISSUE TITLE
InstrumentedResourceMethodApplicationListener fails to instantiate in TomEE

### ISSUE THREAD

**Issue by ardias** [dropwizard/metrics#806]
Using apache tomee jaxrs 1.7.1 distribution.
When adding the metrics-jersey2 module as a dependency, i can see in the TomEE startup log (catalina.out) the following error:

SEVERE: can't instantiate com.codahale.metrics.jersey2.InstrumentedResourceMethodApplicationListener
java.lang.InstantiationException: com.codahale.metrics.jersey2.InstrumentedResourceMethodApplicationListener
    at java.lang.Class.newInstance(Class.java:427)
        at org.apache.openejb.server.cxf.rs.CxfRsHttpListener.newProvider(CxfRsHttpListener.java:357)

Checking the class code, i can see it  doesn't not have a default ctor, so that's why TomEE is complaining.
Should there be a default ctor? Or is this  TomEE/CXF being idiotic?

**Comment by ryantenney** [comment]
Are you using MetricsFeature to register it? https://github.com/dropwizard/metrics/blob/master/metrics-jersey2/src/main/java/com/codahale/metrics/jersey2/MetricsFeature.java

**Comment by ardias** [comment]
No i wasn't. I'll checkl it out. thanks

**Comment by ardias** [comment]
hi,
problem is that i'm not really using Jersey,  TomEE uses Apache Cxf for JAX-RS and so it's me being stupid trying to use metrics-jersey2. I want to add some metrics to my JAX-RS service and it's not been particularly easy, since i'm also in a JEE environment. 
I tried using metrics-cdi so that i could use annotations, but it only works with CDI 1.2 and TomEE seems to be using only CDI 1.1
I really didn't want to populate my method with direct calls to the metrics 'objects'
