### ISSUE TITLE
counter resets

### ISSUE THREAD

**Issue by willblackie** [dropwizard/metrics#810]
before I go further with testing / documentation on this i wanted to open an issue and see if you're interested, if there's a better approach etc..

problem: per instance counters don't reset, they count up forever, our infrastructure changes all the time as we deploy new versions of services so the graphs produced for count are only useful for understanding how much work an instance did (and when you aggregate they look like shark fins /| /| /|) - which is not what we're looking for, what we actually want is for example how many calls were made to method x or external API y per minute/hour/day.

we're working with datadog for graphing / alerts - using their forwarder (java/metrics -> graphite(carbon-relay) - > datadog agent)

the datadog agent resets counters if you use their sdk, so this is where the idea came from..

the code changes are currently just in the console reporter & graphite reporter (though it'd be easy to do this for all reporters)

```java
GraphiteReporter.forRegistry(rego)
                .convertDurationsTo(TimeUnit.MILLISECONDS)
                .convertRatesTo(TimeUnit.SECONDS)
                .withResetCounters() // this is new
```

the LongAdder already has a sumThenReset method so the implementation is just to call that via new methods on the Timer/Counter/etc.. if the reporter is built with "withResetCounters" enabled
** i understand that this is not atomic but should be good enough, these are metrics not financial audit data though if you have a better solution that performs i'd be open to it of course

sound like something you'd accept if I finish up the other reporters, do some documentation and testing?

here's a working branch
https://github.com/willblackie/metrics/tree/counter_reset

thanks in advance

**Comment by ryantenney** [comment]
Reset comes up a lot, and the current policy is that we can't support resets, if for absolutely no other reasons than multiple reporters would end up clobbering each other, and that counters don't necessarily monotonically increase.
