### ISSUE TITLE
Use a new Socket on each report for the Graphite scheduled reporting

### ISSUE THREAD

**Issue by adamdecaf** [dropwizard/metrics#814]
We've noticed that after the fix for re-constructing connections when things fail (https://github.com/dropwizard/metrics/pull/675) that it takes 15 minutes (plus extra time based on how often you report) to see graphs again. (Or even see metrics recorded.

We've setup a custom reporter for samza jobs (due to them having their own metrics library with not graphite support). In that library we create a new socket each time, here's a copy/paste of that. (In scala)

``` scala
object Graphite extends Logging {
  def withGraphite(host: String, port: Int)(useGraphite: Graphite => Unit): Unit = {
    debug(s"Graphite connection info: $host:$port")
    var socket: Socket = null
    try {
      socket = SocketFactory.getDefault().createSocket(host, port)
      val writer = new BufferedWriter(new OutputStreamWriter(socket.getOutputStream(), "UTF-8"))
      useGraphite(new Graphite {
        def hyphenate(s: String): String = if (s != null) s.replaceAll("""\s+""", "-") else ""
        override def send(name: String, value: String, time: Long): Unit = {
          writer.write(hyphenate(name))
          writer.write(' ')
          writer.write(hyphenate(value))
          writer.write(' ')
          writer.write(time.toString)
          writer.write('\n')
          writer.flush()
        }
      })
    } catch {
      case t: Throwable => error(s"Error writing to Graphite at $host:$port", t)
    } finally {
      if (socket != null) socket.close()
    }
  }
}
```

As you can see we are just creating a new socket each time. This has worked out well for us because since we only report once a minute (no high frequency reporting is needed for us) it's not a worry to re-create a socket on each report.

(The top dots are where we saw metrics, the bottom is samza always reporting.)

![](https://i.imgur.com/ZmaaVvk.png)

So, would it be accepted if we patched dropwizard/metrics to (probably over some threshold, anything under ~30s might want to maintain the existing use case, create a new socket on each send? Or does anyone have other options? We looked at lowering the [`SO_TIMEOUT`](https://docs.oracle.com/javase/7/docs/api/java/net/Socket.html#getSoTimeout%28%29) as well, as right now it seems to be infinite. We have not yet tried that to see what difference it makes though.

**Comment by calumlean** [comment]
Hello all,

We've had a problem with 3.1.1 though an Amazon ELB.
The symptom is that once the JVM starts, we get a few metrics delivered, but then no more.
tcpdump shows the metrics being sent to the ELB, but they never arrive on the carbon boxes.
The metrics host shows a connection in CLOSE_WAIT that never appears to close.
tcp        1   0 ::ffff:10.124.x.x:33377   ::ffff:10.124.y.y:2003   CLOSE_WAIT  495        336560     24092/java

We've rolled back to com.codahale.metrics/metrics-logback 3.0.2 which fixes this problem.

**Comment by jsravn** [comment]
We're having similar problems after upgrading to 3.1.2 to get the #675 and dns caching fix.

Even worse, it appears to kill the scheduled graphite reporter task. OS reports socket as CLOSE_WAIT. My guess is graphite then tries to reuse that socket and gets an unhandled exception that causes the scheduled task to no longer run.

As an aside, GraphiteReporter#report should be catching unexpected exceptions and logging them, instead of just IOException. If something unexpected occurs, the way the code is now, it silently stops scheduling future tasks with no logging.

**Comment by graph1zzlle** [comment]
Same behaviour here

**Comment by arteam** [comment]
Should be fixed by #899

**Comment by adamdecaf** [comment]
@arteam That's fantastic news! I assume there be a 3.1.x release to look forward to then?

**Comment by arteam** [comment]
Yes, as soon we sort things out with the changes for 3.1.3 (#1040) I expect a release. I would like to include only #899 to it to minimize an impact of an updating to a maintenance release.
