### ISSUE TITLE
Overflow when adding 2 long values in SlidingTimeWindowReservoir

### ISSUE THREAD

**Issue by hasnarobert** [dropwizard/metrics#816]
In `SlidingTimeWindowReservoir.getTick` computing the new tick `final long tick = clock.getTick() * COLLISION_BUFFER;` results in overflow when the default clock is used.

**Comment by ryantenney** [comment]
This is a known issue, which we are tracking in #515.

**Comment by mozotom** [comment]
Here's what I've done at my place that fixed it https://github.com/dropwizard/metrics/pull/931
We had this problem when physical server uptime was over 417 days - rebooting server, would restart up time for another 417 days, but we wanted a permanent fix, so I created this one.
