### ISSUE TITLE
Rewrite InfluxDB reporter to use Apache HttpClient

### ISSUE THREAD

**Issue by ryantenney** [dropwizard/metrics#820]

**Comment by dcoraboeuf** [comment]
Hi, do you know when the release of Metrics with support for InfluxDB is due? And in the meantime, which 3rd party library would you recommend to have an InfluxDB reporter?
Thanks,
Damien.

**Comment by bentatham** [comment]
Looks to me like the ``InfluxDbHttpSender`` already used ``org.apache.http``.  

Why not use [influxdb-java](https://github.com/influxdata/influxdb-java) though - which is maintained by the influxdb developers themselves?  If it is not efficient enough, perhaps we could contribute back to that project instead.

**Comment by arteam** [comment]
We don't support InfluxDB in the core right now, and there is a coupld of 3rd party reporters:
* https://github.com/iZettle/dropwizard-metrics-influxdb
* https://github.com/kickstarter/dropwizard-influxdb-reporter
