### ISSUE TITLE
OpenTSDB reporter

### ISSUE THREAD

**Issue by ryantenney** [dropwizard/metrics#821]

**Comment by nsauro** [comment]
+1

**Comment by BorisNaguet** [comment]
+1
That could be a good start:
https://github.com/sps/metrics-opentsdb
?
I haven't had time to test it yet...

**Comment by hindol-viz** [comment]
+1

**Comment by aditanase** [comment]
@ryantenney @BorisNaguet We're using the sps/metrics-opentsdb reporter with metrics3. It does not seem to be maintained anymore but I just sent in a PR to make it compatible with metrics5.
https://github.com/sps/metrics-opentsdb/pull/21

If you're cool with us using it as a base I'm open to polish it up with the hope that it will end up in this repo as an official opentsdb reporter.

CC-ing @sps.
