### ISSUE TITLE
4.0.0-SNAPSHOT jar uses io.dropwizard as package names

### ISSUE THREAD

**Issue by jgangemi** [dropwizard/metrics#824]
apologies if i'm missing something really obvious here...

the jars that get pulled down when i update my pom version all have their packages changed to `io.dropwizard` yet when i look at the code on master, the package names are still `com.codahale` so i'm a little lost as to how that can be. is there a bad jar in nexus?

also, when the 4.0 release comes out, will the package names change or are they going to remain `com.codahale`?

thanks!!

**Comment by ryantenney** [comment]
You're not missing anything obvious. I've been working on 4.0 in the branch metric-name, and pushing snapshots from there. 4.0 will use io.dropwizard.metrics as the package name. This will be the final package name change.

**Comment by jgangemi** [comment]
thank you for that clarification!
