### ISSUE TITLE
Timer with arbitrary number of events in mark

### ISSUE THREAD

**Issue by hadrienk** [dropwizard/metrics#828]
Is there a reason not to expose the amount of events in the Timer#update() method? 

Something like:
```java
   /**
     * Adds a recorded duration.
     *
     * @param duration the length of the duration
     * @param unit     the scale unit of {@code duration}
     * @param n        the number of events
     */
    public void update(long duration, TimeUnit unit, long n) {
        update(unit.toNanos(duration), n);
    }

    }

    private void update(long duration, long n) {
        if (duration >= 0) {
            histogram.update(duration);
            meter.mark(n);
        }
    }
```

**Comment by ryanrupp** [comment]
I'm guessing this is just a rare use case so not sure it makes sense on the standard API, maybe better fit for a custom utility method that just calls update N amount of times. Are you looking to only update the meter though but not the histogram N amount of times? The percentiles would be off then because the duration would only be counted once but maybe that's what you're looking for, what is your use case?

**Comment by hadrienk** [comment]
I have a method that run every x minutes. The method moves around objects and I would like to measure the throughput, but relative to the time it executed. Does that make sense?

**Comment by ryantenney** [comment]
I see what you mean, but @ryanrupp is correct that this doesn't appear to be a sufficiently common use case as to justify inclusion in the API.

Could I recommend maintaining both a Timer _and_ a Meter? That way you'll be recording the count and rate of the method invocation, the method's execution time, and the count and rate of the events/objects processed.

**Comment by hadrienk** [comment]
I will try out using my own Meter objects yes. Thank you.

**Comment by pawelfanduel** [comment]
The use case is quite common when you are doing batch processing with the variable size of a batch and you want to see if there is a gain in making batch smaller or bigger (latency can be measured only as a whole and then needs to be divided). Well just need to write me own timer.
