### ISSUE TITLE
HealthChecks no longer exposed via JMX

### ISSUE THREAD

**Issue by CodingFabian** [dropwizard/metrics#830]
was once working / implemented in #92 , however it is only available via the Admin Servlet .

**Comment by ryantenney** [comment]
It appears JMX was due for a total overhaul in #149, but that never happened. I need to get a sense of how many people are actively using JMX, because at this point supporting it would only take time away from the current major goals of the v4 release.

**Comment by CodingFabian** [comment]
thanks, totally reasonable.

**Comment by ryantenney** [comment]
Tracking in #832
