### ISSUE TITLE
Get a sense of which modules are being actively used

### ISSUE THREAD

**Issue by ryantenney** [dropwizard/metrics#831]
Also which new modules would be desirable.

Put together a survey and send it out on metrics-user, and post it to the project page.

Accept volunteers to maintain any underutilized modules, and deprecate the rest.

**Comment by cemo** [comment]
- metrics-jetty9-legacy
- metrics-ganglia
- metrics-jetty8
- metrics-jersey
- metrics-log4j

These seems a little bid old and not used widely.

**Comment by tguzik** [comment]
Perhaps it's not much and should be taken with a grain of salt, but the number of usages could be an useful indicator here: 

http://mvnrepository.com/artifact/io.dropwizard.metrics

Note that this only shows public projects that were uploaded to Maven Central.

**Comment by ryantenney** [comment]
@tguzik It's a good thought, but it generally won't capture most uses of reporters. It's probably only capturing uses from a couple example Dropwizard projects and any third party modules which support reporters.

**Comment by ryantenney** [comment]
metrics-ganglia is first on the chopping block, due to a transitive dependency on an LGPL-licensed library through gmetric4j. Unless I hear a gigantic outpouring of support, and an offer to refactor it to remove that dependency, I'll be removing it from the v4 branch as soon as next week.

**Comment by ryantenney** [comment]
@joschi Does Dropwizard not use metrics-jersey anymore?

**Comment by joschi** [comment]
@ryantenney No, Dropwizard is using metrics-jersey2 since Dropwizard 0.8.0.

**Comment by cburroughs** [comment]
I have not been able to find a link to the survey.  What is the path forward for the removed module, specifically metircs-ganglia?  Is the v2-style ganglia integration acceptable?
