### ISSUE TITLE
Deeper filtering on Graphite Reporter

### ISSUE THREAD

**Issue by bentatham** [dropwizard/metrics#835]
While we can, of course, filter the top-level metrics, I would like to be able to filter the per-metric details.  Specifically, while the Histograms are useful, I don't find them all the useful when plotting in Graphite.  Given that some paid, hosted graphite instances are priced on a per-metric basis, it would be nice to be able to choose how each Dropwizard Metric gets converted into a Graphite Metrics.

Currently, this could be done by making ``GraphiteReporter.report*`` ``protected`` instead of ``private`` so we can override it.  Better, imo, would be to be able to inject reporters per-metric-type to avoid subclassing ``GraphiteReporter``.

**Comment by marshallpierce** [comment]
I took an approach similar to this for my new relic reporter because New Relic discourages using many custom metrics: https://github.com/palominolabs/metrics-new-relic/blob/master/src/main/java/com/palominolabs/metrics/newrelic/MetricAttributeFilter.java

It lets you filter each reported attribute of each metric type (and individual metric).

**Comment by bentatham** [comment]
Yeah - I thought about doing it that way too, but was discouraged by the long list of per-metric-attribute methods.  I've tried to think of ways around that -- see #837 -- but for now, I'll change mine to do it your way.

Perhaps I'll copy your ``MetricAttributeFilter`` and move it into ``metric-core`` so it can be shared amount all reporters, if desired.

**Comment by ryantenney** [comment]
While it certainly gets the job done, I'm not a big fan of that MetricAttributeFilter.  I'd definitely go the route of #837.

Since this specifically references graphite, I'm going to close this and track it in #178.
