### ISSUE TITLE
MetricAttribute Key

### ISSUE THREAD

**Issue by bentatham** [dropwizard/metrics#837]
I'm not sure I'm using the right terminology, but here I'm using _attribute_ to refer to a specific value of a _metric_, eg _75thPercentile_ of a `Histogram`.  In practice, an _attribute_ is what gets sent out of the system to external tools like graphite.

This is a fairly large scope idea, but it seems to me that through Metrics, there is often a whole whack of methods per-metric.  This makes it virtually impossible to add any custom metrics or do any intelligent filtering of attributes.

See discussion in #835 

So the idea here is to use a _key_-based system for the metric attributes, instead of each metric having attribute-specific methods.
- this could be an `enum`, but likely better to just use some  interface like `MetricAttribute` or something to make it easier to define them in the appropriate places and allow for custom extensibility.
- each metric would have: 
  - `Object getAttribute(MetricAttribute)` method, and would throw `IllegalArgumentException` if the given attribute did not apply to that `Metric`.
  - could get fancy with generic, if desired, so that each `MetricAttribute<T>` could be more specific `<T> T getAttribute(MetricAttribute<T>)` to avoid casting and checking issues.  Obviously, all the primitive types that are typically returned would be boxed.
  - `Set<MetricAttribute> getAttributes()`
- This would then allow us to arbitrarily add custom `Metric`s to the system that could still be handled by `Reporter` by injecting a handler for each specific `MetricAttribute` to the `Reporter`. (or use some generic attribute handling, based on `<T>` in each `Reporter`).
- Each `MetricAttribute` could have a `getKey()` or some such method that could be shared among `Reporter`s (eg `p99`, `median`) so they aren't repeated everywhere;

Lots of details to be fleshed out, but hopefully the goal is clear -- to allow more extensibility.

**Comment by ryantenney** [comment]
:+1: this is almost exactly (not 100% on MetricAttrbute for the name, but that's less important) what I've been planning for v4.

**Comment by bentatham** [comment]
Great!  I'll get started on something in my fork.  If not ``MetricAttribute``, what name did you have in mind?  ``MetricValue``?  The terminology is certainly overlapping -- these _attributes_ are the _metrics_ in the graphite world, whereas the dropwizard _metric_ is a group of graphite _metrics_.  Obviously, I'm not suggesting we change the dropwizard definition of _metric_, but we just need to be clear in the naming and docs to avoid confusion wherever possible.

**Comment by bentatham** [comment]
@ryantenney what is the status of java8 on metrics?  Looks like you still support java7, so can't use java8 features.  The reason I ask is due to ``default`` methods...without them, I think I'll have to use some abstract classes to provide default impls of these new methods (which I loathe, but don't see a better way).  This is particularly true for all ``MetricSet``s and ``Gauge``s, which there are many.

Also, what is you preferred terms for what I call a ``MetricAttribute`` above?  could use ``MetricField``.  I saw reference to a _measurement_ in other issues.  I don't like either of those words since they overlap directly with influxdb terminology, but are not consistent - hence why I used _attribute_.  But I'll use whatever name the community or maintainers decide, of course.

**Comment by bentatham** [comment]
You can see a  first pass of this feature [here](https://github.com/dropwizard/metrics/compare/master...bentatham:feature/837-metric-attribute?expand=1) (without filtering in reporters yet).  I'd like some feedback before continuing, as this is my first contribution to the project - I want to conform to any standards I'm not inferring from existing source (do you have an eclipse formatter, for example?), and it is a fairly large and disruptive.

**Comment by bentatham** [comment]
[Here](https://github.com/dropwizard/metrics/compare/master...bentatham:feature/837-keys?expand=1) is a similar, but different approach that uses more generics to perhaps make it better - but some may find it too complicated.

**Comment by ryantenney** [comment]
I scanned both of those approaches and I think they're both very promising! Thanks! I'll look at them in greater depth soon.

I think Metrics 4 will require Java 8, especially considering that it probably won't be out until after Java 9 is released!

I appreciate your work on this! Let's talk again soon.

**Comment by bentatham** [comment]
I've been working on this change, and if we do plan to move to Java 8, I'd like to know sooner rather then later, because some of the issues I am trying solve would be dramatically helped by lambdas and default methods.  If not, I'll persevere in Java 7, but if yes, then I'm happy to make the pull requests to enable Java 8, and then some more pull requests to do some cleanup of the existing code to take advantage of the Java 8 features, followed by finishing off this issue as well.

**Comment by ryantenney** [comment]
I keep been second guessing the decision to move to Java 8, but let's do it.  We'll still have v3.2 for anyone stuck on Java <=7.

With regard to default methods on interfaces, I'd encourage you to not overuse them.  I think that they should be generally avoided unless a) the interface is intended to be used as a lambda function, or b) an existing interface is being expanded and we need to maintain backwards compatibility.

**Comment by arteam** [comment]
#1048 has added a `MetricAtrribute` class.

**Comment by ryantenney** [comment]
It's not the same, we need to reopen this.

**Comment by arteam** [comment]
Sorry, I didn't read the issue carefully. Now we can use `MetricAttribute` across different metrics modules and expose it in the public API.
