### ISSUE TITLE
InstrumentedResourceMethodApplicationListener doesn't accurately track latency with @Suspended AsyncResponse

### ISSUE THREAD

**Issue by ryankennedy** [dropwizard/metrics#838]
I'm using metrics included in Dropwizard 0.8.2. Several of my methods are using AsyncResponse to offload long running tasks to another thread pool (in this case the Jersey Client thread pool to pipe the uploaded image to another service) so as to not tie up Jetty threads for long periods of time.

Heroku properly notices that my requests are taking 30 seconds, however my @Timed annotated method metric is reporting an 11ms 99th percentile. The reason for this is that InstrumentedResourceMethodApplicationListener.TimerRequestEventListener only wraps the timer around RESOURCE_METHOD_START and RESOURCE_METHOD_FINISHED. When using @Suspended AsyncResponse parameters, however, the HTTP request isn't necessarily complete when RESOURCE_METHOD_FINISHED is fired.

RequestEvent.Type has some other candidates that I think would be better suited to match on for stopping the timer: RESP_FILTERS_START, RESP_FILTERS_FINISHED, or FINISHED. Which one to choose would depend on how much of the request lifecycle we'd want included in the timer. RESOURCE_METHOD_START means we're already excluding all of the routing and request parsing. If we want to remain consistent with RESOURCE_METHOD_FINISHED and only time the service execution and none of the rendering then switching to RESP_FILTERS_START or RESP_FILTERS_FINISHED would likely suffice.

**Comment by ryantenney** [comment]
Yea, there was a similar issue with metrics-servlet recently. I'll try changing the events and see what happens.

**Comment by sjoerdtalsma** [comment]
Any news on this?
Or are we forced to use a different `InstrumentedExecutorService` for each call that we want to have timed?

**Comment by gtrevg** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  gtrevg@gmail.com
    Domain plentyproductions.com has exceeded the max emails per hour (205/200 (102%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext3.iad.github.net ([192.30.252.194]:50947 helo=github-smtp2b-ext-cp1-prd.iad.github.net)
	by server21.abstractdns.com with esmtps (TLSv1:DHE-RSA-AES256-SHA:256)
	(Exim 4.87)
	(envelope-from <noreply@github.com>)
	id 1bE6vH-0007HR-AS
	for github@trevorgattis.com; Sat, 18 Jun 2016 03:27:51 +0000
Date: Thu, 16 Jun 2016 05:50:33 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1466081433;
	bh=UDIbNB5FGJpu+brXdD5Eu/RJRqKYh9g6b5EPfT+QdYE=;
	h=From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=vOP5AjF9rVRK2O4p+AJWEYFBqj9bPZG6HFkx73YDF1H1diTM4fi5d9Fjz3CVrtiBi
	 w7mNb0ea0P9RJiovBrN/S1hyG7mZpnegzopJR3cM9eysN50LScsPLX9gjMmSfiE0oG
	 Roth0wisLPPvsr8t29up9bLKtRWaWzXdFYDFBnPo=

**Comment by edwkar** [comment]
+1. Are there any updates on this? :-)

**Comment by marshallpierce** [comment]
https://bitbucket.org/marshallpierce/jersey2-metrics should measure async responses correctly. I've got a test for it: https://bitbucket.org/marshallpierce/jersey2-metrics/src/326470d2bc4bb8863c535303523816ae897eb81d/jersey2-metrics-core/src/test/java/org/mpierce/jersey2/metrics/FullStackTest.java?at=master&fileviewer=file-view-default#FullStackTest.java-79

It should be pretty easy to drop in instead of the stock Jersey integration. Let me know if it's not :)

**Comment by suspended** [comment]
why did you tag my username?

**Comment by aphalke** [comment]
Any update on this? @marshallpierce its not working for me :( event type that I am getting is         RESOURCE_METHOD_FINISHED, and its checked as Type.Finished
