### ISSUE TITLE
io.dropwizard.jetty.MutableServletContextHandler.percent* metrics returning "NaN" initially

### ISSUE THREAD

**Issue by mcpate** [dropwizard/metrics#840]
Upon initial deployment of the Dropwizard app, when I hit the metrics endpoint (before any other traffic hits the app) I find reasonable defaults for all metrics except the above io.dropwizard.jetty.MutableServletContextHandler.percent* metrics.  These metrics have a value of "NaN" which subsequently causes issues in the metrics aggregator (dogStatsD).  It would seem that a reasonable default for these metrics would be "0"?

If this is a reasonable change I would love to help out if I could be pointed in the correct direction.

**Comment by mcpate** [comment]
Looks like this is happening when InstrumentedHandler::doStart is called.  A Ratio object is returned that can have a value of "NaN".  I'm not sure if this should be checked/updated when the metrics are queried or if it would be better to return "NaN" and have the parsers (in my case dogStatsD) handle the "NaN" value?

**Comment by ryantenney** [comment]
Yep. I think that is the correct behavior, and the parser should be made to handle NaN.

**Comment by ryantenney** [comment]
Does it cause dogStatsD to simply not report that metric, or does it cause the loss of other metrics?

**Comment by mcpate** [comment]
Yeah, it causes dogStatsD to write an error:
```
dd.dogstatsd[15]: ERROR (dogstatsd.py:308): Error receiving datagram
Traceback (most recent call last):
  File "/opt/datadog-agent/agent/dogstatsd.py", line 296, in start
    aggregator_submit(message)
  File "/opt/datadog-agent/agent/aggregator.py", line 599, in submit_packets
    parsed_packets = self.parse_metric_packet(packet)
  File "/opt/datadog-agent/agent/aggregator.py", line 474, in parse_metric_packet
    raise Exception('Metric value must be a number: %s, %s' % (name, raw_value))
Exception: Metric value must be a number: cns.io.dropwizard.jetty.MutableServletContextHandler.percent-5xx-5m, ?
```

**Comment by ryantenney** [comment]
I'm going to close this as an issue with the datadog agent.
