### ISSUE TITLE
90th percentile is missing from metrics

### ISSUE THREAD

**Issue by sandopolus** [dropwizard/metrics#843]
The [documentation](http://metrics.dropwizard.io/3.1.0/getting-started/) for the Dropwizard Metrics states that the Histogram should have the 90th percentile metric available, but it is currently missing and is generally a useful percentile to have to SLA purposes.

I am working on updating the code in the metrics-core project so that the 90th percentile is added into the [Snapshot class](https://github.com/dropwizard/metrics/blob/master/metrics-core/src/main/java/io/dropwizard/metrics/Snapshot.java) along with the core reporters and unit tests within this section.

Is there anything else that should be looked into for this?
Otherwise i will work on the code and get the pull request submitted when your happy.

Thanks

**Comment by ryantenney** [comment]
I'd suggest that you not try to add in 90th percentile.  It's very likely that v4 will have configurable quantiles, and as a result most of the changes to add this would be overwritten. I'll keep this issue open to make sure we add in 90th percentile after the refactor is completed.

**Comment by mkumaromnifone** [comment]
And also could you please add 50th percentile?

**Comment by ryantenney** [comment]
Median is 50th percentile.

**Comment by mkumaromnifone** [comment]
thanks a lot for prompt response, sorry by mistake i had asked this question.

**Comment by mkumaromnifone** [comment]
is there any way to get code for 3.1.2 version?

**Comment by ryanrupp** [comment]
You can view the tags in github, so 3.1.2 is here - https://github.com/dropwizard/metrics/tree/v3.1.2 and can download the source as a zip.
