### ISSUE TITLE
ExponentiallyDecayingReservoir histogram precision

### ISSUE THREAD

**Issue by soid** [dropwizard/metrics#852]
I might misunderstand something, but I feel like this description in ExponentiallyDecayingReservoir is not fully accurate:

```
Creates a new {@link ExponentiallyDecayingReservoir} of 1028 elements, which offers a 99.9%
confidence level with a 5% margin of error assuming a normal distribution, and an alpha
factor of 0.015, which heavily biases the reservoir to the past 5 minutes of measurements.
```

I've understood it as it provides a 5 minutes sliding window with high confidence level that the statistics are within the estimated values plus minus 5% error.

However, the way it works is that it has a pool of samples (1028 elements), and if there've been many hits 10 minutes ago, and no or a few hits for the last five minutes, then it will not clean the pool and will be actually biased toward the busy time 10 minutes ago.
For example, if there were 2000 hits 10 minutes ago, and in the last 5 minutes we've got only 5 hits, then the pool will contain 5 samples for the last five minutes and 1023 samples older than that. And this histogram will be mostly based off the 10 minutes data.

Next, I feel like the claim "99.9% confidence level with a 5% margin of error" can't be made without knowing anything about population distribution.  I might forget statistics though.

So additional comments, documentation and guidelines on how to pick the sample pool size and the alpha are greatly appreciated. It feels like ExponentiallyDecayingReservoir is not that easy as it is documented. I'd like to contribute, but I feel rather puzzled than figured that out.

**Comment by marshallpierce** [comment]
You're correct. Another issue is that it assumes a normal distribution, which for most things is not a good assumption. Latency in computer systems is almost never normal because you're not measuring some natural process (see central limit theorem, etc.). Might I suggest https://bitbucket.org/marshallpierce/hdrhistogram-metrics-reservoir instead -- see the links in its readme for more on why.

**Comment by jmkgreen** [comment]
This fits our observations of inaccuracies. In our case most of the "traffic" we are measuring occurs within a limited time window each day, probably quite a common pattern.

The customisation by using a separate histogram implementation may be a workaround however there are now a number of libraries making use of Dropwizard Metrics under the hood (Apache Camel in our case) and thus the indirection makes such adjustments heavy work if not impossible. There also does not seem to be an up-to-date artefact within Maven Central :(

**Comment by marshallpierce** [comment]
Hmm, sounds like there are several parts to this: 

- The default reservoir type is not applicable for many use cases
- People may want to change the default type for their project
- But if you do change the default type, you'd change it for everybody, including your dependencies -- maybe the ability to change the default should be scoped in some way.

Which artifact are you referring to? If you mean the hdrhistogram reservoir, its artifacts are published to jcenter. (It's like Maven Central, but more artifacts, better CDNs, and an easier developer experience for uploading.)

**Comment by jmkgreen** [comment]
I think changing the default type within a project would be a step too far and may cause more confusion particularly for dependencies as you suggest.

> Which artifact are you referring to?

See http://search.maven.org/#search%7Cga%7C1%7Chdrhistogram - I have not attempted to set Maven to use both Central and jcenter since I've never had the need nor do I immediately have the time to look at it.

**Comment by marshallpierce** [comment]
Maven central is a subset of jcenter, so that's expected.
