### ISSUE TITLE
A plugin that emits metrics using the collectd binary protocol over UDP

### ISSUE THREAD

**Issue by timezra** [dropwizard/metrics#853]
I have a metrics plugin that can emit metrics using the collectd binary protocol and would like to submit it for your consideration.

**Comment by timezra** [comment]
Just out of curiosity, was this closed because there is a separate pull request open for it or because the request for feature has been rejected? Thanks, -Tim

**Comment by ryantenney** [comment]
The former. I haven't had time to review the pull request, I'll try to get to it soon.
