### ISSUE TITLE
Support for Riemann/Elasticsearch Reporter Contribution

### ISSUE THREAD

**Issue by timezra** [dropwizard/metrics#855]
I would like to get the community's feedback on whether anyone would find metrics connectors to elasticsearch and riemann useful. I would find value in these and would like to contribute them.
Using the elasticsearch bulk upload api should be straightforward and should not bring in additional dependencies as it just uses http.
Riemann is a different issue as that would mean using protocol buffers and would probably mean bringing in a library from the clojars dependency repository.
If the community is interested in either of these connectors, is anyone more passionate about one than the other?
Cheers,
---Tim---

**Comment by ryantenney** [comment]
I'm not certain about elasticsearch, but I am very interested in a riemann reporter. Just so you know, the library is going to be somewhat rearchitected in the not too distant future, so it probably doesn't make sense to start this work yet.

**Comment by timezra** [comment]
Thanks, Ryan. I find riemann integration more interesting as well and am glad you picked that one :-) Just out of curiosity, is the rearchitecture planned for the next release and when are you targeting the next release?

**Comment by jonnywray** [comment]
Just an FYI in case you're not aware, but the Riemann Java client already includes a metrics reporter. I'm using it very successfully.

**Comment by ryantenney** [comment]
Thanks for the heads up!
