### ISSUE TITLE
Dropwizard reports its metrics version incorrectly

### ISSUE THREAD

**Issue by pmacklin** [dropwizard/metrics#860]
I noticed this when trying to upgrade metrics version from 3.1.0 to 3.1.1; the version is still reported in the metrics generated JSON like so:

```
{
  "version": "3.0.0",
  "gauges": {
    // ...
```

This appears to be hardcoded in a deep embeded file and not driven from the POM files at all. Can this be brought up to date please?

https://github.com/dropwizard/metrics/blob/master/metrics-json/src/main/java/io/dropwizard/metrics/json/MetricsModule.java#L26

**Comment by ryantenney** [comment]
Thanks for the heads up! Will be fixed in 3.1.3 and in 4.0.0, whenever they're released.
