### ISSUE TITLE
Support for double values in Histogram

### ISSUE THREAD

**Issue by djgeary** [dropwizard/metrics#863]
Currently Histogram only supports updating with int or long values. 

We need a histogram metric for a double value and currenlty we are having to multiply up by a known power of 10 to be able to use Histogram as it stands (and then remember the output metrics need to be divided again to get the actual mean, max etc.).

**Comment by ryantenney** [comment]
I'd be open to considering this as a pull request, but it won't happen otherwise.

**Comment by selotape** [comment]
Hey @arteam , I notice you added this feature to the 4.1.0 milestone.
Does that mean this feature is in the works? or is it still up for grabs?

**Comment by reviliant** [comment]
Hello is this feature still open or someone has already implemented this

**Comment by joschi** [comment]
> Hello is this feature still open or someone has already implemented this

@reviliant It's still open.

Please get in touch if you want to provide a pull request for this (see #1525 for discussion).

**Comment by the-thing** [comment]
@joschi 

I had a quick look and I would be happy to work on this, but I'm not sure how far you want to go with code duplication. I understand that for the time being the backwards compatibility is a must, so we can't simply replace long with double. However, I think in the long run this is a great idea.

Things that will be duplicated
- reservoir implementations (as per https://github.com/dropwizard/metrics/issues/1525)
- snapshots (uniform, weighted)
- histogram
- some reporters (JMX histogram etc.)

There is not that much code that can be refactored to retain backwards compatibility . Maybe extracting some common code such as Snapshot -> BaseSnapshot etc. I've got some ideas how to avoid some of these duplications, but the API might not be consistent anymore.

This is a useful feature that I heard many people wish was provided by the library. Again, happy to contribute, but don't want to spend time needlessly.

**Comment by joschi** [comment]
@the-thing Sorry, I totally forgot about this comment. 🙈

I've given it a try over the weekend and #1806 is the preliminary result. I'm not 100% happy with it because it introduces a lot of duplicate code, but extracting all remotely similar functionality into common base classes also seemed overkill for now.

Since you already thought about it, I would very much appreciate your comments and improvements on the PR. 😄

**Comment by joschi** [comment]
@djgeary @selotape @reviliant @the-thing @alzkiria @vladimir-bukhtoyarov Any comments on #1806 from your ends?

**Comment by acommend** [comment]
This issue was closed potentially indicating that support was added for the DoubleHistogram, however with the latest v4.2.34 the feature is missing. Has it been replaced with something else?

**Comment by joschi** [comment]
@acommend The relevant PR #1806 was closed without merging.

There is currently no support for histograms backed by floating point values.
