### ISSUE TITLE
Create collectd reporter

### ISSUE THREAD

**Issue by dernasherbrezon** [dropwizard/metrics#870]
Good day,

Would like to create collectd reporter and pull request. Essentially it will be the same as graphite udp reporter but implement collectd protocol.

Any objections?

**Comment by zhaohangbo** [comment]
It's a good idea. I am also interested in creating collectd reporter

**Comment by sirlordt** [comment]
Excelent idea... please implement this.

**Comment by jplock** [comment]
There are a few open pull requests related to this already in #871 and #854

**Comment by ryantenney** [comment]
I'm supportive of a collectd reporter. I'll take a look at those two PRs.
