### ISSUE TITLE
CsvReporter should sanatize metric names to be sure they are valid file names

### ISSUE THREAD

**Issue by wimdeblauwe** [dropwizard/metrics#880]
There is a `sanitize` method in CsvReporter, but it does nothing to sanatize at all. I can create a PR for this if you want, but it has to be decided what to do with illegal characters. Just remove them? Replace them with `_` or `-` or something else? Do we consider `/` as an illegal character (currently, this will make the CSV file into a subdirectory, which might be what some users want) ?

**Comment by ryantenney** [comment]
Can I consider this resolved by your PR?

**Comment by wimdeblauwe** [comment]
No, this is different. Any preference on how the sanitation should be done?

Op maandag 2 november 2015 heeft Ryan Tenney <notifications@github.com> het
volgende geschreven:

**Comment by guillaume-aecf** [comment]
Is this issue still active? I'm currently facing the same issue. Or maybe, if you could provide a way of extending CsvReporter so I can override sanitize() myself?

**Comment by arteam** [comment]
It was fixed in Metric 3.2.0. Now `CsvReporter` has a `CsvFilePrvovider` which sanitizes metrics names. You can provide a custom one, if you want. See #882 and #910.

**Comment by guillaume-aecf** [comment]
Perfect! Thank you. :-)
