### ISSUE TITLE
Publish 4.0.0-SNAPSHOT

### ISSUE THREAD

**Issue by fzakaria** [dropwizard/metrics#881]
I'd like to make use of a lot of the new functionality (especially metric-servlets).

Can you publish a SNAPSHOT of 4.0.0 ?
You've made mention that you might have already however I was unable to find any maven repo with it.

**Comment by ryantenney** [comment]
There's a pretty recent snapshot in the Sonatype snapshots repo: https://oss.sonatype.org/content/repositories/snapshots/io/dropwizard/metrics/
