### ISSUE TITLE
Custom reporter that writes to Hazelcast?

### ISSUE THREAD

**Issue by stodge** [dropwizard/metrics#884]
I'm prototyping Metric in my application and I was wondering if creating a custom reporter is as simple as deriving from ScheduledReporter and "filling in the blanks" as it were? I want to experiment with reporting to Hazelcast 2.6.10 (http://www.hazelcast.org). If that makes sense. Does that make sense?

Thanks

**Comment by ryantenney** [comment]
Yes that is absolutely correct. The scheduled reporter handles scheduling and retrieving metrics from the MetricRegistry, you just have to override the report method. I'm going to close the issue, but please feel free to ask any additional questions you might have here!
