### ISSUE TITLE
httpasyncclient integration doesn't time request execution

### ISSUE THREAD

**Issue by juretta** [dropwizard/metrics#886]
The current approach does not actually time the request execution but the time to return the Future of the response. This was discovered when introducing latency in our code that wasn't reflected at all in the metrics we gathered from the async client library.

PR #885 provides a fix and highlights the problem.

**Comment by ryantenney** [comment]
Thanks! Will track in #885. It will be a couple days before I have a chance to review it, but I greatly appreciate your giving the httpasyncclient module some well needed TLC.

**Comment by juretta** [comment]
I think this should be re-opened. Request execution timing for the httpasyncclient is essentially broken.

**Comment by ryantenney** [comment]
It has been moved to #885, which is still open

**Comment by juretta** [comment]
I think my point is that this is a bug in the library as the request execution measurement is simply wrong. As a consumer of the library I'd expect the issues to reflect the state of the library instead of splitting issue tracking and open PRs. But that's just me maybe ¯\_(ツ)_/¯
