### ISSUE TITLE
Make GraphiteReporter output configurable

### ISSUE THREAD

**Issue by note** [dropwizard/metrics#887]
I think that `GraphiteReporter` should give user some option to modify the output of metrics. It would be nice to be able to e.g. report 90th percentile or to have different keys. It's useful when you migrate from different reporter but want to keep old formatting.

I am thinking about adding a new parameter (let's say `GraphiteFormatter`) to `GraphiteReporter` constructor. Than user would be able to inject his own implementation.

I am willing to contribute but first want to ask if it makes sense to you.

**Comment by ryantenney** [comment]
Thanks for asking!  This is a desirable feature, however I am hoping to have configurable percentiles as a native feature in Metrics 4 (each metric will define a set of attributes which they export, and the attributes would be configurable globally or per metric). At least that's the current plan.

**Comment by mhurne** [comment]
Some solution to this problem is desirable on my end as well, especially when using https://bitbucket.org/marshallpierce/hdrhistogram-metrics-reservoir

**Comment by devenv** [comment]
Configurable number of the decimal digits sent would be nice too :/

**Comment by arteam** [comment]
Looks like the user now can disable some metrics (#1048) and format decimal digits (#1073).
