### ISSUE TITLE
Release scheduled?

### ISSUE THREAD

**Issue by fernandezpablo85** [dropwizard/metrics#906]
Looking forward to use the metrics-influxdb implementation but it seems the latest version doesn't include it, are you planning on cutting a new release with that extension?

**Comment by fernandezpablo85** [comment]
Implementing something like https://jitpack.io would be ideal and hassle-free

**Comment by ryantenney** [comment]
I'm afraid the metrics-influxdb module isn't scheduled for release until metrics v4, and I don't know when that will be released. I have several grand ideas for v4 and no time to make them happen.

**Comment by fernandezpablo85** [comment]
no worries, im already using it via jitpack.io

**Comment by sriram-r** [comment]
Guys - just wanted to see if there's any plan to do a release of metrics-core. I've been playing with the tag support functionality and we like it. I wanted to know if there's a release scheduled for it?

**Comment by ryantenney** [comment]
I'm afraid there's no release scheduled for the master branch (v4) at this time.

**Comment by fernandezpablo85** [comment]
BTW I ended up using https://jitpack.io as a workaround, that way you can "depend" on a specific commit and update at will.
