### ISSUE TITLE
jetty's MutableServeletContextHandler metric reports currentTimeMillis instead of actual duration in case of AsyncResponse

### ISSUE THREAD

**Issue by kubagruszka** [dropwizard/metrics#914]
We're facing an issue that the timer metrics family `io.dropwizard.jetty.MutableServletContextHandler.requests` reports currentTimeMillis instead of elapsed duration in case of AsyncResponse processing while using metrics-jetty9-3.1.2. After some code debugging it looks like:

`Request#startAsync` and `HttpChannelState#startAsync` are triggered yet before the `AsyncListener` listener `com.codahale.metrics.jetty9.InstrumentedHandler` is being registered thus the method `onStartAsync` where `start` is initalized is not being triggered. This results in `updateResponses` is triggered with start == 0 and calculates the elapsedTime == currentTimeMillis.

I do not understand this code enough to find the root cause, but I believe that above explanation will shed more light on the problem for those who are experts here. Thanks!

**Comment by mziemba** [comment]
I have the same issue using Spring Boot 1.3.5.RELEASE with Jetty 9.2.16.v20160414 and Metrics 3.1.2.

A sample application that illustrates the issue can be found [here](https://github.com/mziemba/spring-boot-jetty-metrics)

**Comment by arteam** [comment]
I guess it should be fixed by #1074
