### ISSUE TITLE
metrics-jvm 3.1.2 and metrics-core 3.1.2 don't play nicely

### ISSUE THREAD

**Issue by oliverlockwood** [dropwizard/metrics#916]
I'm experiencing the following error, with both `io.dropwizard.metrics:metrics-jvm:3.1.2` and `io.dropwizard.metrics:metrics-core:3.1.2` on my classpath:

```
java.lang.NoSuchMethodError: com.codahale.metrics.JmxAttributeGauge.<init>(Ljavax/management/MBeanServerConnection;Ljavax/management/ObjectName;Ljava/lang/String;)V
	at com.codahale.metrics.jvm.BufferPoolMetricSet.getMetrics(BufferPoolMetricSet.java:45)
```

From looking at the code on the 3.1-maintenance branch, I notice the following:
-  The `getMetrics()` method is attempting to call a constructor on `JmxAttributeGauge` with first parameter of type `javax.management.MBeanServer` (see [here](https://github.com/dropwizard/metrics/blob/3.1-maintenance/metrics-jvm/src/main/java/com/codahale/metrics/jvm/BufferPoolMetricSet.java#L45-L46)).
-  The constructor available in `JmxAttributeGauge` takes a first parameter of type `javax.management.MBeanServerConnection` (see [here](javax.management.MBeanServerConnection)) instead.

Is this a known issue?  Are there any plans to resolve it?

**Comment by ryantenney** [comment]
MBeanServer implements MBeanServerConnection, so that doesn't explain it: https://docs.oracle.com/javase/7/docs/api/javax/management/MBeanServer.html

Might you have multiple versions of Metrics on the classpath?

**Comment by oliverlockwood** [comment]
@ryankennedy thanks for the pointer; I thought I'd looked for that possibility but obviously missed it.  It may well be a classpath issue - I'll look into that now.

**Comment by oliverlockwood** [comment]
Confirmed.  The joys of trying to upgrade from 0.7.1 to 0.9.2!  Thanks for your time, I'll close this issue now.
