### ISSUE TITLE
@Timed, @Metered & @ExceptionMetered defined per Resource

### ISSUE THREAD

**Issue by patrox** [dropwizard/metrics#919]
I noticed that the mentioned annotations, are defined with target contexts:

```
@Target({ ElementType.TYPE, ElementType.CONSTRUCTOR, ElementType.METHOD, ElementType.ANNOTATION_TYPE })
```

but they are effective only when defined at method level - as the [InstrumentedResourceMethodApplicationListener#registerMetricsForModel](https://github.com/dropwizard/metrics/blob/master/metrics-jersey2/src/main/java/io/dropwizard/metrics/jersey2/InstrumentedResourceMethodApplicationListener.java#L179) method is registering only those.

Since at our company we're often marking every resource method with either `@Timed` or `@Metered` then we thought that it would be great if you could declare it per class (`Resource`) level -
so instead of declaring each method as `@Timed`:

```java
@Path("/")
@Produces(MediaType.TEXT_PLAIN)
public class InstrumentedResource {
    @GET
    @Timed
    @Path("/timed")
    public String timed() {
        return "yay";
    }

    @GET
    @Timed
    @Path("/timed2")
    public String timed2() {
        return "yay";
    }
}
```

you could declare it on a class (`Resource`) level, like that:

```java
@Timed
@Path("/")
@Produces(MediaType.TEXT_PLAIN)
public class InstrumentedResource {
    @GET
    @Path("/timed")
    public String timed() {
        return "yay";
    }

    @GET
    @Path("/timed2")
    public String timed2() {
        return "yay";
    }
}
```

Do you think that this is reasonable ? I would like to contribute my changes, if you find it useful.

**Comment by marshallpierce** [comment]
If you use my alternate jersey2 integration, it's easy to do that, or any other policy (e.g. "methods that end in the letter Q", or whatever you want): https://bitbucket.org/marshallpierce/jersey2-metrics

**Comment by ryantenney** [comment]
I added those additional target types somewhat recently in order to support other developers that may wish to implement that functionality (ahem… @marshallpierce).

That having been said, I would like to add support for that to all the first-party modules. It's lower on my list of priorities, but if you submitted a pull request it would be gladly accepted.

**Comment by patrox** [comment]
thanks @ryantenney - I'll post a PR today.

**Comment by patrox** [comment]
@ryantenney a little bit later than originally planned, but here it is: https://github.com/dropwizard/metrics/pull/920

Could you please have a look, whenever you'll have time ?

**Comment by rahuljain1804** [comment]
Hi @ryantenney, I am using metrics-core 3.1.0 for jmx reporting but unable to see @Timed working at resource level. Can you tell me which version supports @Timed at resource level?
