### ISSUE TITLE
Non-metric meta data reporting

### ISSUE THREAD

**Issue by agentgt** [dropwizard/metrics#924]
We often need a simple way to get some meta data from services. Generally this information is on how something is configured or environment information. This is not metric data nor is it a healthcheck as it rarely changes and is generally JSON-like data.

Enter OpsReporters... We have implemented our metadata registry that is very similar to the Metrics API.

It basically allows us to write readonly admin data retrieval without coupling to a web framework.

``` java
public interface OpsReporter {
  //the properties parameter could be omitted as we still haven't needed but this could come from request parameters allowing the reporter to present different data or filter. 
    public Map<String, Object> report(Map<String, String> properties) throws Exception;
}
```

``` java
public class OpsReporterRegistry implements OpsReporterSet {
    private final Map<String, OpsReporter> reporters = new ConcurrentHashMap<String, OpsReporter>();

    public void register(String name, OpsReporter reporter) {
        reporters.put(name, reporter);
    }

    public Map<String, OpsReporter> getReporters() {
        return reporters;
    }
}
```

I'm not sure if this is out of scope of this project but I figured it might not given that HealthChecks are not really Metrics.

Or perhaps others have better solutions to the above problem?

**Comment by ryantenney** [comment]
I haven't encountered this exact use case, but perhaps others have. If there's a significant demand for this capability, it can't be accomplished with this or another library, and it makes sense to add to this project I'd be open to it.

**Comment by marshallpierce** [comment]
This seems related to the thread "Non-numeric Gauges?" on metrics-user. I don't think health checks are a *great* fit as being part of this library, like the OP said -- what if there was a separate library for health checks and other stuff like this? Operationally useful stuff, sometimes live, sometimes not, and maybe it includes some annotated metric data (or not), but really it's just a way of saying "expose this simple, structured-ish data in a way that I can easily expose over http or jmx or other things". Which, I think, is a different role than "calculate these numeric properties".

**Comment by sigram** [comment]
Recent versions of Apache Solr use metrics for exposing all sorts of metadata (paths, selected config strings, Java properties) as well as using a custom gauge impl. for exposing dynamic map-like data (eg. system properties, cache entries etc) where it wouldn't make sense to register them as individual metrics due to their dynamic nature and the inability to monitor changes (eg. someone adding or deleting a sysprop).
We found it quite useful to expose this data alongside regular metrics, so that it can be accessed and reported using the same API.
