### ISSUE TITLE
Namespaced Registries

### ISSUE THREAD

**Issue by randomstatistic** [dropwizard/metrics#925]
Similar to the way a GraphiteReporter can specify a prefix, it's be nice to be able to pass around Registries that enforce a particular namespace/prefix.

I'm imagining you could say something like:

```
MetricRegistry shared = SharedMetricRegistries.getOCreate("foo");
trackUsageStats(shared.withPrefix("usage"));
trackReportingStats(shared.withPrefix("reporting"));
```

Namespaced registries would ideally be MetricRegistry objects themselves, but map to another registry under the hood, such that all interactions apply the designated prefix. So these would be equivalent:

```
shared.timer("usage.abc")
shared.withPrefix("usage").timer("abc")
```

**Comment by randomstatistic** [comment]
Looks like something similar was discussed in Issue #842.

**Comment by ryantenney** [comment]
Yea this looks a lot like #842, I'll track it there. Feel free to register your interest in a comment on that ticket.
