### ISSUE TITLE
Worst Performing Metrics

### ISSUE THREAD

**Issue by mebigfatguy** [dropwizard/metrics#928]
Sorry if i've missed this, but i have a collection of similar metrics, say N Timer metrics (selectable by a simple MetricsFilter). I'd like to expose a text based metric, that shows the bottom N performers (3? 4?) out of this set. Is there a way to do this?

**Comment by ryanrupp** [comment]
You could do this possibly with a Gauge<String> but you would have to implement all the logic e.g. when the gauge gets called it sorts the timers (or snapshots) you're interested in and then shows the top 3-4 by name. You can use a cached gauge (in metrics core) if computing this is a heavier task.

Personally though I would leave this to an external timeseries database (graphite, influxdb, opentsdb, prometheus etc.) that you would just report each timers percentiles to every X minute(s) and do the visualization/aggregation inside of that tool. Of course that approach is a bit heavy handed but having an external tool for this type of aggregation/visualization is nice to have if you can allow it!
