### ISSUE TITLE
HTTP CONNECT method (establishing proxy tunel) breaks HttpClientMetricNameStrategy (QUERYLESS_URL_AND_METHOD)

### ISSUE THREAD

**Issue by JanGurda** [dropwizard/metrics#949]
I use Apache HTTP client 4.4.1, Metrics HTTP CLient 3.1.2 and HTTPS proxy when connecting to one of downstream services.
When I use InstrumentedHttpRequestExecutor I get following exception when HTTP client tries to establish tunnel through proxy:

(xxxxxxxxxxxxxxxxxxxxxxxxxxxx is destination host name)

`
! java.net.URISyntaxException: Expected scheme-specific part at index 38: xxxxxxxxxxxxxxxxxxxxxxxxxxxx:
! at java.net.URI$Parser.fail(URI.java:2848) ~[na:1.8.0_60]
! at java.net.URI$Parser.failExpecting(URI.java:2854) ~[na:1.8.0_60]
! at java.net.URI$Parser.parse(URI.java:3057) ~[na:1.8.0_60]
! at java.net.URI.<init>(URI.java:588) ~[na:1.8.0_60]
! at org.apache.http.client.utils.URIBuilder.build(URIBuilder.java:120) ~[pms.jar:1.0-SNAPSHOT]
! at com.codahale.metrics.httpclient.HttpClientMetricNameStrategies$3.getNameFor(HttpClientMetricNameStrategies.java:47) ~[pms.jar:1.0-SNAPSHOT]
! ... 129 common frames omitted
! Causing: java.lang.IllegalArgumentException: java.net.URISyntaxException: Expected scheme-specific part at index 38: ppa-spidcash-dev.payment.schibsted.no:
! at com.codahale.metrics.httpclient.HttpClientMetricNameStrategies$3.getNameFor(HttpClientMetricNameStrategies.java:50) ~[pms.jar:1.0-SNAPSHOT]
! at com.codahale.metrics.httpclient.InstrumentedHttpRequestExecutor.timer(InstrumentedHttpRequestExecutor.java:51) ~[pms.jar:1.0-SNAPSHOT]
! at com.codahale.metrics.httpclient.InstrumentedHttpRequestExecutor.execute(InstrumentedHttpRequestExecutor.java:42) ~[pms.jar:1.0-SNAPSHOT]
! at org.apache.http.impl.execchain.MainClientExec.createTunnelToTarget(MainClientExec.java:472) ~[pms.jar:1.0-SNAPSHOT]
! at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:397) ~[pms.jar:1.0-SNAPSHOT]
! at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236) ~[pms.jar:1.0-SNAPSHOT]
! at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184) ~[pms.jar:1.0-SNAPSHOT]
! at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88) ~[pms.jar:1.0-SNAPSHOT]
! at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110) ~[pms.jar:1.0-SNAPSHOT]
! at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184) ~[pms.jar:1.0-SNAPSHOT]
! at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:71) ~[pms.jar:1.0-SNAPSHOT]
! at no.spid.payment.metrics.http.client.InstrumentedApacheConnector.apply(InstrumentedApacheConnector.java:344) ~[pms.jar:1.0-SNAPSHOT]
`

The problem is that Apache HTTP client calls CONNECT method on proxy and HttpRequest.gtRequestLine()  resolves to: "CONNECT xxxxxxxxxxxxxxxxxxxxxxxxxxxx:443 HTTP/1.1"
Later URLBuilder.removeQuery().build() throws exception because URI syntax (xxxxxxxxxxxxxxxxxxxxxxxxxxxx:443) is incorrect.

**Comment by rajeshbanuka** [comment]
Is this issue fixed?

**Comment by rajeshbanuka** [comment]
what is the solution
