### ISSUE TITLE
GraphiteReporter does not report Gauge<Boolean>

### ISSUE THREAD

**Issue by efindley** [dropwizard/metrics#951]
I have been trying to use the `HystrixCodahaleMetricsPublisher` plugin to export Hystrix data to Graphite. (https://github.com/Netflix/Hystrix/tree/master/hystrix-contrib/hystrix-codahale-metrics-publisher) That plugin registers several `Gauge<Boolean>` objects to the MetricsRegistry.  I noticed, however, that the GraphiteReporter will ignore all of those since it does not include `Boolean` in its `format` method.  
Can the GraphiteReporter be updated to handle Boolean values?

**Comment by neilcronin** [comment]
@efindley I had a similar issue and created a PR https://github.com/dropwizard/metrics/pull/921  If that ever gets merged, it should be simple to add Boolean to the mix.

**Comment by arteam** [comment]
Contributed in #905.
