### ISSUE TITLE
Does a counter inc operation can fail?

### ISSUE THREAD

**Issue by YossiShasha** [dropwizard/metrics#954]
I am using Counter and try to increment it from different threads simultaneously. does one or more of the increment operation can fail number of times and evantually just don't update the counter? Or does it tries to update it until it succeeds? I am asking it since I have inconsistency with two different Counters values that are supposed to have the same value because they are pretty much incremented together when a certain event happens.

**Comment by ryanrupp** [comment]
All metrics are thread safe, for Counter the library is using a backport of Java 8's LongAdder so it *should* be thread safe at least short of a bug. I did diff LongAdder from Java 8 vs Metrics and it's different but I would explore first if there's anyway your code paths could result in the counters not both being incremented.
