### ISSUE TITLE
@Counted annotation does not work (metrics-core-3.1.2) in jersey2

### ISSUE THREAD

**Issue by m-ramanna** [dropwizard/metrics#956]
Seems like @ Counted is not implemented in InstrumentedResourceMethodApplicationListener (metrics-jersey2)

@ Timed and @ ExceptionMetered do work however.

**Comment by marshallpierce** [comment]
If counting resource method invocations is what you're after, https://bitbucket.org/marshallpierce/jersey2-metrics (my alternate jersey2 integration) supports them.

**Comment by m-ramanna** [comment]
Thanks @marshallpierce .  Are you able to contribute back to the project

**Comment by marshallpierce** [comment]
It's a standalone project. You can use it as is.

**Comment by tobilarscheid** [comment]
Hi, facing the same issue, I think this is really something dropwizard should support OOB.
