### ISSUE TITLE
ScheduledReporter.start has unexpected behavior when reporting take a long time

### ISSUE THREAD

**Issue by taviLaies** [dropwizard/metrics#958]
This is an issue that can happen with any reporter that takes longer to complete than the reporting interval.

Here is my setup but it's not very relevant because this problem can be reproduced with any reporter that takes longer than the reporting interval:

I am using the Graphite reporter with a reporting interval of 10s.
So here's what happens when Carbon crashes in my AWS environment:
1. The socket write takes a LOONG time to throw a Broken pipe exception (many minutes)
2. Because the ScheduledReporter uses scheduleAtFixedDelay and the task was blocked for minutes it tries to "catch up" with all executions and re-executes the task thousands of times with no delay
3. This time the connections cannot be established so it throws a Connection refused exception immediately
4. Thus the thread just pegs the CPU and it causes the Java process to become unresponsive

**Comment by arteam** [comment]
#999 now provides the ability to set the initial delay for `ScheduledReporter`.
