### ISSUE TITLE
`MetricRegistry` may call `notifyListenerOfAddedMetric` for the same metric multiple times

### ISSUE THREAD

**Issue by mzalimeni** [dropwizard/metrics#960]
When adding a `MetricRegistryListener` to a `MetricRegistry`, concurrently registered metrics can be reported multiple times to the added listener.

This is caused by a lack of synchronization between `MetricRegistry.register` and `MetricRegistry.addListener`, both of which call `MetricRegistry.notifyListenerOfAddedMetric` (the first for new metric registration, the second to propagate existing metrics to the listener).

**Comment by ryantenney** [comment]
Strictly speaking it is thread-safe, the issue is that its delivery semantics are at-least-once message delivery. Exactly-once would be possible, but I have concerns about a call to `addListener` blocking calls to `register`.

**Comment by mzalimeni** [comment]
Thanks for the quick reply! And good point, sorry for the misnomer. I've updated the title.

I think I understand the concern about blocking `register` with `addListener`, since you have no guarantees about the behavior of the listener, but in our case (and I'd guess many cases), synchronization there would be tolerable. I think I can find a workaround in our case, but a feature supporting exactly-once notification in some way might be useful.

At any rate, it might be helpful to update the method documentation to call out the existing behavior explicitly.

**Comment by ryantenney** [comment]
An update to the documentation is a good idea, I can see that being an important piece of information to have available when implementing a listener.  I'll look into ways we could support exactly-once delivery with minimal overhead.  Also if you think of something please let me know.
