### ISSUE TITLE
More flexible metric naming

### ISSUE THREAD

**Issue by remmeier** [dropwizard/metrics#964]
Various tools like promtheus, influxdb and elasticsearch move away from simple dotted metric naming schemes and instead make use of tagging. See for example here:

https://influxdb.com/docs/v0.9/concepts/schema_and_data_layout.html

It could prove useful if the MetricRegistry could be extended by such a tagging mechanism and the various reports make use of it.  

Stagemonitor introduced the same concept with Metric2Registry and MetricName. See https://github.com/stagemonitor/stagemonitor/tree/master/stagemonitor-core/src/main/java/org/stagemonitor/core/metrics/metrics2.

**Comment by ryantenney** [comment]
Yes, this will be a key feature of metrics 4. We've already introduced MetricName in the master branch, which takes both a name and a set of tags.  More work is required to adapt the reporters to use the tags.  If you can help with that, let's chat!

**Comment by ryantenney** [comment]
I've also opened #977 to track the conversion of existing reporters to be tag-aware.

**Comment by remmeier** [comment]
regarding PRs I'm currently look more into things like Hibernate metrics, generic UIs, https://github.com/dropwizard/metrics/issues/976 and tracing integration (such as zipkin) if there is a need for that, otherwise I put that on a private repo.
