### ISSUE TITLE
Accurate reporting when using multiple reporters

### ISSUE THREAD

**Issue by harelba** [dropwizard/metrics#967]
When using multiple reporters, the data is not the same for all reporters. This is caused because the snapshots/counters are managed by each reporter individually. If the snapshotting of the data would happen in the "infra" and send to the report so it can just report it, that would provide two benefits:
1. Accurate reporting to multiple reporters (Same numbers sent to each)
2. The ability to provide a "reset on snapshot" capability in the library level - Resetting the metric registry to empty at every interval, allowing metrics which don't accumulate over time.

**Comment by ryantenney** [comment]
The problem is that reporters follow a pull model, so we can't just convert reporters to accept collections of snapshots.

**Comment by harelba** [comment]
Hi, Thanks Ryan for the reply.

Could we do something like one composite reporter which pulls the entire data, and then provides it to the various reporters? This might introduce a change in the reporter interface, but if i'm not missing something, then it shouldn't change the semantics, right?

If you agree, then I'd be glad to have a go at such a change and see if it leads to a good place.

**Comment by marshallpierce** [comment]
I think this only achieves goal 1 (accurate reporting), not goal 2 (resetting). (FWIW I think that metrics should reset on every snapshot and it should be up to upstream things to decide to aggregate if they want.) You'd need to either change the metric internals for Counter, etc, to reset, or use regrettable hacks like the 'reset on snapshot' reservoir variant in https://bitbucket.org/marshallpierce/hdrhistogram-metrics-reservoir.

**Comment by harelba** [comment]
I completely agree. We've been very heavy users of the great codahale metrics in my last company (5M metrics per minute, 200 dashboards), and the fact that all counters required derivatives (non negative ones), and histograms were very hard to reason about because it wasn't clear about what time interval there refer to, has shown us that reset-on-snapshot would have been much better. Frankly, I would even prefer solving the reset-on-snapshot issue than the multiple reporters accuracy.

btw, when there's "holes in the data" due to network issues, or machines restarting, then reset-on-snapshot prevents major correctness issues (doing a "derivative" on data with holes skews the data and creates a lot of correctness issues).

oh, and another thing - We've been trying to use the HdrHistogram reserviour, but the current way that metrics registry is written doesn't provide us with the capability to add it as a "natural" new type of metric (or override all histograms/timers) - We actually need to create our own metric registry for supporting that out of the box (since getOrAdd and "metrics" fields inside MetricRegistry are not protected).

Harel

**Comment by marshallpierce** [comment]
Yeah, the lack of ability to set a default is tricky (I used a separate map in jersey2-metrics https://bitbucket.org/marshallpierce/jersey2-metrics/src/ecfc46d072f905f2b1fa691edd4ad33ef17a4e6e/jersey2-metrics-core/src/main/java/org/mpierce/jersey2/metrics/MetricProvider.java?at=master but that's not exactly elegant). However, I don't think even setting a global default would necessarily be suitable, as I can conceive of legitimate use cases that might want to have different defaults for different sections of a service or things like that. What about a third-party library, for instance, that might use metrics and expect the behavior of a certain reservoir type? Anyway, I'm straying OT so I'll stop there.

Reset-on-snapshot will be problematic if you have more than one reporter, though (unless we also have "one snapshot feeds every reporter"-style reporting).

**Comment by rehevkor5** [comment]
I just ran into this too, when adding a `HdrHistogramResetOnSnapshotReservoir` to a Dropwizard app which uses a java agent to gather JMX metrics and send them to a server. Here are some more factors to consider about eg. https://github.com/dropwizard/metrics/blob/4.0-development/metrics-jmx/src/main/java/com/codahale/metrics/jmx/JmxReporter.java#L251

- Creating multiple snapshots is more costly, for Histograms it's about 10x the cost
- If using a reporter such as com.codahale.metrics.JmxReporter, the various values retrieved from a single Histogram are not self-consistent, since each value comes from a different snapshot (even if you're not doing reset-on-snapshot)

To solve this, I'll probably omit these metrics from the JMX reporting, and use something like https://github.com/ReadyTalk/metrics-statsd/blob/master/metrics3-statsd/src/main/java/com/readytalk/metrics/StatsDReporter.java to send them directly to the server.
