### ISSUE TITLE
Move to Java 8

### ISSUE THREAD

**Issue by bentatham** [dropwizard/metrics#971]
From @ryantenney in #837 
> I keep ~~been~~ second guessing the decision to move to Java 8, but let's do it. We'll still have v3.2 for anyone stuck on Java <=7.
> 
> With regard to default methods on interfaces, I'd encourage you to not overuse them. I think that they should be generally avoided unless a) the interface is intended to be used as a lambda function, or b) an existing interface is being expanded and we need to maintain backwards compatibility.

This means we can move forward and make use of lambdas for gauges, and other benefits.

**Comment by ryantenney** [comment]
Now I notice the extra word in my post *facepalm*

**Comment by ryantenney** [comment]
Closed by #974
