### ISSUE TITLE
Customizable Servlets

### ISSUE THREAD

**Issue by remmeier** [dropwizard/metrics#976]
AdminServlet, MetricsServlet and MetricsModule are currently quite hard to customize (without copy/pasting the code). It could be benefitial if:
- AdminServlet.init calls newHealthCheckServlet, newMetricsServlet, newMetricsServlet, newThreadDumpServlet methods that allow subclasses to return a custom implementation.
- GaugeSerializer, CounterSerializer, HistogramSerializer, MeterSerializer, TimerSerializer, MetricRegistrySerializer are no longer private within MetricsModule.
- MetricsServlet.init calls a newObjectMapper method, which calls a newMetricsModule to allow customizations.
- Snapshot class handling could be generalized so that it can be implemented by Gauges and Counters as well, not only by Histograms. For example, Gauge could provide a history of values for the past hour with values sampled every 10 second.

=> I created a basic angular 2 application that allows to browser all metrics using such modified servlets. e.g. Gauge values are shown as line charts over time. 

Maybe related to https://github.com/dropwizard/metrics/issues/964 it could also be beneficial if metrics are able to provide unit type information. Like values being "bits", "bytes", "seconds", etc. This would further ease implementing a generic UI.

**Comment by remmeier** [comment]
I can do a pr if the ticket sound reasonable :-)

**Comment by tommy-bo** [comment]
@remmeier I made a PR for customizing AdminServlet in case you find it usable: #991

**Comment by arteam** [comment]
Hello @remmeier,

I find all your suggestions very reasonable, would gladly review a pull request in case if you have time to contribute.

**Comment by remmeier** [comment]
in the meantime I started working a bit in another direction based on jsonapi resp. the katharsis java implementation (http://jsonapi.org/format/). It provides a bit a richer api with meta-data, sorting, filtering, etc. Potentially I can put that somewhere at some point.
