### ISSUE TITLE
How to set Thread Pool in embed jetty 9 in spring boot

### ISSUE THREAD

**Issue by acidlychee** [dropwizard/metrics#983]
it seems can't recreate a server with the InstrumentedQueuedThreadPool.If add a JettyServerCustomizer , just  change the existed ThreadPool's params, but can't set a InstrumentedQueuedThreadPool

**Comment by ryantenney** [comment]
I'm sorry, I don't understand the question.

**Comment by acidlychee** [comment]
@ryantenney  sorry , my english is poor.. I hava found the solution in spring boot issue.
https://github.com/spring-projects/spring-boot/issues/3687

**Comment by ryantenney** [comment]
Glad to hear it!
