### ISSUE TITLE
InfluxDB reporter uses not supported json protocol

### ISSUE THREAD

**Issue by mmatloka** [dropwizard/metrics#985]
Hi,
According to https://docs.influxdata.com/influxdb/v0.13/write_protocols/json/

> The JSON write protocol is no longer a valid write protocol for InfluxDB.

Library created from Dropwizard metrics already supports line protocol https://github.com/iZettle/dropwizard-metrics-influxdb .

**Comment by arteam** [comment]
We don't support InfluxDB in the core, despite it was merged to master at some point of time.
